### ISSUE TITLE
[Module Proposal]: avm-ptn-aap-openai-cognitivesearch (tf)

### ISSUE THREAD

**Issue by mariocon** [Azure/Azure-Verified-Modules#1000]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes.

### Bicep or Terraform?

Terraform

### Module Classification?

Pattern Module

### Module Name

avm-ptn-aap-openai-cognitivesearch (tf)

### Module Details

This is a pattern module proposal for a Corporate Line of Business (LoB) ChatBot application using Azure OpenAI and Azure Cognitive Search Service.  It includes:

- Azure App Gateway
- Azure App Service Premium v3 (Linux): Web App + API App
- Azure BLOB Storage
- Azure SQL Database
- Azure Cache for REDIS
- Azure App Insights
- Private VNET

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

mariocon

### (Optional) Secondary Module Owner's GitHub Username (handle)

andbron, mikestiers-msft

**Comment by prjelesi** [comment]
@mariocon let finish formal part:

 - Shouldn’t this be a resource module? What makes it a pattern - e.g., does it deploy multiple resources?
- What is it for? What problem does it fix or provides a solution for?
- What is/isn’t part of it? Which resource and/or pattern modules are planned to be leveraged in it? Provide a list of resources that would be part of the planned module.
- Where is it coming from/what’s backing it - e.g., Azure Architecture Center (AAC), community request, customer example. - - - 
 - Provide an architectural diagram and related documentation if possible - or a pointer to these if they are publicly available.

**Comment by prjelesi** [comment]
@mariocon can you please respond on previous ask?

**Comment by mariocon** [comment]
Hello Team,

Closing the issue, as I will be transferring this over to other member of our ISD Acceleration & Automation team. A new request will be submitted.
