### ISSUE TITLE
[Module Proposal]: `avm-ptn-sentinel`

### ISSUE THREAD

**Issue by cshea-msft** [Azure/Azure-Verified-Modules#1014]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes.

### Bicep or Terraform?

Terraform

### Module Classification?

I'm not sure, please advise

### Module Name

avm-ptn-sentinel

### Module Details

Creating a Pattern module that deploys Sentinel, configures alerts, data connectors, watchlists, 

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

cshea-msft

### (Optional) Secondary Module Owner's GitHub Username (handle)

amurrell1

**Comment by prjelesi** [comment]
@cshea-msft can you check this and confirm with module owner that you are not overlapping https://github.com/Azure/Azure-Verified-Modules/issues/760 ?

**Comment by cshea-msft** [comment]
hey @prjelesi i didn't see that one, not sure how I missed it. Yes that will probably overlap so we can remove this one. Thanks for sharing.

**Comment by prjelesi** [comment]
@cshea-msft i will close it. In case that we need to reopen it, just ping us.
