### ISSUE TITLE
[Module Proposal]: `avm-utl-regions`

### ISSUE THREAD

**Issue by matt-FFFFFF** [Azure/Azure-Verified-Modules#1034]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes.

### Bicep or Terraform?

Terraform

### Module Classification?

I'm not sure, please advise

### Module Name

avm-utl-regions

### Module Details

Utility module to get data from about Azure regions

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

matt-FFFFFF

**Comment by matt-FFFFFF** [comment]
This will be an import of the existing work: https://github.com/Azure/terraform-azurerm-regions

**Comment by prjelesi** [comment]
Hi @matt-FFFFFF 

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by matt-FFFFFF** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by prjelesi** [comment]
Thank you Mr @matt-FFFFFF !

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

Before starting development, please ensure ALL the following requirements are met.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - for naming your module
  - `TelemetryIdPrefix` - for your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repo name and folder path are defined in `RepoURL`
  - Create GitHub teams for module owners and contributors and grant them permissions as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
  - Grant permissions for the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

Check if this module exists in the other IaC language. If so, collaborate with the other owner for consistency. 👍

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published! Please include a link pointing to your PR, once available. 🙏**

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by matt-FFFFFF** [comment]
On my list to port across

**Comment by matt-FFFFFF** [comment]
Published https://registry.terraform.io/modules/Azure/avm-utl-regions/azurerm

**Comment by matt-FFFFFF** [comment]
@PmeshramPM @mbilalamjad @prjelesi Module published - please can you update the workflow?

**Comment by mbilalamjad** [comment]
> @PmeshramPM @mbilalamjad @prjelesi Module published - please can you update the workflow?

@matt-FFFFFF it seems the [AVM Review process](https://azure.github.io/Azure-Verified-Modules/contributing/terraform/review/) for this module has been skipped which we're requiring all module owners for AVM TF modules. Appreciate if you could do the "Requested Actions" on the below to finish the review process of the module so that we can mark it as compliant and available in the module Index on the AVM website
https://github.com/Azure/terraform-azurerm-avm-utl-regions/issues/8
