### ISSUE TITLE
[Module Proposal]: `avm-res-oracledatabase-cloudexadatainfrastructure`

### ISSUE THREAD

**Issue by terrymandin** [Azure/Azure-Verified-Modules#1052]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-oracledatabase-cloudexadatainfrastructure

### Module Details

Create a resource module to deploy [Oracle Exadata Infrastructure](https://learn.microsoft.com/en-us/azure/oracle/oracle-db/provision-oracle-exadata-infrastructure).  

This will be used in the [avm-ptn-odaa-tf](https://github.com/Azure/Azure-Verified-Modules/issues/1051) pattern module. 

### Do you want to be the owner of this module?

No

**Comment by prjelesi** [comment]
Hi @terrymandin 

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by prjelesi** [comment]
@sihbher do you want to own this module?

**Comment by sihbher** [comment]
> @sihbher do you want to own this module?

Yes, I do

**Comment by prjelesi** [comment]
Oki doki, let finish process.

Hi @sihbher 

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm you agree to the below pages that define what module ownership means:

[Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
[Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
[Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)
Any questions or clarifications needed, let us know!

If you agree, please just reply to this issue with the exact sentence below (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by sihbher** [comment]
Hi,

I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by terrymandin** [comment]
Please make me a contributor.

**Comment by mbilalamjad** [comment]
Hi @sihbher,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

We just want to ask you to double check a few important things.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- You must be the owner of the GitHub teams as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
- Please check that your name has been updated in the module index page (this should happen shortly after you confirmed ownership).

You can now take ownership of this module and start improving it as needed! ✅ Happy coding! 🎉

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by mbilalamjad** [comment]
@sihbher, @terrymandin this has been provisionally approved, can you please double check and confirm the Resource Provider and Resource Type for this resource module, once you do the module index can be updated to complete the approval process.
CC: @prjelesi

**Comment by prjelesi** [comment]
Module name updated. 
Index file updated

**Comment by sihbher** [comment]
The initial review of this module is complete, and the module has been published to the registry. Requesting AVM team to close this module proposal and mark the module available in the module index.
Terraform Registry Link: [Azure/avm-res-oracledatabase-cloudexadatainfrastructure/azurerm | Terraform Registry](https://registry.terraform.io/modules/Azure/avm-res-oracledatabase-cloudexadatainfrastructure/azurerm/latest)
GitHub Repo Link: [Azure/terraform-azurerm-avm-res-oracledatabase-cloudexadatainfrastructure: Azure Verified Module for Oracle Exadata Infrastructure (github.com)](https://github.com/Azure/terraform-azurerm-avm-res-oracledatabase-cloudexadatainfrastructure)
