### ISSUE TITLE
[Orphaned Module]: `avm/res/communication/email-service`

### ISSUE THREAD

**Issue by krbar** [Azure/Azure-Verified-Modules#1055]
### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/communication/email-service

### Module Details

This is an "Orphaned Module" issue to change the ownership of the `avm/res/communication/email-service` module to @donk-msft, which has been agreed with him.

### Do you want to be the new owner of this module?

No

### Module Owner's GitHub Username (handle)

donk-msft

**Comment by matebarabas** [comment]
Hi @donk-msft,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by donk-msft** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by matebarabas** [comment]
Hi @donk-msft,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

We just want to ask you to double check a few important things.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- You must be the owner of the GitHub teams as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
- Please check that your name has been updated in the module index page (this should happen shortly after you confirmed ownership).

You can now take ownership of this module and start improving it as needed! ✅ Happy coding! 🎉

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by matebarabas** [comment]
@krbar, have the related GH teams already been handed over to @donk-msft? Thanks!

**Comment by krbar** [comment]
@matebarabas The GH-Teams are transferred to @donk-msft

**Comment by matebarabas** [comment]
Thanks for confirming, @krbar! I'm closing this issue now.
