### ISSUE TITLE
[Question/Feedback]: Error on Lock variable declaration 

### ISSUE THREAD

**Issue by herms14** [Azure/Azure-Verified-Modules#106]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Received the following error when adding the Lock interface in my module 

Error: Unsupported attribute
│ 
│   on variables.tf line 209, in variable "lock":
│  209:     condition     = contains(["CanNotDelete", "ReadOnly", "None"], var.lock.type)
│     ├────────────────
│     │ var.lock is a object
│ 
│ This object does not have an attribute named "type".

Added a type argument to resolve the issue

`variable "lock" {
  type = object({
    name = optional(string, null)
    kind = optional(string, "None")
    type = optional(string, "None")
  })
  default = {}

  validation {
    condition     = contains(["CanNotDelete", "ReadOnly", "None"], var.lock.type)
    error_message = "Lock type must be one of: CanNotDelete, ReadOnly, None."
  }
}`

**Comment by jtracey93** [comment]
@matt-FFFFFF can you take a look at this one

**Comment by matt-FFFFFF** [comment]
Fixed here:

https://azure.github.io/Azure-Verified-Modules/specs/shared/interfaces/#resource-locks

@herms14 please advise if this makes sense

**Comment by herms14** [comment]
looks good to me @matt-FFFFFF
