### ISSUE TITLE
[Module Proposal]: `avm-ptn-aks-economy`

### ISSUE THREAD

**Issue by ms-henglu** [Azure/Azure-Verified-Modules#1061]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes.

### Bicep or Terraform?

Terraform

### Module Classification?

Pattern Module

### Module Name

avm-ptn-aks-economy

### Module Details

This is the original comprehensive AKS Verified Module, including 100+ properties and giving users the freedom to configurate their files with their exact specifications: https://github.com/Azure/terraform-azurerm-aks. These configuration options are incredibly comprehensive, encompassing every facet of AKS configuration. However, this design may pose challenges for individuals who prefer streamlined options or lack extensive AKS background knowledge. To ensure seamless experience for all users and to keep pace with the growing AKS Azure user base, we want to launch several simplified versions of the AKS module. These streamlined versions will feature default settings for certain complex configurations, mirroring the user-friendly design in the Azure Portal.

We will categorize the AKS modules based on the cluster preset configuration settings. This approach is essential as modules are significantly impacted by these configurations, influencing resource allocation, scalability, cost, compatibility, networking, security, and various other aspects.

This is one of the simplified AKS module we want to release, and is the production economy standard module.

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

ms-henglu

**Comment by prjelesi** [comment]
Hi @ms-henglu 

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by ms-henglu** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by prjelesi** [comment]
Hi @ms-henglu 

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

Before starting development, please ensure ALL the following requirements are met.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - for naming your module
  - `TelemetryIdPrefix` - for your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repo name and folder path are defined in `RepoURL`
  - Create GitHub teams for module owners and contributors and grant them permissions as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
  - Grant permissions for the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

Check if this module exists in the other IaC language. If so, collaborate with the other owner for consistency. 👍

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published! Please include a link pointing to your PR, once available. 🙏**

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by ms-henglu** [comment]
I have completed my initial development of the module and I would like to request a review of my module before publishing it to the terraform registry. The latest code is in a PR titled [AVM-Review-PR](https://github.com/Azure/terraform-azurerm-avm-ptn-aks-economy/pull/3) on the module repo and all checks on that PR are passing.

**Comment by ms-henglu** [comment]
Hi @mbilalamjad , this module is ready for review, would you please move this issue to "In Review"? Thanks!
