### ISSUE TITLE
[Question/Feedback]: Resource naming to follow CAF abbreviation best practices

### ISSUE THREAD

**Issue by RossCavanagh** [Azure/Azure-Verified-Modules#109]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Initially, great job, I feel AVM wil really take off quickly. I only just learnt about it via the recently ALZ community call and already poking around anything with AVM in the git repos now. So, thank you.

Regarding naming, within our company we were trying to adhere to the CAF best practices [Abbreviation examples for Azure resources](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations), and we were doing that via [terraform-azurerm-naming](https://github.com/Azure/terraform-azurerm-naming). I'm hoping that something like this could be the standard across the board in some way. I say this as I was looking at the [AVM Terraform storage module](https://github.com/Azure/terraform-azurerm-avm-res-storage-storageaccount/tree/main) and noticed that was using:

`name = "storage${random_pet.this.id}"`

Vs the CAF abbreviation. Thought this is possibly something that could be baked into AVM to make sure resources are consistent.

Again, awesome job on this, many thanks!

**Comment by jtracey93** [comment]
Hey @RossCavanagh,

Thanks for the issue, great suggestion and showing of support for AVM 👍

I'll discuss this with the rest of the AVM team and look to add this as a shared requirement as I personally think its a great idea to default to the CAF abbreviations and then provide the option to overwrite so any naming standard can be used.

> Also please note that the Storage is in the process of becoming AVM aligned, as shown in the [index](https://azure.github.io/Azure-Verified-Modules/indexes/terraform/tf-resource-modules/)
