### ISSUE TITLE
[Module Proposal]: `avm-res-network-virtualnetworkgateway`

### ISSUE THREAD

**Issue by PmeshramPM** [Azure/Azure-Verified-Modules#1097]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-network-virtualnetworkgateway

### Module Details

AVM Resource Module for Virtual Network Gateway

### Do you want to be the owner of this module?

No

**Comment by ASHR4** [comment]
I'm interested in being an external contributor once a module owner has been found :)

**Comment by prjelesi** [comment]
@PmeshramPM i think that this is covered by this module https://github.com/Azure/Azure-Verified-Modules/issues/157

agree?

**Comment by prjelesi** [comment]
Closing as we have existing pattern.
