### ISSUE TITLE
Multi / cross subscription usage 

### ISSUE THREAD

**Issue by urc1712** [Azure/Azure-Verified-Modules#1106]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

I was using AVM virtual machine module to deploy the VM to one subscription with existing resources from another subscription, I am not sure how to achieve this kind of requirements with thia modules. I would request you to provide the suggestions and recommendations. 
```[tasklist]
### Tasks
```

**Comment by jtracey93** [comment]
Hey @urc1712,

Can you let us know whether this is for Bicep or Terraform?

Also I'd recommend opening this issue on the modules source code repository as thats where the module owners will track issues/feature requests etc.

Thanks

#RR
