### ISSUE TITLE
[Module Proposal]: `avm-res-mssql-database`

### ISSUE THREAD

**Issue by thejrayasam** [Azure/Azure-Verified-Modules#1112]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-mssql-database

### Module Details

AVM Resource Module for MSSQL Database

### Do you want to be the owner of this module?

No

**Comment by prjelesi** [comment]
@thejrayasam is this request for child resource of https://github.com/Azure/Azure-Verified-Modules/issues/442 ?

tagging @mbilalamjad for visibility.

**Comment by sujaypillai** [comment]
@prjelesi If this module is still looking for an owner, then I can take it up. @thejrayasam & me are collaborating on this.

**Comment by mbilalamjad** [comment]
Hey @sujaypillai & @thejrayasam, would there be a scenario where a module for azurerm_mssql_database would be needed independent of azurerm_mssql_server? if not then I would recommend we leverage the module proposed for azurerm_mssql_server and your contribution to that module would be appreciated.

**Comment by thejrayasam** [comment]
Closing the issue as there is no requirement to create an independent module azurerm_mssql_database for now, and it can be part of azurerm_mssql_server.
