### ISSUE TITLE
[Module Proposal]: `avm-res-portal-dashboard`

### ISSUE THREAD

**Issue by VeronicaSea** [Azure/Azure-Verified-Modules#1125]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-portal-dashboard

### Module Details

Deploy the azure portal dashboard.

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

VeronicaSea

### (Optional) Secondary Module Owner's GitHub Username (handle)

vedagudipati

**Comment by prjelesi** [comment]
HI @VeronicaSea 

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by prjelesi** [comment]
@VeronicaSea can you please respond on message above?

**Comment by VeronicaSea** [comment]
@prjelesi I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER. Thanks.

**Comment by VeronicaSea** [comment]
Will use this one https://github.com/Azure/Azure-Verified-Modules/issues/788 to track this AVM model proposal.
