### ISSUE TITLE
[Module Proposal]: `Microsoft.Authorization/roleAssignments`

### ISSUE THREAD

**Issue by darrenFrowen** [Azure/Azure-Verified-Modules#1126]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes.

### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

role-assignments

### Module Details

Hi,

Although each resource has options to add 'Microsoft.Authorization/roleAssignments' to each resource, there maybe a requirement where the role assignment is required at the subscription scope and as such there doesn't seem to be an option for this as a standalone resource to be able to perform that operation. 

### Do you want to be the owner of this module?

No

**Comment by matebarabas** [comment]
Hi @darrenFrowen,

Please note that the following authorization related pattern modules are already available:
- variable scope role assignment (for resource group, subscription, management group level assignments), [here](https://github.com/Azure/bicep-registry-modules/tree/main/avm/ptn/authorization/role-assignment)
- resource level role assignment, [here](https://github.com/Azure/bicep-registry-modules/tree/main/avm/ptn/authorization/resource-role-assignment)

As this proposal seems redundant with these existing modules, I'm closing it now. Please feel free to reopen it if you have further comments/questions. Thank you!

**Comment by darrenFrowen** [comment]
Apologies I didn’t think to look in the pattern module apologies On 21 Jun 2024, at 16:54, Máté Barabás ***@***.***> wrote:﻿
Hi @darrenFrowen,
Please note that the following authorization related pattern modules are already available:

variable scope role assignment (for resource group, subscription, management group level assignments), here
resource level role assignment, here

As this proposal seems redundant with these existing modules, I'm closing it now. Please feel free to reopen it if you have further comments/questions. Thank you!
