### ISSUE TITLE
[Orphaned Module]: `avm/res/storage/storage-account`

### ISSUE THREAD

**Issue by ChrisSidebotham** [Azure/Azure-Verified-Modules#1128]
### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/storage/storage-account

### Module Details

Change of primary ownership for module

### Do you want to be the new owner of this module?

No

### Module Owner's GitHub Username (handle)

KTremain

### (Optional) Secondary Module Owner's GitHub Username (handle)

fblix

**Comment by matebarabas** [comment]
Hi @ktremain,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by ktremain** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by matebarabas** [comment]
Hi @ktremain,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

We just want to ask you to double check a few important things.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- You must be the owner of the GitHub teams as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
- Please check that your name has been updated in the module index page (this should happen shortly after you confirmed ownership).

You can now take ownership of this module and start improving it as needed! ✅ Happy coding! 🎉

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by matebarabas** [comment]
@fblix, can you please add @ktremain to both the -owners- and -contributors- GH teams, and make him a maintainer in both? Please confirm it here, when it's done. Thanks!

**Comment by fblix** [comment]
I've added @KTremain to both the owner and contributors GH Teams. He is now also a maintainer on both.

**Comment by matebarabas** [comment]
Thank you for confirming, I'll update the module index later today. I'm closing this issue now.
