### ISSUE TITLE
`avm-res-compute-availabilitysets`

### ISSUE THREAD

**Issue by Navid-db** [Azure/Azure-Verified-Modules#1135]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-compute-availabilitysets

### Module Details

It helps improve the resiliency of our applications by minimizing the impact of potential failures like hardware or software issues within Azure data centers.

### Do you want to be the owner of this module?

No

**Comment by cshea-msft** [comment]
@prjelesi - this shouldn't be a module. We are recommending Availability Zones and if zones are not available we are suggesting they use VMMS with flexible orchestration mode https://learn.microsoft.com/en-us/azure/virtual-machines/availability-set-overview

**Comment by prjelesi** [comment]
Closing this as not needed
