### ISSUE TITLE
Question: security best practices AVM

### ISSUE THREAD

**Issue by roysha1** [Azure/Azure-Verified-Modules#1138]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Great initative!

With Microsoft SFI,
Are there any plans to provide best practices from security aspects?

Do avm plan to have flag of secured or hardened resources out of the box?

**Comment by jtracey93** [comment]
Hey @roysha1,

We are indeed aligning all AVM modules to Well-Architected Framework best practices and that encompasses the security pillar, right now we are knuckling down on reliability but when that is complete our next focus area is doing the same for security 👍
