### ISSUE TITLE
[Question/Feedback]: Add Shared Requirement for Testing Child and Extension Resources

### ISSUE THREAD

**Issue by jtracey93** [Azure/Azure-Verified-Modules#114]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Add Shared Requirement for Testing Child and Extension Resources

cc: @matt-FFFFFF

**Comment by matebarabas** [comment]
@jtracey93, @matt-FFFFFF, are there any updates on this? Did this become an internal ADO item over time?

**Comment by jtracey93** [comment]
@matebarabas i dont believe it did. Just needs doing :)

**Comment by jtracey93** [comment]
https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr24---category-testing---testing-child-extension--interface-resources
