### ISSUE TITLE
[Orphaned Module]: `avm/res/sql/server`

### ISSUE THREAD

**Issue by matebarabas** [Azure/Azure-Verified-Modules#1141]
### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/sql/server

### Module Details

This module was previously owned by @bryansan-msft. When a new owner volunteers, the related GitHub teams need to be handed over by Bryan.

Original module proposal: https://github.com/Azure/Azure-Verified-Modules/issues/295

### Do you want to be the new owner of this module?

No

**Comment by emichellecarter** [comment]
I am willing to take the maintenance on this module.

**Comment by matebarabas** [comment]
Hi @emichellecarter,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by send-itDuong** [comment]
Can we get confirmation that this module is no longer orphaned? The README file still indicate that it still is. 

Thanks!

**Comment by matebarabas** [comment]
Hi @send-itDuong, the ownership is not yet transferred to @emichellecarter as her response to the above is still pending.

**Comment by emichellecarter** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER.  Thank you

**Comment by matebarabas** [comment]
Hi @emichellecarter,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

Before starting development, please ensure ALL the following requirements are met.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - for naming your module
  - `TelemetryIdPrefix` - for your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repo name and folder path are defined in `RepoURL`
  - Create GitHub teams for module owners and contributors and grant them permissions as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
  - Grant permissions for the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

Check if this module exists in the other IaC language. If so, collaborate with the other owner for consistency. 👍

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published! Please include a link pointing to your PR, once available. 🙏**

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by matebarabas** [comment]
@bryansan-msft, can you please hand over the ownership of the 2 related GitHub teams to @emichellecarter?

@emichellecarter, can you Please also remove the `ORPHANED.md` file from the [module's folder](https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/sql/server) and its content from the README.md, by following the steps described in point 5 [here](https://azure.github.io/Azure-Verified-Modules/help-support/issue-triage/avm-issue-triage/#when-a-new-owner-is-identified) and let me know in a comment when this is done. Thanks!

**Comment by matebarabas** [comment]
@bryansan-msft, thanks for letting me know. With no members remaining in these two teams, we lost access to them, so we'll need to involve GH support, which might take longer. I'll take care of this.

**Comment by bryansan-msft** [comment]
You are a maintainer of the parent team. I am sure you can add him yourself

**Comment by matebarabas** [comment]
That's what we'd all hope for, but unfortunately that's not how teams work in GitHub. :) We've run into this once, and managed to solve it, so it will be fixed this time, it's just going to take some time. But don't worry about this, I'll handle it.

**Comment by matebarabas** [comment]
@emichellecarter, the request just went through. You should now be a maintainer in both teams. Please let me know when the orphaned.md file is updated too, so we can close this issue. Thank you!

**Comment by peterbud** [comment]
@matebarabas : Would it make sense to have two co-owners for this module? If yes, I'd be interested

**Comment by matebarabas** [comment]
@peterbud, each module can have 1 owner (primary owner), 1 co-owner (secondary owner), and any number of contributors. As @emichellecarter is now the owner of this module, you can definitely be its secondary owner. Should I sign you up?

PS: @emichellecarter, I can see the orphaned.md has been updated, so I'm closing this issue now.

**Comment by peterbud** [comment]
Yes, pls sign me up
