### ISSUE TITLE
[Orphaned Module]: `Microsoft.MachineLearningServices/workspaces`

### ISSUE THREAD

**Issue by ross-p-smith** [Azure/Azure-Verified-Modules#1147]
### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/machine-learning-services/workspace

### Module Details

We will be working on this module as part of a project so we can take ownership

### Do you want to be the new owner of this module?

Yes

### Module Owner's GitHub Username (handle)

cecheta

### (Optional) Secondary Module Owner's GitHub Username (handle)

ross-p-smith

**Comment by matebarabas** [comment]
@ross-p-smith, thank you for volunteering to co-own this module along with @cecheta! 

Please note that we already have an orphaned module issue for this: https://github.com/Azure/Azure-Verified-Modules/issues/697 
I'll close this one, and we can continue with the handshake on the original one.
