### ISSUE TITLE
[Question/Feedback]: Terraform RBAC interface sample change

### ISSUE THREAD

**Issue by jchancellor-ms** [Azure/Azure-Verified-Modules#116]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

The interface examples for role_assignments in Terraform has an error.  If we set the default value for condition_version to "2.0" the API requires condition to also have a value.  If we try to create a simple role association without a condition or condition_version value, it will fail as the 2.0 value is injected but no condition exists.  Recommend updating the example to the following:

condition_version = optional(string) instead of condition_version = optional(string, "2.0")

**Comment by jtracey93** [comment]
@matt-FFFFFF did you experience this with the key vault module? Can you take a look and update interfaces if required 👍 

I see the Interface in the Specs say
```hcl
variable "role_assignments" {
    type = map(object({
      role_definition_id_or_name             = string
      principal_id                           = string
      description                            = optional(string, null)
      skip_service_principal_aad_check       = optional(bool, true)
      condition                              = optional(string)
      condition_version                      = optional(string, "2.0")
      delegated_managed_identity_resource_id = optional(string)
    }))
    default = {}
  }
``` 

But in your key vault module its:

```hcl
variable "role_assignments" {
  type = map(object({
    role_definition_id_or_name             = string
    principal_id                           = string
    description                            = optional(string, null)
    skip_service_principal_aad_check       = optional(bool, false)
    condition                              = optional(string, null)
    condition_version                      = optional(string, null)
    delegated_managed_identity_resource_id = optional(string, null)
  }))
  default     = {}
...
}
```

Lets get it updated 👍

**Comment by matt-FFFFFF** [comment]
Yeah slipped through due to rapid pace of development!

Will fix
