### ISSUE TITLE
[Question/Feedback]: AVM GA 

### ISSUE THREAD

**Issue by MikeDmx** [Azure/Azure-Verified-Modules#1162]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Hello,

Just a quick question, did you know when AVM for terraform will be GA (stable release) ?

Regards,

**Comment by jtracey93** [comment]
Hey @MikeDmx,

As per the `README.md` of each Terraform module, they are ready for production usage right now 👍 
![image](https://github.com/Azure/Azure-Verified-Modules/assets/41163455/885f3882-d9f3-401f-8705-ef878d7aa27e)

We also discussed this on the latest community call which you can find here: https://youtu.be/LprWndLjLH0?si=TBQSNUit0xEghPId&t=459

So there is no such thing as a GA for AVM, but V1.0.0 will come but there is no fixed date on this just yet, much like Bicep & Terraform as languages have been released and moved towards v1.0.0's themselves.
