### ISSUE TITLE
[Module Proposal]: `avm/ptn/virtual-machine-images/azure-image-builder`

### ISSUE THREAD

**Issue by AlexanderSehr** [Azure/Azure-Verified-Modules#1191]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes.

### Bicep or Terraform?

Bicep

### Module Classification?

Pattern Module

### Module Name

avm/ptn/virtual-machine-images/azure-image-builder

### Module Details

This issues proposes to publish the ImageBuilder part of the `DevOps-Self-Hosted` [image builder construct](https://github.com/Azure/DevOps-Self-Hosted/wiki/Creating%20images%20with%20the%20Azure%20Image%20Builder):

![image](https://github.com/user-attachments/assets/4e280c10-2628-427f-80bb-a97035ff46b0)
 
Aside from 'just' the basis image template it would
- Enable the user to create an image and publish it to an Azure Image Gallery with one single deployment
- Perform all steps via the Azure Backbone (i.e., private networking)
- Enable the user to inject custom scripts that are automatically uploaded to a storage account to then use them during the customization steps
- Control if only a subset of resources should be deployed (e.g., only a new image), all all infrastructure compoents (which would include the image gallery, etc.)

The invocation at the end of the day would look as imple as shown [here](https://github.com/Azure/DevOps-Self-Hosted/blob/main/constructs/azureImageBuilder/deploymentFiles/sbx.image.bicep).

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

alexandersehr

**Comment by matebarabas** [comment]
Hi @AlexanderSehr,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by AlexanderSehr** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by AlexanderSehr** [comment]
> I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

It's written like I'm shouting at you. Ironically I am - when reading it

**Comment by matebarabas** [comment]
Hi @AlexanderSehr,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

Before starting development, please ensure ALL the following requirements are met.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - for naming your module
  - `TelemetryIdPrefix` - for your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repo name and folder path are defined in `RepoURL`
  - Create GitHub teams for module owners and contributors and grant them permissions as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
  - Grant permissions for the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

Check if this module exists in the other IaC language. If so, collaborate with the other owner for consistency. 👍

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published! Please include a link pointing to your PR, once available. 🙏**

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by AlexanderSehr** [comment]
Added long term label as several CI PRs of mine have to be reviewed and merged before this (already finished) ptn implementation can be merged as well

**Comment by matebarabas** [comment]
Related PR: https://github.com/Azure/bicep-registry-modules/pull/3005

**Comment by matebarabas** [comment]
- [x] Module published.
- [x] GitHub teams are available and assigned to their parents.
- [x] `CODEOWNERS` file updated.
- [x] Issue template file updated.
 
Thank you for your work @AlexanderSehr! I'm closing this issue now.
