### ISSUE TITLE
[Module Proposal]: `avm-res-desktopvirtualization-hostpool` (res) (tf)

### ISSUE THREAD

**Issue by jensheerin** [Azure/Azure-Verified-Modules#120]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals

### Check this module doesn't already exist in another project that is being evolved into AVM

- [X] I have checked for that this module doesn't already exist in CARML or TFVM

### Terraform or Bicep?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-desktopvirtualization-hostpool

### Module Details

Azure Virtual Desktop Resource Host pool to eventually be used in the pattern module for AVD LZA
I already have the code publish here ttps://github.com/Azure/avdaccelerator/blob/main/workload/terraform/greenfield/AADscenario/avd.tf and will be converting to AVM format. 

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username

@jensheerin

**Comment by matebarabas** [comment]
Aiming for consistency between the Bicep and Terraform version of the AVD resource modules as well as the pattern module of the AVD LZA, before moving on with this issue, @danycontre and @moisesjgomez will align internally with @jensheerin on the composition of the modules and other technical questions. 
CC: @cshea15

**Comment by jensheerin** [comment]
@matebarabas I met with @danycontre and @moisesjgomez and we are aligned. Can you we move to next steps?

cc: @cshea15 

I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by danycontre** [comment]
@jensheerin thanks for submitting the issue.

Some comments:

- Please update the module name to: avm-res-desktopvirtualization-hostpool, this is the naming we are using in line with the AVM team guidance.

**Comment by jensheerin** [comment]
Module name update to avm-res-desktopvirtualization-hostpool

**Comment by jensheerin** [comment]
@matebarabas Met with Matt White and reviewed all of the AVD tf module proposals and he approves moving to in development

**Comment by matebarabas** [comment]
Hi @jensheerin,

Thanks for requesting/proposing to be an AVM module owner.

We just want to confirm you agree to the below pages that define what module ownership means:

- https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions
- https://azure.github.io/Azure-Verified-Modules/specs/shared
- https://azure.github.io/Azure-Verified-Modules/help-support/module-support

Any questions or clarifications needed, let us know.

If you agree please just reply to this issue with the exact sentence below (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

> @jensheerin: I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by matebarabas** [comment]
Hi @jensheerin,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities.

We just want to ask you to double check a few important things before you start the development.

Please visit the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page of your module and use the following values explicitly as provided there:

- `ModuleName`
- `TelemetryIdPrefix`
- `ModuleOwnersGHTeam` and `ModuleContributorsGHTeam`
- Repository name and folder path defined in `RepoURL`

You can now start the development of this module! Happy coding! 🎉

Please respond to this comment, once your module is ready to be published!

Any further questions or clarifications needed, let us know.

Thanks,

The AVM Core Team

**Comment by jensheerin** [comment]
In progress - https://github.com/Azure/terraform-azurerm-avm-res-desktopvirtualization-hostpools/

**Comment by jensheerin** [comment]
@matebarabas, Matt approved my PR.  Published https://registry.terraform.io/modules/Azure/avm-res-desktopvirtualization-hostpools

**Comment by matebarabas** [comment]
@jensheerin, this is great news, congrats to your first module! :)

Before moving on with closing this issue and marking the module fully available, can you please make sure that you have both the "owners" and "contributors" teams created and associated with the repo, with the right level of permissions assigned (as described[here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#grant-permissions---terraform). Thanks! 

#RR

**Comment by jensheerin** [comment]
Thank you @matebarabas! both owners and contributors teams have been created and assigned permissions.

**Comment by matebarabas** [comment]
@PmeshramPM, can you please help take the next steps to close this issue? Thanks!

**Comment by jensheerin** [comment]
For reference: CELA compliant https://ossmsft.visualstudio.com/Reviews/_workitems/edit/48583 Thanks!

**Comment by matebarabas** [comment]
@jensheerin, I just noticed that the name under which this module has been published is slightly off. **You need to use the singular form (the way it's noted in the title and description of this issue)**. 

Can you please:
- change the name of the GH repo (please note that GH will automatically redirect any requests that will use the old name to the new name)
- change the published name of the module

Thank you!

CC: @PmeshramPM

**Comment by jensheerin** [comment]
@matebarabas, changes completed. Thank you!

**Comment by matebarabas** [comment]
This module has been published, and is available here: 
- repo: https://github.com/Azure/terraform-azurerm-avm-res-desktopvirtualization-hostpool
- registry: https://registry.terraform.io/modules/Azure/avm-res-desktopvirtualization-hostpool/azurerm/latest
