### ISSUE TITLE
[Module Proposal]: `avm-res-site-manager`

### ISSUE THREAD

**Issue by xhy8759** [Azure/Azure-Verified-Modules#1204]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-site-manager

### Module Details

It helps create resource site manager in Azure Arc which can be found in aka.ms/sitemanager.

### Do you want to be the owner of this module?

Yes

**Comment by xhy8759** [comment]
https://github.com/Azure/terraform-azapi-avm-res-site-manager/pull/5

**Comment by mbilalamjad** [comment]
> I would like to request a review of my module. The latest code is in a PR titled AVM-Review-PR on the module repo and all checks on that PR are passing.

Thank you Hangyu, before we start review could you please look into the failing e2e test on the PR

**Comment by xhy8759** [comment]
![image](https://github.com/user-attachments/assets/587b9832-32c9-4fa2-b5a3-7e6d0aac0874)
hi @mbilalamjad we run e2e test locally and it passed.

**Comment by mbilalamjad** [comment]
@xhy8759 just had a conversation with @xwen11 and a few observations

1. This module proposal hasn't gone through the module triage process for approval and assignment.
2. The module name doesn't align with the proper resource provider and resource type.
3. Also, this module proposal says that it's a resource module as it has `res` in the name here but the repo has `ptn` in its name

Given the above reason, we'll close this module proposal and instead keep the original [module proposal](https://github.com/Azure/Azure-Verified-Modules/issues/906)
