### ISSUE TITLE
[Module Proposal]: `terraform-azapi-avm-res-hci`

### ISSUE THREAD

**Issue by xhy8759** [Azure/Azure-Verified-Modules#1205]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

hci

### Module Details

Document: https://azure.microsoft.com/en-us/products/azure-stack/hci

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

xhy8759

### (Optional) Secondary Module Owner's GitHub Username (handle)

duzitong

**Comment by prjelesi** [comment]
@xhy8759 is this related with https://github.com/Azure/Azure-Verified-Modules/issues/907

**Comment by prjelesi** [comment]
closing as not needed
