### ISSUE TITLE
[Module Proposal]: `avm/ptn/azd/insights-dashboard`

### ISSUE THREAD

**Issue by Menghua1** [Azure/Azure-Verified-Modules#1206]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes.

### Bicep or Terraform?

Bicep

### Module Classification?

Pattern Module

### Module Name

avm/ptn/azd/insights-dashboard

### Module Details

Please add a Pattern Module named `avm/ptn/azd/insights-dashboard`, this module will create the following two resources:

1. `Application Insights instance` based on an existing Log Analytics workspace.
2. `Portal Dashboard` for an Application Insights instance.

For details, please refer to azd: 
https://github.com/Azure/azure-dev/blob/main/templates/common/infra/bicep/core/monitor/applicationinsights.bicep

https://github.com/Azure/azure-dev/blob/main/templates/common/infra/bicep/core/monitor/applicationinsights-dashboard.bicep

CC: @jongio

### Do you want to be the owner of this module?

No

### Module Owner's GitHub Username (handle)

jongio

**Comment by ChrisSidebotham** [comment]
@jongio - Would a suitable owner for this module be identified from your team or do we need to look elsewhere?

**Comment by Menghua1** [comment]
@jongio I've updated Module Details in the Description.

**Comment by jongio** [comment]
@ChrisSidebotham - I can signup to be the owner of this and all azd related pattern modules.  What's the best way to do that?

**Comment by matebarabas** [comment]
Hi @jongio, @jeanchg and I will reach out to you internally once you're back next week to clarify the context and some of our questions on this and all the other related pattern module proposals @Menghua1 has recently submitted.

**Comment by jongio** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by matebarabas** [comment]
Hi @jongio,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by Menghua1** [comment]
@AlexanderSehr I would like to ask if you know how long it will take for the current module `br/public:avm/ptn/azd/insights-dashboard:<version>` to be released?

**Comment by AlexanderSehr** [comment]
> @AlexanderSehr I would like to ask if you know how long it will take for the current module `br/public:avm/ptn/azd/insights-dashboard:<version>` to be released?

I'd argue it is 😉  
![image](https://github.com/user-attachments/assets/1c9d51b1-06e9-4c4a-ac0d-11c167ea844f)

In case it's not showing up for you yet, rest assured it's just a caching issue which will fix itself. You can already reference the module regardless :)

**Comment by matebarabas** [comment]
- [x] Module published.
- [x] GitHub teams are available and assigned to their parents.
- [x] `CODEOWNERS` file updated.
- [x] Issue template file updated.
 
Thank you for your work @Menghua1!
