### ISSUE TITLE
[Module Proposal]: `avm-res-operationalinsights-workspace` (tf)

### ISSUE THREAD

**Issue by cshea-msft** [Azure/Azure-Verified-Modules#121]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals

### Check this module doesn't already exist in another project that is being evolved into AVM

- [X] I have checked for that this module doesn't already exist in CARML or TFVM

### Terraform or Bicep?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-operationalinsights-workspace

### Module Details

Creating a module for log analytics to be used by other modules for data ingestion. 

code is currently here https://github.com/Azure/avdaccelerator/blob/main/workload/terraform/modules/insights/law.tf

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username

cshea-msft , jensheerin

**Comment by matt-FFFFFF** [comment]
We have this already - we plan to re-work it into a pattern module called 

https://registry.terraform.io/modules/Azure/alz-management/azurerm/latest

Do we need a LA dedicated resource module or can we build on the above?

**Comment by jtracey93** [comment]
I think there also needs to be a separate resource module for a LAW in TF as the `alz-management` module is a pattern module as it does LAW + Automation Accounts

Picky I know, but we should follow what we set out 👍

**Comment by cshea15** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by cshea-msft** [comment]
is there any update on this?

**Comment by jtracey93** [comment]
@prjelesi @matebarabas @PmeshramPM please can you reply to @cshea-msft here 👍

**Comment by cshea-msft** [comment]
@prjelesi you are correct, i will own the module.

**Comment by prjelesi** [comment]
@cshea-msft github user is also updated. we will update on AVM index page also.

**Comment by PmeshramPM** [comment]
@cshea-msft - Just changed the name of the module proposal to  ->  avm-res-operationalinsights-workspace (tf)

**Comment by cshea-msft** [comment]
PR ready for review https://github.com/Azure/terraform-azurerm-avm-res-operationalinsights-workspace/pull/1

**Comment by jensheerin** [comment]
PR ready for review https://github.com/Azure/terraform-azurerm-avm-res-operationalinsights-workspace/pull/3

**Comment by mbilalamjad** [comment]
Hey @cshea-msft, @jensheerin have approved the PR, there's also a governance PR from the AVM team which I've approved, you could merge both and go ahead with publishing module into the registry.
