### ISSUE TITLE
[Module Proposal]: `avm/res/dev-ops-infrastructure/pool`

### ISSUE THREAD

**Issue by johnlokerse** [Azure/Azure-Verified-Modules#1217]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes.

### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/dev-ops-infrastructure/pool

### Module Details

This module deploys the new Managed DevOps Pools resource.

### Do you want to be the owner of this module?

No

### Module Owner's GitHub Username (handle)

@elizatargithub7,
@surajguptha

**Comment by johnlokerse** [comment]
I have approval from @surajguptha to create this AVM resource module request.

I have created the Bicep template for managed-devops-pools including a setup of tests for `default`, `max` and `waf-aligned`. Waf-aligned is not finished yet. Before I go through testing I would like to open a PR to see if the Bicep template meets AVM code conventions/rules/etc... 

**Challenge**
A challenge I am facing, which perhaps @AlexanderSehr can assist with, is that the tests depend on an Azure DevOps or GitHub organisation. Currently, I am using my own ADO organisation to deploy the pool for testing, but this needs to change for the AVM tests.

When using ADO, the managed identity or service connection used for deploying MDP requires `Project Collection Admin` permissions to manage the pool. This means ADO needs a connection to an Entra ID as well. A possible solution could be to connect the Entra ID from the tenant where the tests are deployed to an Azure DevOps organisation dedicated to this module. Project Collection Admin is a highly privileged role in Azure DevOps, so having an isolated environment is in my opinion the best option.

**Comment by jtracey93** [comment]
Just adding for context this is a new resource to Azure that @johnlokerse is working with the PG (@surajguptha) to create AVM modules so they are ready in time for release.

https://devblogs.microsoft.com/engineering-at-microsoft/managed-devops-pools-the-origin-story/

**Comment by AlexanderSehr** [comment]
Hey @johnlokerse & @jtracey93,
let's align on this one. Some time ago I created this pattern proposal: https://github.com/Azure/Azure-Verified-Modules/issues/1191 to start migrating some of the IP I have in my [DevOps-Self-Hosted](https://github.com/Azure/DevOps-Self-Hosted) respository into AVM. The image builder is the first building block, the ScaleSet deployment would be the 2nd (for which I did not create a proposal yet). If possible it would be great to have a chat some time @johnlokerse regarding what exactly you plan to do, and how we can ideally align :)

**Comment by johnlokerse** [comment]
I will send you a message @AlexanderSehr 😃

**Comment by johnlokerse** [comment]
Had a chat yesterday with @AlexanderSehr. This resource will be a good fit for AVM. The only thing we need to think about is testing since the resource needs an Azure DevOps (or GitHub) environment to create the agent pools. I think it is good to open a pull request for the Bicep template as early as possible for early feedback.

**Comment by johnlokerse** [comment]
I have created the pull request for code review. The PR will not be merged until this proposal is approved. :-)

**Comment by AlexanderSehr** [comment]
> I have created the pull request for code review. The PR will not be merged until this proposal is approved. 😄

Reviewed it is

**Comment by matebarabas** [comment]
Hi @johnlokerse, thank you so much for proposing this module, and thank you for your patience on triaging it! Many of us on the AVM core team have been OOF in the last couple of weeks, but we're back now! 😊

Looking into the attached PR, I'd have the following question/ask: As the key RP/RT pair for this module is `Microsoft.DevOpsInfrastructure/pools`, this module's name should be `avm/res/dev-ops-infrastructure/pools`. **Could you please update the proposal and change the module's name in all occurrences in the related PR (folder name, etc.)?**

Based on our internal discussion, I'll also initiate the handshake with @elizatargithub7 on the ownership. CC: @surajguptha

**Comment by matebarabas** [comment]
Hi @elizatargithub7,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by elizatargithub7** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by elizatargithub7** [comment]
> Hi @elizatargithub7,
> 
> Thanks for requesting/proposing to be an AVM module owner!
> 
> We just want to confirm **you agree to the below pages** that define what module ownership means:
> 
> * [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
> * [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
> * [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)
> 
> Any questions or clarifications needed, let us know!
> 
> If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):
> 
> "I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"
> 
> Thanks,
> 
> The AVM Core Team
> 
> #RR

I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by jaredfholgate** [comment]
Hi. I can probably help with the GitHub / Azure DevOps testing dependency for this. I will also propose the Terraform version of this module. @elizatargithub7 and @johnlokerse feel free to ping me for help with the VCS part of you don’t already have a solution.

**Comment by matebarabas** [comment]
Official public preview announcement from the PG: https://aka.ms/hellomdp

**Comment by matebarabas** [comment]
PR: https://github.com/Azure/bicep-registry-modules/pull/2894
