### ISSUE TITLE
[Module Proposal]: `avm/ptn/sql/server-deployment-script`

### ISSUE THREAD

**Issue by Menghua1** [Azure/Azure-Verified-Modules#1223]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes.

### Bicep or Terraform?

Bicep

### Module Classification?

Pattern Module

### Module Name

avm/ptn/sql/server-deployment-script

### Module Details

Please add a Pattern Module named `avm/ptn/sql/server-deployment-script`, this module will create the following two resources:

1. Azure SQL Server instance.
2. Deployment Scripts.

For details, please refer to azd: 
https://github.com/Azure/azure-dev/blob/main/templates/common/infra/bicep/core/database/sqlserver/sqlserver.bicep

CC: @jongio

### Do you want to be the owner of this module?

No

**Comment by matebarabas** [comment]
@Menghua1, thank you for proposing this module and thank you for your patience on triaging it! Many of us on the AVM core team have been OOF in the last couple of weeks, but we're back now! 😊

As this is categorized as a pattern module, its approval will require a more thorough assessment. We'll reach out to @jongio internally for more context and details as this proposal may require some adjustments to fit AVM's [pattern definition](https://azure.github.io/Azure-Verified-Modules/specs/shared/module-classifications/) and intent. The AVM core team will get back to you soon. Thank you for your patience!
