### ISSUE TITLE
[Question/Feedback]: Managed Identities

### ISSUE THREAD

**Issue by jchancellor-ms** [Azure/Azure-Verified-Modules#123]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

We should provide additional clarity on the following scenarios related to managed identities:

1. Is it acceptable for a resource to enable the system managed identity by default if it is required for use within the resource.
2. For user assigned managed identities explicitly set the expectation for resource modules that any identities will be created outside of the module. (Makes little sense to create a resource within the resource context that is expected to be used across resources)
3. For user-assigned managed identities explicitly state that we won't be assigning RBAC to them either.  (assumed the role assignments will take place when the user identity is created. (see item 2)

**Comment by matt-FFFFFF** [comment]
Hi @jchancellor-ms 

For 1. What scenario were you thinking of? In a resource module I think no but a pattern module may absolutely require this.

Re 2. Agreed. UMIs should be passed by reference

And 3. Again would love to hear the scenario. Typically the role assignment would be on a different resource to that which it was assigned.

**Comment by jtracey93** [comment]
Jon is OOF this week

**Comment by mbilalamjad** [comment]
> Hi @jchancellor-ms Jon Chancellor FTE
> 
> For 1. What scenario were you thinking of? In a resource module I think no but a pattern module may absolutely require this.
> 
> Re 2. Agreed. UMIs should be passed by reference
> 
> And 3. Again would love to hear the scenario. Typically the role assignment would be on a different resource to that which it was assigned.

@jchancellor-ms just following up, appreciate your response on @matt-FFFFFF comments above

**Comment by jchancellor-ms** [comment]
Opted to have two separate RBAC variables.  One matching the spec interface and one with to provision RBAC on the managed identity.  This can be closed.
