### ISSUE TITLE
[Module Proposal]: `avm/ptn/azd/web-container-app`

### ISSUE THREAD

**Issue by Menghua1** [Azure/Azure-Verified-Modules#1231]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes.

### Bicep or Terraform?

Bicep

### Module Classification?

Pattern Module

### Module Name

avm/ptn/azd/web-container-app

### Module Details

Please add a Pattern Module named `avm/ptn/app/web-container-app`, this module will create the following three resources:

1. Container App.
2. User Assigned Identity.
3. Azure Container Registry (ACR).

For details, please refer to azd: 
https://github.com/Azure/azure-dev/blob/main/templates/todo/common/infra/bicep/app/web-container-app.bicep

CC: @jongio

### Do you want to be the owner of this module?

No

### Module Owner's GitHub Username (handle)

jongio

**Comment by prbeegala** [comment]
I'm working with Container Apps, and happy to own this module.

**Comment by matebarabas** [comment]
@Menghua1, thank you for proposing this module and thank you for your patience on triaging it! Many of us on the AVM core team have been OOF in the last couple of weeks, but we're back now! 😊

As this is categorized as a pattern module, its approval will require a more thorough assessment. We'll reach out to @jongio internally for more context and details as this proposal may require some adjustments to fit AVM's [pattern definition](https://azure.github.io/Azure-Verified-Modules/specs/shared/module-classifications/) and intent. The AVM core team will get back to you soon. Thank you for your patience!

**Comment by matebarabas** [comment]
> I'm working with Container Apps, and happy to own this module.

Hi @prbeegala, thanks for volunteering to help! Please note that this module along with some other related ones have been proposed by the AZD PG team and they may want to work on these too. Also note that the "ingredients" of this proposed pattern module already exist. Should this pattern module be approved, the work here would most likely be focused on stitching these together.

**Comment by matebarabas** [comment]
Hi @jongio,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR
