### ISSUE TITLE
[Module Proposal]: `avm-res-azurestackhci-logicalNetwork`

### ISSUE THREAD

**Issue by xhy8759** [Azure/Azure-Verified-Modules#1256]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-azurestackhci-logicalNetwork

### Module Details

Terraform azapi module to create AzureStackHCI logical network.
https://learn.microsoft.com/en-us/azure-stack/hci/manage/create-logical-networks?tabs=azurecli

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

xhy8759

### (Optional) Secondary Module Owner's GitHub Username (handle)

duzitong

**Comment by prjelesi** [comment]
Hi 

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by prjelesi** [comment]
@prjelesi  to check azapi

**Comment by xhy8759** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by prjelesi** [comment]
@prjelesi to check can we have azapi in repo name

**Comment by prjelesi** [comment]
@xhy8759  azurerm as we agreed

**Comment by xhy8759** [comment]
I would like to request a review of my module. The latest code is in a PR titled AVM-Review-PR on the module repo and all checks on that PR are passing.
Here isour PR link:
https://github.com/Azure/terraform-azurerm-avm-res-azurestackhci-logicalnetwork/pull/1

Test passes locally:
![logicalnetwork](https://github.com/user-attachments/assets/25a27371-14c4-4b67-847e-94a2b512aab9)
