### ISSUE TITLE
[Module Proposal]: `avm-res-devopsinfrastructure-pool`

### ISSUE THREAD

**Issue by jaredfholgate** [Azure/Azure-Verified-Modules#1265]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-devopsinfrastructure-pool

### Module Details

This is a resource module for Managed DevOps Pools. It is currently in public preview, but will be a great solution to have available ASAP.

API ref: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/devopsinfrastructure/resource-manager/Microsoft.DevOpsInfrastructure/preview/2024-04-04-preview/devopsinfrastructure.json

ARM example: https://learn.microsoft.com/en-us/azure/devops/managed-devops-pools/quickstart-arm-template?view=azure-devops

This will be leveraged in the avm-ptn-cicd-agents-and-runners pattern module.

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

jaredfholgate

**Comment by jaredfholgate** [comment]
Cross referencing the issue for the Bicep version: https://github.com/Azure/Azure-Verified-Modules/issues/1217

**Comment by johnlokerse** [comment]
Mentioning @haflidif, who is already working on a Terraform MDP solution.

**Comment by haflidif** [comment]
@jaredfholgate happy to collaborate with you on this 💯

**Comment by jaredfholgate** [comment]
> @jaredfholgate happy to collaborate with you on this 💯

Hello again @haflidif. :) Sure, I have a meeting about it on Monday and will get in touch. If you have a repo for it already, please feel free to share.

**Comment by haflidif** [comment]
> > @jaredfholgate happy to collaborate with you on this 💯
> 
> Hello again @haflidif. :) Sure, I have a meeting about it on Monday and will get in touch. If you have a repo for it already, please feel free to share.

I'll just wrap few commits and do a little clean up in the repo, I'll share as soon as possible

**Comment by haflidif** [comment]
@jaredfholgate what do you think about the naming of the module, when I spoke to the PMs when I gave my repo a name, they liked the `avm-res-devopsinfrastructure-managed-devops-pools` - but maybe `avm-res-devopsinfrastructure-managed-pools` is more convenient ?

**Comment by haflidif** [comment]
> @jaredfholgate what do you think about the naming of the module, when I spoke to the PMs when I gave my repo a name, they liked the `avm-res-devopsinfrastructure-managed-devops-pools` - but maybe `avm-res-devopsinfrastructure-managed-pools` is more convenient ?

nvm saw a request to have the Bicep module named the same way you did, so I will change the name of my repo to reflect the naming in the proposal 😎

**Comment by jaredfholgate** [comment]
> > @jaredfholgate what do you think about the naming of the module, when I spoke to the PMs when I gave my repo a name, they liked the `avm-res-devopsinfrastructure-managed-devops-pools` - but maybe `avm-res-devopsinfrastructure-managed-pools` is more convenient ?
> 
> nvm saw a request to have the Bicep module named the same way you did, so I will change the name of my repo to reflect the naming in the proposal 😎

Yeah, we are supposed to follow the api naming for these modules and I think this is right, but the PM can confirm and I can rename the repo if needed.

**Comment by haflidif** [comment]
@jaredfholgate Still work in progress, but here is what I have so far: https://github.com/haflidif/terraform-azurerm-avm-res-devopsinfrastructure-pools  

I've done some unit-tests on it and it seems to go through and deploy what I want - I will include the unit-test later today

**Comment by johnlokerse** [comment]
Hey @haflidif @jaredfholgate! Since we have to run the AVM Bicep/Terraform modules through automated tests I wonder what the best way is to have a connection to Azure DevOps. At some point in the deployment the user (in this case a SPN) that orchestrates the deployment needs to deploy an agent pool in an existing Azure DevOps organisation.

What are your views on this? Or is the approach different for Terraform?

cc @AlexanderSehr

**Comment by jaredfholgate** [comment]
> Hey @haflidif @jaredfholgate! Since we have to run the AVM Bicep/Terraform modules through automated tests I wonder what the best way is to have a connection to Azure DevOps. At some point in the deployment the user (in this case a SPN) that orchestrates the deployment needs to deploy an agent pool in an existing Azure DevOps organisation.
> 
> What are your views on this? Or is the approach different for Terraform?
> 
> cc @AlexanderSehr

Terraform is already sorted as I had to implement a solution last week for Azure DevOps and GitHub. Basically, if you supply any GitHub variables or secrets that start with `TF_VAR_`, it will add them to the container environment, so you can declare variables in the examples (e2e tests) and supply them by this means.

For local testing use a tfvars file for e2e tests we have orgs that can be used and the owner can set the variables in the repo or environment.

For Bicep, I am unsure but could potentially follow a similar approach.

**Comment by jaredfholgate** [comment]
> > Hey @haflidif @jaredfholgate! Since we have to run the AVM Bicep/Terraform modules through automated tests I wonder what the best way is to have a connection to Azure DevOps. At some point in the deployment the user (in this case a SPN) that orchestrates the deployment needs to deploy an agent pool in an existing Azure DevOps organisation.
> > What are your views on this? Or is the approach different for Terraform?
> > cc @AlexanderSehr
> 
> Terraform is already sorted as I had to implement a solution last week for Azure DevOps and GitHub. Basically, if you supply any GitHub variables or secrets that start with `TF_VAR_`, it will add them to the container environment, so you can declare variables in the examples (e2e tests) and supply them by this means.
> 
> For local testing use a tfvars file. For e2e tests we have orgs that can be used and the owner can set the variables in the repo or environment.
> 
> For Bicep, I am unsure but could potentially follow a similar approach.

Having said that, I now see that it can't use a PAT and requires a principal of some kind to register the pool in Azure DevOps. I'll have to figure that part out... Can possible grant the MSI perms during the test run I think.

**Comment by matebarabas** [comment]
@jaredfholgate, I've changed the module's name in this proposal to its singular form (`pools` --> `pool`), since as per the [naming convention](https://azure.github.io/Azure-Verified-Modules/specs/shared/#terraform-resource-module-naming) for resource modules, the RT segment of the name must be in singular form. 

@prjelesi, please make sure the singular form is captured when this proposal is triaged. Thanks!

**Comment by matebarabas** [comment]
Official public preview announcement from the PG: https://aka.ms/hellomdp

**Comment by AlexanderSehr** [comment]
> > Hey @haflidif @jaredfholgate! Since we have to run the AVM Bicep/Terraform modules through automated tests I wonder what the best way is to have a connection to Azure DevOps. At some point in the deployment the user (in this case a SPN) that orchestrates the deployment needs to deploy an agent pool in an existing Azure DevOps organisation.
> > What are your views on this? Or is the approach different for Terraform?
> > cc @AlexanderSehr
> 
> Terraform is already sorted as I had to implement a solution last week for Azure DevOps and GitHub. Basically, if you supply any GitHub variables or secrets that start with `TF_VAR_`, it will add them to the container environment, so you can declare variables in the examples (e2e tests) and supply them by this means.
> 
> For local testing use a tfvars file. For e2e tests we have orgs that can be used and the owner can set the variables in the repo or environment.
> 
> For Bicep, I am unsure but could potentially follow a similar approach.

In Bicep we'll need to do something similar. As already discussed in a different location, we'll have to enable the BRM (ABM-Bicep) CI to dynamically pull secerets and pass them into templates. It should not be too complicated to implement, but needs to be aligned with the other Bicep maintainers. I hope we can get to discuss it tomorrow.

**Comment by matebarabas** [comment]
> @matebarabas and @prjelesi This module has now been released here if you want to close this issue and update the index? It is here: https://registry.terraform.io/modules/Azure/avm-res-devopsinfrastructure-pool

As @PmeshramPM is managing TF module proposals at this stage, I'd like to ask him to follow up on the conclusion of this development. Thanks!

**Comment by prjelesi** [comment]
@jaredfholgate i supose that you agree to be owner of this module and to follow all roles and responsibilities as module owner?

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

**Comment by jaredfholgate** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by prjelesi** [comment]
Hi @jaredfholgate 

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

Before starting development, please ensure ALL the following requirements are met.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - for naming your module
  - `TelemetryIdPrefix` - for your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repo name and folder path are defined in `RepoURL`
  - Create GitHub teams for module owners and contributors and grant them permissions as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
  - Grant permissions for the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

Check if this module exists in the other IaC language. If so, collaborate with the other owner for consistency. 👍

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published! Please include a link pointing to your PR, once available. 🙏**

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team
