### ISSUE TITLE
[Orphaned Module]: `avm/res/network/front-door`

### ISSUE THREAD

**Issue by matebarabas** [Azure/Azure-Verified-Modules#1269]
### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/network/front-door

### Module Details

This module was previously owned by @rozkurt. 

**Note**: when someone volunteers to be the owner of this module, please reach out to @rozkurtto for changing the ownership of the existing GitHub teams.

- Module proposal: https://github.com/Azure/Azure-Verified-Modules/issues/490
- PR: https://github.com/Azure/bicep-registry-modules/pull/769

### Do you want to be the new owner of this module?

No

### Module Owner's GitHub Username (handle)

hundredacres

**Comment by hundredacres** [comment]
@matebarabas I can become an owner of this module.

**Comment by matebarabas** [comment]
Hi @hundredacres,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by hundredacres** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by matebarabas** [comment]
Hi @hundredacres,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

We just want to ask you to double check a few important things.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- You must be the owner of the GitHub teams as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
- Please check that your name has been updated in the module index page (this should happen shortly after you confirmed ownership).

You can now take ownership of this module and start improving it as needed! ✅ Happy coding! 🎉

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by matebarabas** [comment]
@rozkurt, can you please hand over the 2 GH teams to @hundredacres (add him as a member AND make him a maintainer) and let us know when this step is done. Thank you!
- https://github.com/orgs/Azure/teams/avm-res-network-frontdoor-module-contributors-bicep
- https://github.com/orgs/Azure/teams/avm-res-network-frontdoor-module-owners-bicep

@hundredacres, can you please also remove the `ORPHANED.md` file from the [module's folder](https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/network/front-door) and its content from the README.md, by following the steps described in point 5 [here](https://azure.github.io/Azure-Verified-Modules/help-support/issue-triage/avm-issue-triage/#when-a-new-owner-is-identified) and let me know in a comment when this is done. Thanks!

**Comment by hundredacres** [comment]
@matebarabas PR to remove ORPHANED file: https://github.com/Azure/bicep-registry-modules/pull/3320

**Comment by rozkurt** [comment]
@matebarabas I confirm that I added @hundredacres and made him maintainer on 2 GH teams that you referred!

**Comment by matebarabas** [comment]
- [x] Module published.
- [x] New owner has been added to the GitHub teams as maintainer.
- [x] `ORPHANED` file deleted, `README` file updated.
 
Thank you for taking over, @hundredacres! I'm closing this issue now.
