### ISSUE TITLE
[Module Proposal]: `avm-ptn-azurestackhci-galleryimage`

### ISSUE THREAD

**Issue by xhy8759** [Azure/Azure-Verified-Modules#1289]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-ptn-azurestackhci-galleryimage

### Module Details

Provision for AzureStackHCI gallery image.
Provider is Microsoft.AzureStackHCI/marketplaceGalleryImages@2023-09-01-preview

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

xhy8759

### (Optional) Secondary Module Owner's GitHub Username (handle)

duzitong

**Comment by prjelesi** [comment]
Not needed
