### ISSUE TITLE
[Module Proposal]: `avm-res-aiservices-account`

### ISSUE THREAD

**Issue by cmaclaughlin** [Azure/Azure-Verified-Modules#1355]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-aiservices-account

### Module Details

Although technically a kind of Cognitive Services account, [Azure AI Services](https://learn.microsoft.com/en-us/azure/ai-services/what-are-ai-services) were added as their own [unique resource with v3.116 of the Azure resource provider](https://registry.terraform.io/providers/hashicorp/azurerm/3.116.0/docs/resources/ai_services). There is a need for AI Services - required for AI Studio and optional (but desired) for AML.

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

cmaclaughlin

### (Optional) Secondary Module Owner's GitHub Username (handle)

Nepomuceno

**Comment by prjelesi** [comment]
Hi @cmaclaughlin 
let's chat offline.

**Comment by cmaclaughlin** [comment]
Closing. Will open an issue against the Cognitive Services Account AVM module to support this `kind`.
