### ISSUE TITLE
[Module Proposal]: `avm-res-postgres-flexibleserver`

### ISSUE THREAD

**Issue by cmaclaughlin** [Azure/Azure-Verified-Modules#1356]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-postgres-flexibleserver

### Module Details

A module for deploying an Azure Database for PostgreSQL flexible server

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

ritesh-modi

### (Optional) Secondary Module Owner's GitHub Username (handle)

cmaclaughlin

**Comment by prjelesi** [comment]
Hi @cmaclaughlin 

i would say that this is duplicated request with this

https://github.com/Azure/Azure-Verified-Modules/issues/273

and I propose that we check how Tim is progressing and maybe you can jump in to help? 

Let me know what you think.
