### ISSUE TITLE
AVM External Community Call - 24th September 2024

### ISSUE THREAD

**Issue by jeanchg** [Azure/Azure-Verified-Modules#1387]
The Azure Verified Modules team will host our next quarterly Community Call on September 24th, at 18:00 CET, showcasing all of the great work the community and the team have done, alongside important updates, guest speakers and a community Q&A.
To sign up for this next occurrence, please use: [Teams Webinar link](https://msit.events.teams.microsoft.com/event/74fc1d31-fc02-411d-bb3c-a4969833d178@72f988bf-86f1-41af-91ab-2d7cd011db47)
Please leave comments below on topics you'd like covered.

**Comment by michal-chmel** [comment]
Is there going to be a recording available?

**Comment by jeanchg** [comment]
> Is there going to be a recording available?
@michal-chmel Yes, absolutely, every meeting is recorded and later published on our YouTube channel.

**Comment by matebarabas** [comment]
[Event summary](https://azure.github.io/Azure-Verified-Modules/resources/community/#24th-september-2024)
