### ISSUE TITLE
[Module Proposal]: `avm/ptn/authorization/management-group-policy-exemption`

### ISSUE THREAD

**Issue by oZakari** [Azure/Azure-Verified-Modules#1405]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes.

### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/ptn/authorization/management-group-policy-exemption

### Module Details

Policy exemptions module

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

oZakari

**Comment by matebarabas** [comment]
@oZakari, thank you for proposing this module! As this is categorized as a pattern module, its approval will require a more thorough assessment. The AVM core team will get back to you soon. Thank you for your patience!

In the meantime, can you please provide more details about this module? What would be included in this module: would this be a generic one for any exceptions or something specific? Would the implementation be of variable scope, or would it have 3 separate implementations (the differentiate between rg/sub/mg level scoping), the same way we're doing this for role assignments ([rg](https://github.com/Azure/Azure-Verified-Modules/issues/1322)/[sub](https://github.com/Azure/Azure-Verified-Modules/issues/1323)/[mg](https://github.com/Azure/Azure-Verified-Modules/issues/1324))? Thanks!

**Comment by oZakari** [comment]
@matebarabas This will be a generic policy exemptions module. It will have 3 separate modules per each scope as the role assignments and generic policy assignments modules were built.

**Comment by matebarabas** [comment]
@oZakari, it makes sense; thanks for clarifying! In this case, can you please file 3 separate module proposals (rename and keep this one and create 2 more). Please follow the naming logic of the 3 scoped solution that I referenced above. Thank you!

**Comment by matebarabas** [comment]
Hi @oZakari,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by oZakari** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by matebarabas** [comment]
Hi @oZakari,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

Before starting development, please ensure ALL the following requirements are met.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - for naming your module
  - `TelemetryIdPrefix` - for your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repo name and folder path are defined in `RepoURL`
  - Create GitHub teams for module owners and contributors and grant them permissions as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
  - Grant permissions for the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

Check if this module exists in the other IaC language. If so, collaborate with the other owner for consistency. 👍

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published! Please include a link pointing to your PR, once available. 🙏**

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team
