### ISSUE TITLE
[Module Proposal]: `avm/ptn/azd/aks-automatic-cluster`

### ISSUE THREAD

**Issue by zedy-wj** [Azure/Azure-Verified-Modules#1426]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes.

### Bicep or Terraform?

Bicep

### Module Classification?

Pattern Module

### Module Name

avm/ptn/azd/aks-automatic-cluster

### Module Details

Please add a Pattern Module named `avm/ptn/azd/aks-automatic-cluster`, this module will create the following three resources:

1. Azure Kubernetes Service (AKS) Automatic Cluster.
2. Azure Container Registry (ACR).
3. Key Vault.

For details, please refer to the related PR:
https://github.com/Azure/azure-dev/pull/4069

CC: @jongio, @wbreza 

### Do you want to be the owner of this module?

No

**Comment by matebarabas** [comment]
@zedy-wj, thanks for this proposal! Just a quick clarifying question: has this been on the list that was circulated internally previously, or is this a newly identified requirement? Thanks!

**Comment by zedy-wj** [comment]
> @zedy-wj, thanks for this proposal! Just 2 quick clarifying questions:
> 
> * has this been on the list that was circulated internally previously, or is this a newly identified requirement?
> * Would @jongio be the owner of this one too?
> 
> Thanks!

Hey @matebarabas,
1. This is a newly identified requirement.
2. We will confirm the owner ASAP.

**Comment by jongio** [comment]
Yes, make me the owner of this and any future azd ptn modules.  thx

**Comment by matebarabas** [comment]
Hi @jongio,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by jongio** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by matebarabas** [comment]
Hi @jongio,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

Before starting development, please ensure ALL the following requirements are met.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - for naming your module
  - `TelemetryIdPrefix` - for your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repo name and folder path are defined in `RepoURL`
  - Create GitHub teams for module owners and contributors and grant them permissions as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
  - Grant permissions for the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

Check if this module exists in the other IaC language. If so, collaborate with the other owner for consistency. 👍

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published! Please include a link pointing to your PR, once available. 🙏**

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by zedy-wj** [comment]
@matebarabas - I haven't found the relevant content of this `ptn module proposal` in this [file](https://github.com/Azure/Azure-Verified-Modules/blob/main/docs/static/module-indexes/BicepPatternModules.csv). Do we need some additional steps to get approval?

> * For your module's repository:
>   
>   * Repo name and folder path are defined in `RepoURL`
>   * Create GitHub teams for module owners and contributors and grant them permissions as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
>   * Grant permissions for the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

@jongio - `Create GitHub teams for module owners and contributors and grant them permission.` Since we do not have permission to complete these operations, they need to be processed by the Owner.

I'm not sure if there is a sequence problem when dealing with the above two prerequisites, but I think they should both be completed before PR review (due to the static validation of the pipeline). At the same time, we have started preparing PR.

**Comment by matebarabas** [comment]
@zedy-wj, the index will be updated with this information soon. I'll let you know when it happened. Thanks for your patience!

**Comment by v-xuto** [comment]
@jongio Could you help create GitHub teams or find someone to assist with the creation?

**Comment by matebarabas** [comment]
@v-xuto, I agreed with Jon that I'll assist with this one as the index update is pending on me.

**Comment by v-xuto** [comment]
> [@v-xuto](https://github.com/v-xuto), I agreed with Jon that I'll assist with this one as the index update is pending on me.

OKay, thanks for your assistance.

**Comment by matebarabas** [comment]
@zedy-wj, @v-xuto, @jongio, here are some updates from my end:

- [x] Module index updated (telemetry ID prefix available)
- [x] GH teams created:
  - https://github.com/orgs/Azure/teams/avm-ptn-lzashared-dataservices-module-contributors-bicep
  - https://github.com/orgs/Azure/teams/avm-ptn-lzashared-dataservices-module-owners-bicep
- [x] Submit a PR to update the MAR manifest file with the new name
- [ ] MAR manifest PR merge confirmed --> this needs to get confirmed before the module can be first published (typically takes a couple of days)

**Comment by matebarabas** [comment]
@zedy-wj, @v-xuto, @jongio, all requirements listed above are now complete.

**Comment by matebarabas** [comment]
- [x] Module published.
- [x] GitHub teams are available and assigned to their parents.
- [x] `CODEOWNERS` file updated.
- [x] Issue template file updated.

The module index will be updated to reflect this change.
 
Thank you for your work @zedy-wj, @Menghua1, @NanaXiong00!
