### ISSUE TITLE
[Module Proposal]: `avm-res-network-azurefirewall` (tf)

### ISSUE THREAD

**Issue by cshea-msft** [Azure/Azure-Verified-Modules#152]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals

### Check this module doesn't already exist in another project that is being evolved into AVM

- [X] I have checked for that this module doesn't already exist in CARML or TFVM

### Terraform or Bicep?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-network-firewall

### Module Details

Creating Azure firewall module to deploy in a customer virtual network. 

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username

cshea15

**Comment by cshea15** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by prjelesi** [comment]
@cshea15  Thank you for proposing this one. 

For the Azure Firewall  the armresourcename name is azureFirewalls-

I have edited the issue form to reflect the correct name ( avm-res-network-azureFirewall)

Please see the specification (https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-rmnfr1---category-naming---module-naming)

Let us know if you need any help.

**Comment by JefferyMitchell** [comment]
@cshea-msft Let me know when you are ready for PG review and I will setup, I also have ADO of items to complete for module creation if needed.

**Comment by JefferyMitchell** [comment]
> I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

I will add you to ADO and assign the ADO items.

**Comment by cshea-msft** [comment]
Still working on it, hoping to have it wrapped up soon.

**Comment by cshea-msft** [comment]
PR is ready for review https://github.com/Azure/terraform-azurerm-avm-res-network-firewall/pull/1

**Comment by cshea-msft** [comment]
waiting for PR to be reviewed.

**Comment by cshea-msft** [comment]
PR has been approved and the module has been published to Hashicorp

https://registry.terraform.io/modules/Azure/avm-res-network-firewall/azurerm/latest

**Comment by PmeshramPM** [comment]
updated the correct module name - avm-res-network-azurefirewall
