### ISSUE TITLE
[Module Proposal]: `avm-res-network-firewallpolicy` (tf)

### ISSUE THREAD

**Issue by cshea-msft** [Azure/Azure-Verified-Modules#153]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals

### Check this module doesn't already exist in another project that is being evolved into AVM

- [X] I have checked for that this module doesn't already exist in CARML or TFVM

### Terraform or Bicep?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-network-firewallpolicy

### Module Details

Creating a module for firewall policy that will be used with the azure firewall policy. 

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username

cshea15

**Comment by cshea15** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by prjelesi** [comment]
@cshea15 

i supposes that statement above confirms that you agree to the below pages that define what module ownership means:

https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions
https://azure.github.io/Azure-Verified-Modules/specs/shared
https://azure.github.io/Azure-Verified-Modules/help-support/module-support

Please confirm that i am not wrong about this. 

module name: **avm-res-network-firewallpolicy**
Github repo name: **terraform-azurerm-avm-res-network-firewallpolicy**

i will move this request from "Proposed" to "In Development" 

Please reach out to AVM core team in case that you need any assistance.

**Comment by cshea15** [comment]
You are correct, I was just getting ahead of it thanks @prjelesi

**Comment by cshea-msft** [comment]
pr is ready for review https://github.com/Azure/terraform-azurerm-avm-res-network-firewallpolicy/pull/1

**Comment by cshea-msft** [comment]
waiting for PR to be approved.

**Comment by cshea-msft** [comment]
PR is merged and content has been published. https://registry.terraform.io/modules/Azure/avm-res-network-firewallpolicy/azurerm/latest
