### ISSUE TITLE
[Module Proposal]: `avm/res/document-db/database-account/table`

### ISSUE THREAD

**Issue by seesharprun** [Azure/Azure-Verified-Modules#1545]
### Check for previous/existing GitHub issues/module proposals

- [x] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [x] I have checked for that this module doesn't already exist in the module indexes.

### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/document-db/database-account/table

### Module Details

Azure Cosmos DB for Table now supports Microsoft Entra authentication (https://learn.microsoft.com/azure/cosmos-db/table/security).

As part of this, I'm working on Azure Developer CLI quickstart template using AVM modules and I noticed that I'm unable to create an account for Table as the `capabilities` array requires the account to be either NoSQL, MongoDB, or Apache Gremlin.

I'm planning a pull request to add the ability to create a table within an Azure Cosmos DB account.

I'm going to base it on this implementation: (https://github.com/Azure-Samples/cosmos-db-table-dotnet-quickstart/blob/2069c418a2bd8a9b3565e0456a9037d9582d7ad7/infra/core/database/cosmos-db/table/table.bicep)

And I will add the best practices from your current sub-resource implementations.

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

seesharprun

### (Optional) Secondary Module Owner's GitHub Username (handle)

markjbrown

**Comment by seesharprun** [comment]
I'm working on this in this PR:

- https://github.com/Azure/bicep-registry-modules/pull/3562

**Comment by AlexanderSehr** [comment]
Hey @seesharprun,
I think this proposal can be closed. As of today, we don't need dedicated proposals for child-modules. @matebarabas I'll leave it ultimately up to you 😉

**Comment by bryansan-msft** [comment]
I would re-open an Issue in the module repository instead of closing it completely. It is weird to open a PR without an Issue backing up the PR

**Comment by seesharprun** [comment]
@bryansan-msft, I will reopen this as a proposal in the module repository. I was following a guide I saw to put a proposal here, but I could have misunderstood it.
