### ISSUE TITLE
[Module Proposal]: `avm-res-network-bastionhost` (tf)

### ISSUE THREAD

**Issue by herms14** [Azure/Azure-Verified-Modules#155]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals

### Check this module doesn't already exist in another project that is being evolved into AVM

- [X] I have checked for that this module doesn't already exist in CARML or TFVM

### Terraform or Bicep?

Terraform

### Module Classification?

Resource Module

### Module Name
avm-res-network-bastionhost

Github Repo name - terraform-azurerm-avm-res-network-bastionhost

### Module Details

a terraform module to create a Azure Bastion resource based of CAF best practices patterned on this deprecated module 

https://registry.terraform.io/modules/aztfmod/caf-azure-bastion/azurerm/latest

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username

herms14

**Comment by prjelesi** [comment]
@herms14 Can you provide more details how you plan to use mention deprecated module? AVM resource modules  **MAY** contain references to other resource modules, however **MUST NOT** contain references to non-AVM modules nor AVM pattern modules.

**Comment by herms14** [comment]
@prjelesi I don't plan to reference that deprecated module. What I meant was to revive the module and bring it to avm specifications since it has now been archived.

**Comment by prjelesi** [comment]
Cool! @herms14 

Let's continue with formal part:

Thanks for requesting/proposing to be an AVM module owner.

We just want to confirm you agree to the below pages that define what module ownership means:

https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions
https://azure.github.io/Azure-Verified-Modules/specs/shared
https://azure.github.io/Azure-Verified-Modules/help-support/module-support

Any questions or clarifications needed let us know.

If you agree please just reply to this issue with the exact sentence below (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks

The AVM Core Team

**Comment by prjelesi** [comment]
@herms14 

I just edit module name  - avm-res-network-bastionhost
Please use Github Repo name - terraform-azurerm-avm-res-network-bastionhost

**Comment by herms14** [comment]
Thanks @prjelesi 



I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

**Comment by prjelesi** [comment]
@herms14 Thanks! moved to "In development"

**Comment by herms14** [comment]
Update on this modile - I already have the code available on my own repo. Still waiting for CELA to approve the repo under the Azure org - https://ossmsft.visualstudio.com/Reviews/_workitems/edit/48748

**Comment by herms14** [comment]
UPDATE - I have submitted a PR for review - https://github.com/Azure/terraform-azurerm-avm-res-network-bastionhost/pull/1

**Comment by mbilalamjad** [comment]
Hi @herms14, thank you for requesting a review of the PR and module, have provided feedback on the [PR](https://github.com/Azure/terraform-azurerm-avm-res-network-bastionhost/pull/1), appreciate if you could look into it and in case you have any questions or concerns than please feel free to reach out.

CC: @PmeshramPM, @matt-FFFFFF, @segraef

**Comment by mbilalamjad** [comment]
@herms14 recommend looking into the tests failing before merging and publishing version 0.1.0 module to the terraform registry.

**Comment by herms14** [comment]
module has been published in TF registry 

https://registry.terraform.io/modules/Azure/avm-res-network-bastionhost/azurerm/latest

**Comment by mbilalamjad** [comment]
Thank you so much @herms14 for owning and developing this module.

Closing this proposal as module has been published to terraform registry below.
https://registry.terraform.io/modules/Azure/avm-res-network-bastionhost/azurerm/latest

Further discussion on this module including issues & PRs to take please on its repo below.
https://github.com/Azure/terraform-azurerm-avm-res-network-bastionhost
