### ISSUE TITLE
[Module Proposal]: avm-pnt-subnet-nsg-rt-associations

### ISSUE THREAD

**Issue by VeronicaSea** [Azure/Azure-Verified-Modules#1566]
### Check for previous/existing GitHub issues/module proposals

- [x] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [x] I have checked for that this module doesn't already exist in the module indexes.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-pnt-subnet-nsg-rt-associations

### Module Details

We would like to create an AVM pattern module to deploy subnets associated with network security groups and route tables if needed.

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

VeronicaSea

**Comment by prjelesi** [comment]
Hi, check this request #1453

**Comment by VeronicaSea** [comment]
Tracking the request https://github.com/Azure/Azure-Verified-Modules/issues/1453
