### ISSUE TITLE
[Module Proposal]: `avm-ptn-vnetgateway` (tf)

### ISSUE THREAD

**Issue by mbilalamjad** [Azure/Azure-Verified-Modules#157]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals

### Check this module doesn't already exist in another project that is being evolved into AVM

- [X] I have checked for that this module doesn't already exist in CARML or TFVM

### Terraform or Bicep?

Terraform

### Module Classification?

Pattern Module

### Module Name

avm-ptn-vnetgateway

### Module Details

Terraform Module for VPN Gateway

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username

mbilalamjad

**Comment by PmeshramPM** [comment]
Hi @mbilalamjad, 

Thanks for requesting/proposing to be an AVM module owner.

We just want to confirm you agree to the below pages that define what module ownership means:

- https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions
- https://azure.github.io/Azure-Verified-Modules/specs/shared
- https://azure.github.io/Azure-Verified-Modules/help-support/module-support

Any questions or clarifications needed let us know.

If you agree please just reply to this issue with the exact sentence below (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks

The AVM Core Team

**Comment by PmeshramPM** [comment]
@mbilalamjad  - Thank you for proposing this one. For the VPN gateway the armresourcename name is vpngateways - 


I have edited the issue form to reflect the correct name ( avm-res-network-vpngateway) 

Please see the specification (https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-rmnfr1---category-naming---module-naming) 
Module names MUST follow the below pattern (all lower case):

Bicep: avm-res-<rp>-<armresourcename> (to support registry hosting)
Terraform:
avm-res-<rp>-<armresourcename> (Module name for registry)
terraform-<provider>-avm-res-<rp>-<armresourcename> (GitHub repository name to meet registry naming requirements)
<provider> is the logical abstraction of various APIs used by Terraform. In most cases, this is should to be azurerm for resource modules.
Example: avm-res-compute-virtualmachine

**Comment by matt-FFFFFF** [comment]
We have this already

@luke-taylor wrote one

**Comment by PmeshramPM** [comment]
@matt-FFFFFF - Would it make sense to convert the one written by @luke-taylor into AVM complaint? May be @luke-taylor can help with this one ?

**Comment by prjelesi** [comment]
@matt-FFFFFF pls advise how to proceed with this.

**Comment by matt-FFFFFF** [comment]
We will create a pattern module in AVM this week

**Comment by matt-FFFFFF** [comment]
It was in the ALZ backlog @JefferyMitchell 

Will do

**Comment by JefferyMitchell** [comment]
I found it! I see it was closed in July!

**Comment by PmeshramPM** [comment]
I had a discussion with @matt-FFFFFF over this and this is the summary 
1. The current module crated by @luke-taylor - (https://registry.terraform.io/modules/Azure/vnet-gateway/azurerm/latest) provides a better end user/customer experience. 
2. This module can deploy VPN or Express Route gateways along with route table configs. 
3. This module Supports configuring ER and  S2S vpn, etc.
4. Matt and Luke are working to evolve this module into AVM specs. 

Renaming this Issue into pattern module now and moving into Development.

**Comment by PmeshramPM** [comment]
Hi @luke-taylor 

Thanks for requesting/proposing to be an AVM module owner.

We just want to confirm you agree to the below pages that define what module ownership means:

https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions
https://azure.github.io/Azure-Verified-Modules/specs/shared
https://azure.github.io/Azure-Verified-Modules/help-support/module-support
Any questions or clarifications needed let us know.

If you agree please just reply to this issue with the exact sentence below (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks

The AVM Core Team

**Comment by luke-taylor** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by PmeshramPM** [comment]
Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

We just want to ask you to double check a few important things before you start the development.

Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page:

For your module:
ModuleName - to name your module
TelemetryIdPrefix - to be used in your module's telemetry
For your module's repository:
Repository name and folder path are defined in RepoURL
Create the GitHub teams defined in the ModuleOwnersGHTeam and ModuleContributorsGHTeam columns
You can now start the development of this module! ✅ Happy coding! 🎉

Please respond to this comment, once your module is ready to be published! 🙏

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team


NOTE:

This Module Proposal issue MUST remain open until the module is fully developed, tested and published to the relevant registry. Do NOT close the issue before the successful publication is confirmed!
Once the module is fully developed, tested and published to the relevant registry, and the Module Proposal issue was closed, it MUST remain closed.

**Comment by prjelesi** [comment]
@mbilalamjad , @PmeshramPM  Matta and Luke confirmed that module is published, please update index list.

**Comment by mbilalamjad** [comment]
Thank @luke-taylor & @matt-FFFFFF for contributing and publishing the module to the registry
https://registry.terraform.io/modules/Azure/avm-ptn-vnetgateway/azurerm/latest
