### ISSUE TITLE
[Module Proposal]: ` avm-ptn-virtualnetworkpeering` (tf)

### ISSUE THREAD

**Issue by herms14** [Azure/Azure-Verified-Modules#163]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals

### Check this module doesn't already exist in another project that is being evolved into AVM

- [X] I have checked for that this module doesn't already exist in CARML or TFVM

### Terraform or Bicep?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-ptn-virtualnetworkpeering

### Module Details

resource module for Azure virtual network peering 

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username

herms14

**Comment by matt-FFFFFF** [comment]
Hi @herms14 

We have this feature in the lz-vending module already. Albeit for vents created by this module only.

https://github.com/Azure/terraform-azurerm-lz-vending

Also due to subscription id constraints we would need to use AzAPI if we did use a separate module.

We also need to consider re-syncing the peerings if the address spaces change - only an issue AzAPI

**Comment by herms14** [comment]
got it @matt-FFFFFF. Thanks. for the info. lets close this issue then.

**Comment by matt-FFFFFF** [comment]
Not saying a standalone module is not valuable!

Just trying to set expectations

**Comment by PmeshramPM** [comment]
@matt-FFFFFF  @herms14  - I am looking at this one and could you please confirm if the LZ vending TF can be reused in other customer scenarios Or the customer has to use the lz vending then only they can get the peering? If yes, then we should have a standalone one as well which can be re-used in all other places.

**Comment by matt-FFFFFF** [comment]
@PmeshramPM 

Let's chat about this. It's not straight forward. We need to be sure of the functional spec before we dish it out.

**Comment by matebarabas** [comment]
Some additional food for thought: Please note that the VNET peering functionality is part of the VNET module in the Bicep version of the VNET template (this is currently in CARML but will be migrated to AVM soon): https://github.com/Azure/ResourceModules/tree/main/modules/network/virtual-network

**Comment by PmeshramPM** [comment]
I am having a discussion with @matt-FFFFFF @herms14  on this module. We are trying to figure out if it would make sense to have an separate Vnet Peer Module for all use cases.

**Comment by matt-FFFFFF** [comment]
I agree that one-sided vnet peering could be part of the virtualnetwork module.

However there could be a (pattern?) that allows us to create bidirectional peerings. However for that to be really useful we should use the AzAPI provider.

**Comment by prjelesi** [comment]
@matt-FFFFFF any advice on this?
I propose that vnet peering is part of VNET module and to align this part to be in line with bicep side.

**Comment by matt-FFFFFF** [comment]
Peer configuration is two sided.

The vnet module could do one half but not the other.

I still recommend (as an AND not an OR) we look into a pattern module for vnet peering.

**Comment by prjelesi** [comment]
I understand, and lets align this with Bicep part.

**Comment by prjelesi** [comment]
@herms14 sorry for waiting that we align. Lets process with creation of this module.

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

<br>

> **NOTE**:
>
> - This Module Proposal issue **MUST remain open** until the module is fully developed, tested and published to the relevant registry. **Do NOT close** the issue before the successful publication is confirmed!
> - Once the module is fully developed, tested and published to the relevant registry, and the Module Proposal issue was closed, it **MUST remain closed**.

**Comment by herms14** [comment]
"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

**Comment by prjelesi** [comment]
Hi @herms14 

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

We just want to ask you to double check a few important things and take the next steps before you start the development.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - avm-ptn-virtualnetworkpeering
  - `TelemetryIdPrefix` - to be used in your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry): 46d3xgtf.ptn.network-vnetpeering
- For your module's repository:
  - Repository name: terraform-azurerm-avm-ptn-virtualnetworkpeering
  - Create the GitHub teams defined in the `ModuleOwnersGHTeam` and `ModuleContributorsGHTeam` columns and grant them permissions as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only): @azure/avm-ptn-virtualnetworkpeering-module-owners-tf,@azure/avm-ptn-virtualnetworkpeering-module-contributors-tf.
    
    - In case of a Terraform module, follow the instructions [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#grant-permissions---terraform) and assign the necessary permissions.

Grant the right level of permissions for  the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment, once your module is ready to be published so we can trigger review process!** 🙏

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

<br>

> **NOTE**:
>
> - This Module Proposal issue **MUST remain open** until the module is fully developed, tested and published to the relevant registry. **Do NOT close** the issue before the successful publication is confirmed!
> - Once the module is fully developed, tested and published to the relevant registry, and the Module Proposal issue was closed, it **MUST remain closed**.

**Comment by herms14** [comment]
Update: Havent started yet on this. Will kickstart writing the code probably next week

**Comment by PmeshramPM** [comment]
based on last update from @herms14 removing the "needs attention" label

**Comment by herms14** [comment]
code is ready but needs more testing. looking at mid march for review

**Comment by herms14** [comment]
still working on it. was pushed back due to other urgent priorities

**Comment by jaredfholgate** [comment]
@matt-FFFFFF and @prjelesi I am wondering if this proposal is still valid, given we can achieve one way or two way peering with the vnet module: https://registry.terraform.io/modules/Azure/avm-res-network-virtualnetwork/azurerm/latest/submodules/peering

**Comment by PmeshramPM** [comment]
Closing this one since this functionality is available in Vnet module ( https://github.com/Azure/Azure-Verified-Modules/issues/62)
