### ISSUE TITLE
[Module Proposal]: `avm-ptn-avd-lza-insights` (tf)

### ISSUE THREAD

**Issue by jensheerin** [Azure/Azure-Verified-Modules#166]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals

### Check this module doesn't already exist in another project that is being evolved into AVM

- [X] I have checked for that this module doesn't already exist in CARML or TFVM

### Terraform or Bicep?

Terraform

### Module Classification?

Pattern Module

### Module Name

avm-ptn-avd-lza-insights

### Module Details

We will be migrating and modifying the Terraform module from AVD LZA.

Please add @jensheerin as co-owner

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username

cshea15

**Comment by jensheerin** [comment]
@matebarabas I met with @danycontre and @moisesjgomez and we are aligned. Can you we move to next steps?

cc: @cshea15 

I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by matebarabas** [comment]
@jensheerin, thanks for opening this request and volunteering! Thanks for aligning with @danycontre, @moisesjgomez and others.

I know you've already pasted the confirmation statement above, but for our records, please let me paste the request below (no need to respond to this again - unless you disagree 🙂). 

I'll also shortly send you a final confirmation that indicates you're good to go.

Thank you!

**Comment by matebarabas** [comment]
Hi @jensheerin,

Thanks for requesting/proposing to be an AVM module owner.

We just want to confirm you agree to the below pages that define what module ownership means:

- https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions
- https://azure.github.io/Azure-Verified-Modules/specs/shared
- https://azure.github.io/Azure-Verified-Modules/help-support/module-support

Any questions or clarifications needed, let us know.

If you agree please just reply to this issue with the exact sentence below (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

> @jensheerin: I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by matebarabas** [comment]
Hi @jensheerin,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities.

We just want to ask you to double check a few important things before you start the development.

Please visit the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page of your module and use the following values explicitly as provided there:

- `ModuleName`
- `TelemetryIdPrefix`
- `ModuleOwnersGHTeam` and `ModuleContributorsGHTeam`
- Repository name and folder path defined in `RepoURL`

You can now start the development of this module! Happy coding! 🎉

Please respond to this comment, once your module is ready to be published!

Any further questions or clarifications needed, let us know.

Thanks,

The AVM Core Team

**Comment by matebarabas** [comment]
Thanks for the update!

**Comment by jensheerin** [comment]
Correction in business review https://dev.azure.com/ossmsft/Reviews/_workitems/edit/49287
Repo https://github.com/Azure/avm-ptn-avd-lza-insights

**Comment by mbilalamjad** [comment]
Reached out to @jensheerin offline to confirm any updates or any supported need, she or I will update accordingly.

**Comment by jensheerin** [comment]
Repo updated and ready for review.

**Comment by jensheerin** [comment]
https://github.com/Azure/terraform-azurerm-avm-ptn-avd-lza-insights/

**Comment by prjelesi** [comment]
@jensheerin is review done?

**Comment by jensheerin** [comment]
@prjelesi  Not yet will ping Bilal

**Comment by mbilalamjad** [comment]
Hey @jensheerin per our discussion offline, kindly perform the "Requested Actions" in the [AVM-Review](https://github.com/Azure/terraform-azurerm-avm-ptn-avd-lza-insights/issues/27) of the module, feel free to reach out if you have any questions or need any support.

**Comment by jensheerin** [comment]
"The https://github.com/Azure/terraform-azurerm-avm-ptn-avd-lza-insights/issues/27 of this module has been completed and the module has been published to the registry. Requesting AVM team to update this module proposal and module index accordingly."

**Comment by mbilalamjad** [comment]
Thank you so much @jensheerin for owning and developing this module.

The module index on the AVM website has been updated to reflect the same.

The module has been moved from "In Review" to "Done" in the "AVM - Module Triage" Project.

This proposal (issue) is being closed as module has been published to terraform registry per below.
https://registry.terraform.io/modules/Azure/avm-ptn-avd-lza-insights/azurerm/latest

Any Further discussion on this module including issues & PRs to take please on its repo per below.
https://github.com/Azure/terraform-azurerm-avm-ptn-avd-lza-insights
