### ISSUE TITLE
[Module Proposal]: `avm-res-desktopvirtualization-applicationgroup` (tf)

### ISSUE THREAD

**Issue by jensheerin** [Azure/Azure-Verified-Modules#169]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals

### Check this module doesn't already exist in another project that is being evolved into AVM

- [X] I have checked for that this module doesn't already exist in CARML or TFVM

### Terraform or Bicep?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-desktopvirtualization-applicationgroup

### Module Details

We will be migrating and modifying the Terraform module we are using for AVD LZA.

Please add as the following co-owner:
@cshea15

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username

jensheerin

**Comment by jensheerin** [comment]
cc: @danycontre and @moisesjgomez 
 
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by matebarabas** [comment]
@jensheerin, thanks for opening this request and volunteering! Thanks for aligning with @matt-FFFFFF, @danycontre and others.

I know you've already pasted the confirmation statement above, but for our records, please let me paste the request below (no need to respond to this again - unless you disagree :) ). 

I'll also shortly send you a final confirmation that indicates you're good to go.

Thank you!

**Comment by matebarabas** [comment]
Hi @jensheerin,

Thanks for requesting/proposing to be an AVM module owner.

We just want to confirm you agree to the below pages that define what module ownership means:

- https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions
- https://azure.github.io/Azure-Verified-Modules/specs/shared
- https://azure.github.io/Azure-Verified-Modules/help-support/module-support

Any questions or clarifications needed, let us know.

If you agree please just reply to this issue with the exact sentence below (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

> @jensheerin: I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by matebarabas** [comment]
Hi @jensheerin,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities.

We just want to ask you to double check a few important things before you start the development.

Please visit the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page of your module and use the following values explicitly as provided there:

- `ModuleName`
- `TelemetryIdPrefix`
- `ModuleOwnersGHTeam` and `ModuleContributorsGHTeam`
- Repository name and folder path defined in `RepoURL`

You can now start the development of this module! Happy coding! 🎉

Please respond to this comment, once your module is ready to be published!

Any further questions or clarifications needed, let us know.

Thanks,

The AVM Core Team

**Comment by jensheerin** [comment]
In progress https://github.com/Azure/terraform-azurerm-avm-res-desktopvirtualization-applicationgroups

**Comment by jensheerin** [comment]
CELA completed https://ossmsft.visualstudio.com/Reviews/_workitems/edit/48610?src=WorkItemMention&src-action=artifact_link

PR submitted https://github.com/Azure/terraform-azurerm-avm-res-desktopvirtualization-applicationgroup/pull/2

**Comment by matebarabas** [comment]
Great progress, @jensheerin! Can you please ping me here when this PR was reviewed, merged and the module is published? Thanks!

**Comment by jensheerin** [comment]
PR reviewed and merged. Published in HarshiCorp Registry https://registry.terraform.io/modules/Azure/avm-res-desktopvirtualization-applicationgroup/azurerm/latest

**Comment by matebarabas** [comment]
- [x] Module published.
- [x] GitHub teams created and assigned to their respective parents.

Thank you @jensheerin for your work! Closing the issue.
