### ISSUE TITLE
[Module Proposal]: `avm-res-network-ipampool`

### ISSUE THREAD

**Issue by teowa** [Azure/Azure-Verified-Modules#1705]
### Check for previous/existing GitHub issues/module proposals

- [x] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [x] I have checked for that this module doesn't already exist in the module indexes.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-network-ipampool

### Module Details

AVM Terraform module for Network Manager IP address management, For more information, see the [Azure documentation](https://learn.microsoft.com/en-us/azure/virtual-network-manager/how-to-manage-ip-addresses-network-manager?tabs=azureportal).
The repo is created at https://github.com/Azure/terraform-azapi-avm-res-network-ipampool

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

teowa

**Comment by teowa** [comment]
I have completed my initial development of the module and I would like to request a review of my module before publishing it to the terraform registry. The latest code is in a PR titled [AVM-Review-PR](https://github.com/Azure/terraform-azapi-avm-res-network-ipampool/pull/1) on the module repo and all checks on that PR are passing except the e2e test, which can pass in my local.

**Comment by fafriha** [comment]
Thank you for requesting a review of your module. The AVM module review process has been initiated, please perform the **Requested Actions** on the AVM-Review issue on the module repo.

**Comment by mbilalamjad** [comment]
Hi @teowa,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by mbilalamjad** [comment]
Hey @teowa,

Thanks for the module proposal, just want to confirm if you've reviewed this [spec ](https://azure.github.io/Azure-Verified-Modules/specs/shared/#terraform-resource-module-naming)and that this proposal aligns with it.

**Comment by fafriha** [comment]
@teowa It appaers that the testing environment was not set up because this module was not approved. As described in our specs, we should wait for approval from the Core Team before starting any development. Please connect with @cshea-msft to discuss how you can integrate this into his module. Charles developed the network manager module, and this module should be a sub-module of it rather than a separate one.

**Comment by teowa** [comment]
@fafriha , thanks for advice. I will consider integrate this into the network manager module.
