### ISSUE TITLE
[Orphaned Module]: `avm/res/sql/instance-pool`

### ISSUE THREAD

**Issue by matebarabas** [Azure/Azure-Verified-Modules#1718]
### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/sql/instance-pool

### Module Details

@yashints, please perform the steps under point 5. of [this guide](https://azure.github.io/Azure-Verified-Modules/help-support/issue-triage/avm-issue-triage/#when-a-module-becomes-orphaned). Thanks!

**Note**: when someone volunteers to be the owner of this module, please follow the steps below:
  - "un-orphaning" the module by performing step 5, here: [When a New Owner is Identified](https://azure.github.io/Azure-Verified-Modules/help-support/issue-triage/avm-issue-triage/#when-a-new-owner-is-identified)
  - request change of ownership on the existing GitHub teams.

Original module proposal: https://github.com/Azure/Azure-Verified-Modules/issues/752
PR: https://github.com/Azure/bicep-registry-modules/pull/1714
Code: https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/sql/instance-pool

### Do you want to be the new owner of this module?

No

**Comment by matebarabas** [comment]
Orphaning PR: https://github.com/Azure/bicep-registry-modules/pull/3846

**Comment by gpacetti** [comment]
Please, you can sign me as owner.

**Comment by matebarabas** [comment]
Hi @gpacetti,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

Before starting development, please ensure ALL the following requirements are met.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - for naming your module
  - `TelemetryIdPrefix` - for your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repo name and folder path are defined in `RepoURL`
  - Create GitHub teams for module owners and contributors and grant them permissions as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
  - Grant permissions for the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

Check if this module exists in the other IaC language. If so, collaborate with the other owner for consistency. 👍

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published! Please include a link pointing to your PR, once available. 🙏**

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by matebarabas** [comment]
Hi @gpacetti,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by gpacetti** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

Inviato da Outlook per iOS<https://aka.ms/o0ukef>
________________________________
Da: Máté Barabás ***@***.***>
Inviato: Saturday, December 7, 2024 12:29:46 AM
A: Azure/Azure-Verified-Modules ***@***.***>
Cc: gpacetti ***@***.***>; Mention ***@***.***>
Oggetto: Re: [Azure/Azure-Verified-Modules] [Orphaned Module]: `avm/res/sql/instance-pool` (Issue #1718)


Hi @gpacetti<https://github.com/gpacetti>,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm you agree to the below pages that define what module ownership means:

  *   Team Definitions & RACI<https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions>
  *   Shared Specification (Bicep & Terraform)<https://azure.github.io/Azure-Verified-Modules/specs/shared>
  *   Module Support<https://azure.github.io/Azure-Verified-Modules/help-support/module-support>

Any questions or clarifications needed, let us know!

If you agree, please just reply to this issue with the exact sentence below (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by matebarabas** [comment]
Hi @gpacetti,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

We just want to ask you to double check a few important things.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- You must be the owner of the GitHub teams as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
- Please check that your name has been updated in the module index page (this should happen shortly after you confirmed ownership).

You can now take ownership of this module and start improving it as needed! ✅ Happy coding! 🎉

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by matebarabas** [comment]
@gpacetti, as discussed internally, please assign your GitHub account to your Microsoft corp account and join the Azure GH organization. Then, the previous owner (@yashints) will be able to reassign the 2 administrative GH teams to you. Thank you!

**Comment by gpacetti** [comment]
Hi Máté
thanks for all. I've already linked my Github and Microsoft accounts. I think It is ok, if the configuration is not ok, let me know that I'll provide to fix it.

[cid:09e9b9ad-3ee1-4d06-83b5-4ea09c2a11f5]

________________________________

**Comment by matebarabas** [comment]
@gpacetti, all requirements for taking ownership have been met.

- Module index updated with your name
- You're the maintainer of the module's 2 GH teams
- As the orphaned disclaimer hasn't been added to the module's readme, there's no need to revert this step.

Thanks again for taking over this module! I'm closing this issue now.
