### ISSUE TITLE
[Module Proposal]: `avm/ptn/authorization/policy-exemption`

### ISSUE THREAD

**Issue by oZakari** [Azure/Azure-Verified-Modules#1735]
### Check for previous/existing GitHub issues/module proposals

- [x] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [x] I have checked for that this module doesn't already exist in the module indexes.

### Bicep or Terraform?

Bicep

### Module Classification?

Pattern Module

### Module Name

avm/ptn/authorization/policy-exemption

### Module Details

Create pattern module to allow the deployment of policy exemptions at management group, subscription level, and resource group scopes.

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

oZakari

**Comment by matebarabas** [comment]
Hi @oZakari,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by matebarabas** [comment]
- [x] Module published.
- [x] GitHub teams are available and assigned to their parents.
- [x] `CODEOWNERS` file updated.
- [x] Issue template file updated.

The module index will be updated to reflect this change.
 
Thank you for your work @oZakari!
