### ISSUE TITLE
[Orphaned Module]: `avm/res/cognitive-services/account`

### ISSUE THREAD

**Issue by matebarabas** [Azure/Azure-Verified-Modules#224]
### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/cognitive-services/account

### Module Details

This module was migrated from CARML without having an owner.

### Do you want to be the new owner of this module?

No

**Comment by ilhaan** [comment]
@matebarabas I'm interested in taking ownership for the `avm-res-cognitiveservices-account` bicep module.

**Comment by matebarabas** [comment]
Hi @ilhaan,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

<br>

> **NOTE**:
>
> - This Orphaned Module issue **MUST remain open** until the ownership is fully confirmed!
> - Once the Orphaned Module issue was closed, it **MUST remain closed**. If the module will subsequently become orphaned again, a new Orphaned Module issue must be opened.

**Comment by ilhaan** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by matebarabas** [comment]
Hi @ilhaan,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

We just want to ask you to double check a few important things.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- You must be the owner of the GitHub teams defined in the `ModuleOwnersGHTeam` and `ModuleContributorsGHTeam` columns
- Pleas check that your name has been updated in the module index page (this should happen shortly after you confirmed ownership).

You can now take ownership of this module and start improving it as needed! ✅ Happy coding! 🎉

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

<br>

> **NOTE**:
>
> - This Orphaned Module issue **MUST remain open** until the ownership is fully confirmed!
> - Once the Orphaned Module issue was closed, it **MUST remain closed**. If the module will subsequently become orphaned again, a new Orphaned Module issue must be opened.

**Comment by ilhaan** [comment]
Github teams created: 
* https://github.com/orgs/Azure/teams/avm-res-cognitiveservices-account-module-owners-bicep
* https://github.com/orgs/Azure/teams/avm-res-cognitiveservices-account-module-contributors-bicep

**Comment by matebarabas** [comment]
@ilhaan,

Due to a recent change in the naming convention for AVM Bicep modules, this module is getting an updated name.

The title and description of this GH issue has been updated to reflect the name change. **Please make sure you adhere to the new naming convention when publishing your module!** 

Please see the new naming convention in:
- [RMNFR1](https://azure.github.io/Azure-Verified-Modules/specs/shared/#bicep-resource-module-naming) for resource modules
- [PMNFR1](https://azure.github.io/Azure-Verified-Modules/specs/shared/#bicep-pattern-module-naming) for pattern modules

Please note that the Telemetry ID and name of GitHub Teams haven't changed.

If you feel uncertain about any details, please check the [Bicep modules indexes](https://azure.github.io/Azure-Verified-Modules/indexes/bicep/).
