### ISSUE TITLE
[Module Proposal]: `avm-res-network-networkwatcher` (tf)

### ISSUE THREAD

**Issue by ehaslett** [Azure/Azure-Verified-Modules#236]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-network-networkwatcher

### Module Details

Azure Verified Module for Network Watcher

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

ehaslett

### (Optional) Secondary Module Owner's GitHub Username (handle)

maheshbenke

**Comment by prjelesi** [comment]
@ehaslett let's sync about this.

**Comment by ehaslett** [comment]
> @ehaslett let's sync about this so i can proceed with triage.

Sent email to sync up including Jeff Mitchell

**Comment by prjelesi** [comment]
@ehaslett did you had chance to review bicep implementation? Do you want to proceed with this?

**Comment by prjelesi** [comment]
@ehaslett , as we agree lets proceed with including child configuration. You can use Bicep module as reference,
Please respond when you get back 'online'. 

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

<br>

> **NOTE**:
>
> - This Module Proposal issue **MUST remain open** until the module is fully developed, tested and published to the relevant registry. **Do NOT close** the issue before the successful publication is confirmed!
> - Once the module is fully developed, tested and published to the relevant registry, and the Module Proposal issue was closed, it **MUST remain closed**.

**Comment by ehaslett** [comment]
> @ehaslett , as we agree lets proceed with including child configuration. You can use Bicep module as reference, Please respond when you get back 'online'.
> 
> Thanks for requesting/proposing to be an AVM module owner!
> 
> We just want to confirm **you agree to the below pages** that define what module ownership means:
> 
> * [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
> * [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
> * [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)
> 
> Any questions or clarifications needed, let us know!
> 
> If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):
> 
> "I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"
> 
> Thanks,
> 
> The AVM Core Team
> 
> #RR
> 
> 
> > **NOTE**:
> > 
> > * This Module Proposal issue **MUST remain open** until the module is fully developed, tested and published to the relevant registry. **Do NOT close** the issue before the successful publication is confirmed!
> > * Once the module is fully developed, tested and published to the relevant registry, and the Module Proposal issue was closed, it **MUST remain closed**.

Hi @prjelesi - Reviewing with Jeff Mitchell tomorrow to make sure I have the correct alignment. I expect to confirm the above Tuesday afternoon Eastern time.

**Comment by ehaslett** [comment]
> > @ehaslett , as we agree lets proceed with including child configuration. You can use Bicep module as reference, Please respond when you get back 'online'.
> > Thanks for requesting/proposing to be an AVM module owner!
> > We just want to confirm **you agree to the below pages** that define what module ownership means:
> > 
> > * [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
> > * [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
> > * [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)
> > 
> > Any questions or clarifications needed, let us know!
> > If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):
> > "I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"
> > Thanks,
> > The AVM Core Team
> > #RR
> > > **NOTE**:
> > > 
> > > * This Module Proposal issue **MUST remain open** until the module is fully developed, tested and published to the relevant registry. **Do NOT close** the issue before the successful publication is confirmed!
> > > * Once the module is fully developed, tested and published to the relevant registry, and the Module Proposal issue was closed, it **MUST remain closed**.
> 
> Hi @prjelesi - Reviewing with Jeff Mitchell tomorrow to make sure I have the correct alignment. I expect to confirm the above Tuesday afternoon Eastern time.

@prjelesi - Received the clarity I was hoping for today after connecting with Jeff Mitchell and Bilal. Thank you for your patience.

**Comment by ehaslett** [comment]
"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

**Comment by ehaslett** [comment]
@prjelesi - please see above confirmation. Thank you.

**Comment by prjelesi** [comment]
Hi @ehaslett ,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

We just want to ask you to double check a few important things and take the next steps before you start the development.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - avm-res-network-networkwatcher
  - `TelemetryIdPrefix` - to be used in your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry): 46d3xgtf.res.network-networkwatcher
- For your module's repository:
  - Repository name : terraform-azurerm-avm-res-network-networkwatcher
  - Create the GitHub teams defined in the `ModuleOwnersGHTeam` and `ModuleContributorsGHTeam` columns and grant them permissions as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only): @azure/avm-res-network-networkwatcher-module-owners-tf,@azure/avm-res-network-networkwatcher-module-contributors-tf
    - follow the instructions [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#grant-permissions---terraform) and assign the necessary permissions.

Grant the right level of permissions for  the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published!** Please include a link pointing to your PR if available. 🙏

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

<br>

> **NOTE**:
>
> - This Module Proposal issue **MUST remain open** until the module is fully developed, tested and published to the relevant registry. **Do NOT close** the issue before the successful publication is confirmed!
> - Once the module is fully developed, tested and published to the relevant registry, and the Module Proposal issue was closed, it **MUST remain closed**.

**Comment by ehaslett** [comment]
Pre-empted for several weeks by U.S. holiday, a week out sick with Covid, and subsequent backlog of customer work the first week of December. Expect work on this mid to late December.

**Comment by PmeshramPM** [comment]
followed up with @ehaslett and he is going to continue with next steps in development.

**Comment by ehaslett** [comment]
Repo created, teams created, teams associated/permitted with repo, waiting review before I can proceed with next steps

**Comment by mbilalamjad** [comment]
@ehaslett ran into an issue with the labels on the repo which has been resolved and he's currently working on it

**Comment by terrymandin** [comment]
Ownership of this AVM will be transferred to myself: Terry Mandin

**Comment by prjelesi** [comment]
@terrymandin formal thing:

If you agree to own this module from now, please just reply to this issue with the exact sentence below (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by terrymandin** [comment]
Shivam Tripathi (NW PM), Misba (CSU Tech Lead) and I met to discuss how Network Watcher related services should be implemented as AVMs.  Recommendations below:

- Flow log and traffic analytics AVMs: Flow log should have its own AVM which includes Traffic Analytics.  Flow Logs and Traffic Analytics will optionally be enabled as part of VNET and NSG AVMs.
- Connection monitor AVMs: Connection monitor should have its own AVM and should be optionally enabled as part of VNET, VM and VMSS AVMs.
- Packet capture AVMs: Packet capture should be an independent AVM and not linked to any other resource creation.
- Network watcher AVMs: Network watcher AVM is not needed.  Adding a Network Watcher AVM with enable/disable capabilities could lead to undesirable IaC actions.  For example, disabling a NW will remove any related connection monitors, flow logs, etc.  IaC will then attempt to recreate them.  Instead of disabling a NW, it is better to use IaC to remove the related services directly.

Follow-up tasks

Flow log and traffic analytics: 
- Create AVM (Terry/Pankaj)
- Add AVM to VNET and NSG AVMs (TBD)
- Track down the owners of the Terraform providers and work with them to add missing functionality (Terry)
Connection monitor: 
- Create AVM (Terry/Pankaj)
- Add AVM to VNET module (TBD)
- Add AVM to VMSS module (Terry)
- Add AVM to VM module (Terry/Jon)
Network Watcher:
- Delete existing AVM repo (Terry)

New proposals will be created for Flow Log and Connection Monitoring.

**Comment by prjelesi** [comment]
@terrymandin bring back this. Let's process.

**Comment by prjelesi** [comment]
Hi @terrymandin 

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by terrymandin** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by terrymandin** [comment]
@prjelesi @PmeshramPM @mbilalamjad, this AVM PR is ready for review.

PR: [Initial Pull Request](https://github.com/Azure/terraform-azurerm-avm-res-network-networkwatcher/pull/34)

**Comment by mbilalamjad** [comment]
Thank you for requesting a review of your module. The [AVM module review process](https://azure.github.io/Azure-Verified-Modules/contributing/terraform/review/) has been initiated, please perform the **Requested Actions** on the [AVM-Review issue](https://github.com/Azure/terraform-azurerm-avm-res-network-networkwatcher/issues/37) on the module repo.
