### ISSUE TITLE
[Module Proposal]: `avm-res-app-managedenvironment` (tf)

### ISSUE THREAD

**Issue by kewalaka** [Azure/Azure-Verified-Modules#241]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-app-managedenvironment

### Module Details

Azure Verified Module for container apps managed environment.  Following the bicep pattern from CARML where managed environments are a separate resource module.

### Do you want to be the owner of this module?

No

### Module Owner's GitHub Username (handle)

segraef

### (Optional) Secondary Module Owner's GitHub Username (handle)

kewalaka

**Comment by kewalaka** [comment]
I've got the beginnings of a module here - covering functionality I currently need - i.e. workload profiles & vnet integration.

https://github.com/kewalaka/terraform-azurerm-avm-res-app-managedenvironment

**Comment by prjelesi** [comment]
@kewalaka than you for module proposal! We will work to find module owner.

**Comment by mbilalamjad** [comment]
Hi @segraef,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

<br>

> **NOTE**:
>
> - This Module Proposal issue **MUST remain open** until the module is fully developed, tested and published to the relevant registry. **Do NOT close** the issue before the successful publication is confirmed!
> - Once the module is fully developed, tested and published to the relevant registry, and the Module Proposal issue was closed, it **MUST remain closed**.

**Comment by segraef** [comment]
"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

**Comment by segraef** [comment]
@kewalaka let me know if you need anything else you should be good to go now with your development and thanks in advance for your contribution!

**Comment by mbilalamjad** [comment]
Hi @segraef,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

We just want to ask you to double check a few important things and take the next steps before you start the development.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - to name your module
  - `TelemetryIdPrefix` - to be used in your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repository name and folder path are defined in `RepoURL`
  - Create the GitHub teams defined in the `ModuleOwnersGHTeam` and `ModuleContributorsGHTeam` columns and grant them permissions as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
    - In case of a Bicep module, **please let the AVM core team know** when you created these teams, and we'll help you with assigning the necessary permissions as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#grant-permissions---bicep).
    - In case of a Terraform module, follow the instructions [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#grant-permissions---terraform) and assign the necessary permissions.

Grant the right level of permissions for  the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published!** Please include a link pointing to your PR if available. 🙏

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

<br>

> **NOTE**:
>
> - This Module Proposal issue **MUST remain open** until the module is fully developed, tested and published to the relevant registry. **Do NOT close** the issue before the successful publication is confirmed!
> - Once the module is fully developed, tested and published to the relevant registry, and the Module Proposal issue was closed, it **MUST remain closed**.

**Comment by mbilalamjad** [comment]
> @kewalaka let me know if you need anything else you should be good to go now with your development and thanks in advance for your contribution!

@segraef I believe you'll need to help @kewalaka by creating the repo from the template into the Azure Org as he won't be able to do that, once you do then he can PR his contribution into that repo

**Comment by segraef** [comment]
Repo https://github.com/Azure/terraform-azurerm-avm-res-app-managedenvironment created, once internal business review is completed it will appear for you @kewalaka.

**Comment by segraef** [comment]
BR still in progress, just triggered internally to get some updates, thank you for your patience.

**Comment by segraef** [comment]
There you go https://github.com/Azure/terraform-azurerm-avm-res-app-managedenvironment.

**Comment by mbilalamjad** [comment]
@kewalaka if you could PR your contribution into the repo above than @segraef could review it

**Comment by kewalaka** [comment]
@segraef - https://github.com/Azure/terraform-azurerm-avm-res-app-managedenvironment/pull/1

cc @mbilalamjad

**Comment by segraef** [comment]
looking at it

**Comment by segraef** [comment]
Merged https://github.com/Azure/terraform-azurerm-avm-res-app-managedenvironment/pull/1, adding labels, tags now before going to publish.

**Comment by segraef** [comment]
> hi @segraef - [Azure/terraform-azurerm-avm-res-app-managedenvironment#10](https://github.com/Azure/terraform-azurerm-avm-res-app-managedenvironment/pull/10) better aligns the module inputs with azurerm & fixes recent governance updates - all grept changes addressed with the exception of E2E - since that needs the internal runners.
> 
> I'd suggest we land that before v0.1.0.
> 
> Do we have approval from the core AVM team to publish?

Thanks, regarding the runners I will get in touch with @matt-FFFFFF and @lonegunmanb who are in the process of transitioning the repos to the self-hosted runers.

To get the approval from another peer of the core team, such as @matt-FFFFFF or @mbilalamjad (instead of me) I'm going to add the team as reviewer to

**Comment by PmeshramPM** [comment]
Based on update from @segraef - removing the needs attention label

**Comment by segraef** [comment]
Development still ongoing https://github.com/Azure/terraform-azurerm-avm-res-app-managedenvironment/pull/17

**Comment by mbilalamjad** [comment]
Reached out to @segraef offline to confirm any updates or any supported need, he or I will update accordingly.

**Comment by segraef** [comment]
Module published https://github.com/Azure/terraform-azurerm-avm-res-app-managedenvironment

**Comment by mbilalamjad** [comment]
Thank you so much @segraef & @kewalaka for your contribution

Closing as module has been published to terraform registry below
 https://registry.terraform.io/modules/Azure/avm-res-app-managedenvironment/azurerm/latest

Further discussion on this module including issues & PRs to take please on its repo below
https://github.com/Azure/terraform-azurerm-avm-res-app-managedenvironment
