### ISSUE TITLE
[Module Proposal]: `avm-res-compute-sshpublickey` (tf)

### ISSUE THREAD

**Issue by ChrisSidebotham** [Azure/Azure-Verified-Modules#253]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-compute-sshpublickey

### Module Details

Create new module. Bicep version already available in BRM

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

ChrisSidebotham

**Comment by mbilalamjad** [comment]
Hi @ChrisSidebotham,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

<br>

> **NOTE**:
>
> - This Module Proposal issue **MUST remain open** until the module is fully developed, tested and published to the relevant registry. **Do NOT close** the issue before the successful publication is confirmed!
> - Once the module is fully developed, tested and published to the relevant registry, and the Module Proposal issue was closed, it **MUST remain closed**.

**Comment by ChrisSidebotham** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by mbilalamjad** [comment]
Hi @ChrisSidebotham,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

We just want to ask you to double check a few important things and take the next steps before you start the development.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - to name your module
  - `TelemetryIdPrefix` - to be used in your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repository name and folder path are defined in `RepoURL`
  - Create the GitHub teams defined in the `ModuleOwnersGHTeam` and `ModuleContributorsGHTeam` columns and grant them permissions as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
    - In case of a Bicep module, **please let the AVM core team know** when you created these teams, and we'll help you with assigning the necessary permissions as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#grant-permissions---bicep).
    - In case of a Terraform module, follow the instructions [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#grant-permissions---terraform) and assign the necessary permissions.

Grant the right level of permissions for  the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published!** Please include a link pointing to your PR if available. 🙏

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

<br>

> **NOTE**:
>
> - This Module Proposal issue **MUST remain open** until the module is fully developed, tested and published to the relevant registry. **Do NOT close** the issue before the successful publication is confirmed!
> - Once the module is fully developed, tested and published to the relevant registry, and the Module Proposal issue was closed, it **MUST remain closed**.

**Comment by ChrisSidebotham** [comment]
Haven't gotten around to this yet but will shortly 👍

**Comment by ChrisSidebotham** [comment]
No attention needed been busy with the bicep CI - will get around to this in the coming weeks

**Comment by ChrisSidebotham** [comment]
awaiting approval via internal process

**Comment by mbilalamjad** [comment]
Reached out to the relevant team to get an update on the business review of the repo.

**Comment by ChrisSidebotham** [comment]
Approvals being handled offline by @mbilalamjad

**Comment by mbilalamjad** [comment]
> Approvals being handled offline by @mbilalamjad

@ChrisSidebotham I see the internal review completed on April 2nd, you might have received an email update from the concerned team, you're good to go

**Comment by ChrisSidebotham** [comment]
@mbilalamjad - PR Pending Review https://github.com/Azure/terraform-azurerm-avm-res-compute-sshpublickey/pull/5

**Comment by mbilalamjad** [comment]
> @mbilalamjad - PR Pending Review [Azure/terraform-azurerm-avm-res-compute-sshpublickey#5](https://github.com/Azure/terraform-azurerm-avm-res-compute-sshpublickey/pull/5)

Hey @ChrisSidebotham, kindly perform the "Requested Actions" in the [AVM-Module](https://github.com/Azure/terraform-azurerm-avm-res-compute-sshpublickey/issues/14) of the module, feel free to reach out if you have any questions or need any support.

**Comment by ChrisSidebotham** [comment]
Module Published https://registry.terraform.io/modules/Azure/avm-res-compute-sshpublickey/azurerm/latest

**Comment by ChrisSidebotham** [comment]
@PmeshramPM

**Comment by mbilalamjad** [comment]
Thank you so much @ChrisSidebotham for owning and developing this module.

The module index on the AVM website has been updated to reflect the same.

The module has been moved from "In Review" to "Done" in the "AVM - Module Triage" Project.

This proposal (issue) is being closed as module has been published to terraform registry per below.
https://registry.terraform.io/modules/Azure/avm-res-compute-sshpublickey/azurerm/latest

Any Further discussion on this module including issues & PRs to take please on its repo per below.
https://github.com/Azure/terraform-azurerm-avm-res-compute-sshpublickey
