### ISSUE TITLE
[Module Proposal]: `avm-res-cdn-profile` (tf)

### ISSUE THREAD

**Issue by Poven795909** [Azure/Azure-Verified-Modules#254]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-cdn-profile

### Module Details

Creating resource module on Azure front door service.

Kindly add 'didayal-msft' as co-owner.

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

Poven795909

### (Optional) Secondary Module Owner's GitHub Username (handle)

didayal-msft

**Comment by prjelesi** [comment]
Hi @Poven795909 ,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

<br>

> **NOTE**:
>
> - This Module Proposal issue **MUST remain open** until the module is fully developed, tested and published to the relevant registry. **Do NOT close** the issue before the successful publication is confirmed!
> - Once the module is fully developed, tested and published to the relevant registry, and the Module Proposal issue was closed, it **MUST remain closed**.

**Comment by Poven795909** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by prjelesi** [comment]
Hi @Poven795909 

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

We just want to ask you to double check a few important things and take the next steps before you start the development.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - avm-res-network-frontdoor
  - `TelemetryIdPrefix` - 46d3xgtf.res.network-frontdoor - to be used in your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repository name : terraform-azurerm-avm-res-network-frontdoor
  - Create the GitHub teams defined in the `ModuleOwnersGHTeam` and `ModuleContributorsGHTeam` columns and grant them permissions as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only): @azure/avm-res-network-frontdoor-module-owners-tf,@azure/avm-res-network-frontdoor-module-contributors-tf .
  - Follow the instructions [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#grant-permissions---terraform) and assign the necessary permissions.

Grant the right level of permissions for  the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published!** Please include a link pointing to your PR if available. 🙏

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

<br>

> **NOTE**:
>
> - This Module Proposal issue **MUST remain open** until the module is fully developed, tested and published to the relevant registry. **Do NOT close** the issue before the successful publication is confirmed!
> - Once the module is fully developed, tested and published to the relevant registry, and the Module Proposal issue was closed, it **MUST remain closed**.

**Comment by Poven795909** [comment]
> Hi @Poven795909
> 
> Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!
> 
> We just want to ask you to double check a few important things and take the next steps before you start the development.
> 
> **Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:
> 
> * For your module:
>   
>   * `ModuleName` - avm-res-network-frontdoor
>   * `TelemetryIdPrefix` - 46d3xgtf.res.network-frontdoor - to be used in your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
> * For your module's repository:
>   
>   * Repository name : terraform-azurerm-avm-res-network-frontdoor
>   * Create the GitHub teams defined in the `ModuleOwnersGHTeam` and `ModuleContributorsGHTeam` columns and grant them permissions as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only): @azure/avm-res-network-frontdoor-module-owners-tf,@azure/avm-res-network-frontdoor-module-contributors-tf .
>   * Follow the instructions [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#grant-permissions---terraform) and assign the necessary permissions.
> 
> Grant the right level of permissions for the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).
> 
> You can now start the development of this module! ✅ Happy coding! 🎉
> 
> **Please respond to this comment and request a review from the AVM core team once your module is ready to be published!** Please include a link pointing to your PR if available. 🙏
> 
> Any further questions or clarifications needed, let us know!
> 
> Thanks,
> 
> The AVM Core Team
> 
> 
> > **NOTE**:
> > 
> > * This Module Proposal issue **MUST remain open** until the module is fully developed, tested and published to the relevant registry. **Do NOT close** the issue before the successful publication is confirmed!
> > * Once the module is fully developed, tested and published to the relevant registry, and the Module Proposal issue was closed, it **MUST remain closed**.

*** I have updated the name of the module to focus on Standard/Premium SKUs of Front door as confirmed by PG, please update your response as necessary ****

**Comment by prjelesi** [comment]
@Poven795909 ,

updated data:

**Module name:** avm-res-cdn-profile,New Module 
**Repository name:** terraform-azurerm-avm-res-cdn-profile
**Telemetry ID:** 46d3xgtf.res.cdn-profile
**Github teams that you need to create:** @azure/avm-res-cdn-profile-module-owners-tf,@azure/avm-res-cdn-profile-module-contributors-tf

Let us know if you need anything else.
Happy coding !

**Comment by Poven795909** [comment]
Repo Created --> https://github.com/Azure/terraform-azurerm-avm-res-cdn-profile 
Please let me know if this Issues needs to be closed. @prjelesi

**Comment by Poven795909** [comment]
Work is in progress

**Comment by cshea-msft** [comment]
@Poven795909 is this just focused on CDN or does it include Front door as well?

**Comment by Poven795909** [comment]
@cshea-msft  Currently we are focusing only on Frontdoor .. not working on CDN.

**Comment by cshea-msft** [comment]
Awesome, I saw the cdn in the name so I wasn't sure. Is there an ETA on when this might be public? I have a customer who is going to deploy Front Door in TF and want to know best practices so I thought your repo would be great to share.

**Comment by Poven795909** [comment]
@cshea-msft  We are aiming to complete the Dev work in another 2-3 weeks and post that we would include changes based on Reviews and feedbacks. A rough ETA could be by March end ?

**Comment by kewalaka** [comment]
@Poven795909 is it possible to make the repo publicly visible (or add me as a contributor & I can help)?  I have a customer interested in this too, I have experience writing AVM modules.

**Comment by Poven795909** [comment]
HI @kewalaka thanks for helping .. we have created the module and currently validating few configurations. Will reach out to you to review the contents before we publish [ ETA - in a week].

**Comment by v-xuto** [comment]
Related to issue: https://github.com/Azure/Azure-Verified-Modules/issues/261
CC: @jongio

**Comment by v-xuto** [comment]
@Poven795909 Any progress? Do you have an ETA for this?

**Comment by Poven795909** [comment]
Hi @v-xuto thanks for following up. We couldn't progress much due to other business priorities, however we have dedicated time reserved in the coming weeks to work on this hence the new ETA is April End.

**Comment by Poven795909** [comment]
@mbilalamjad @prjelesi Can you please add Divyadeep [ didayal-msft ] as the co-owner ? I have mentioned this in the module proposal but I see it being assigned to only me.

**Comment by mbilalamjad** [comment]
> @mbilalamjad Bilal Amjad FTE @prjelesi Predrag Jelesijevic FTE Can you please add Divyadeep [ didayal-msft ] as the co-owner ? I have mentioned this in the module proposal but I see it being assigned to only me.

Will let @prjelesi advise on this request.

**Comment by prjelesi** [comment]
@Poven795909 sure, i can update index page.

**Comment by Poven795909** [comment]
Module completed .. currently working on fixing certain issues identified. ETA for Module Publish is end of April.

**Comment by Poven795909** [comment]
Fixing last minute issues identified . New ETA for publish is May end.

**Comment by Poven795909** [comment]
The AVM Review of this module has been completed and the module has been published to the registry. Requesting AVM team to update this module proposal and module index accordingly.
https://registry.terraform.io/modules/Azure/avm-res-cdn-profile/azurerm/latest
