### ISSUE TITLE
[Module Proposal]: `avm-res-network-publicipaddress` (tf)

### ISSUE THREAD

**Issue by prjelesi** [Azure/Azure-Verified-Modules#256]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-network-publicipaddress

### Module Details

AM module for Azure public IP

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

prjelesi

**Comment by prjelesi** [comment]
terraform-azurerm-avm-res-network-publicipaddress,
https://registry.terraform.io/modules/Azure/avm-res-network-publicipaddress/azurerm/latest,
46d3xgtf.res.network-publicip,
@azure/avm-res-network-publicipaddress-module-owners-tf,
@azure/avm-res-network-publicipaddress-module-contributors-tf,

**Comment by prjelesi** [comment]
terraform-azurerm-avm-res-network-publicipaddress
46d3xgtf.res.network-publicip
@azure/avm-res-network-publicipaddress-module-owners-tf
@azure/avm-res-network-publicipaddress-module-contributors-tf

**Comment by mbilalamjad** [comment]
Hi @prjelesi,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

<br>

> **NOTE**:
>
> - This Module Proposal issue **MUST remain open** until the module is fully developed, tested and published to the relevant registry. **Do NOT close** the issue before the successful publication is confirmed!
> - Once the module is fully developed, tested and published to the relevant registry, and the Module Proposal issue was closed, it **MUST remain closed**.

**Comment by prjelesi** [comment]
Development in progres.

**Comment by prjelesi** [comment]
@mbilalamjad module is published

https://registry.terraform.io/modules/Azure/avm-res-network-publicipaddress/azurerm/latest

**Comment by mbilalamjad** [comment]
Thank you so much @prjelesi  for your contribution

Closing as module has been published to terraform registry below
https://registry.terraform.io/modules/Azure/avm-res-network-publicipaddress/azurerm/latest

Further discussion on this module including issues & PRs to take please on its repo below
https://github.com/Azure/terraform-azurerm-avm-res-network-publicipaddress
