### ISSUE TITLE
[Orphaned Module]: `avm/res/batch/batch-account`

### ISSUE THREAD

**Issue by matebarabas** [Azure/Azure-Verified-Modules#264]
### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/batch/batch-account

### Module Details

This module was migrated from CARML without an owner identified.

### Do you want to be the new owner of this module?

No

**Comment by didayal-msft** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by matebarabas** [comment]
Hi @didayal-msft,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

<br>

> **NOTE**:
>
> - This Orphaned Module issue **MUST remain open** until the ownership is fully confirmed!
> - Once the Orphaned Module issue was closed, it **MUST remain closed**. If the module will subsequently become orphaned again, a new Orphaned Module issue must be opened.

**Comment by matebarabas** [comment]
Hi @didayal-msft,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

We just want to ask you to double check a few important things.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- You must be the owner of the GitHub teams defined in the `ModuleOwnersGHTeam` and `ModuleContributorsGHTeam` columns
- Pleas check that your name has been updated in the module index page (this should happen shortly after you confirmed ownership).

You can now take ownership of this module and start improving it as needed! ✅ Happy coding! 🎉

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

<br>

> **NOTE**:
>
> - This Orphaned Module issue **MUST remain open** until the ownership is fully confirmed!
> - Once the Orphaned Module issue was closed, it **MUST remain closed**. If the module will subsequently become orphaned again, a new Orphaned Module issue must be opened.

**Comment by matebarabas** [comment]
@didayal-msft, can you please create the two GH teams for this module in the Azure organization:
- @Azure/avm-res-batch-batchaccount-module-owners-bicep
- @Azure/avm-res-batch-batchaccount-module-contributors-bicep

(Do not include `@Azure` in the name of the teams!).

Please respond to this message once you've created them both, and I'll help with the rights assignment. Thanks!

**Comment by matebarabas** [comment]
@didayal-msft, this is just a gentle reminder. :) Please let me know once you created the above teams, as I would then need to add them to the right parent teams, which then will need to be approved by you. Thanks!

**Comment by didayal-msft** [comment]
@matebarabas  I have created the 2 teams.

**Comment by matebarabas** [comment]
Teams added to their parents. Closing this issue.
