### ISSUE TITLE
[Module Proposal]: `avm-res-dbforpostgresql-flexibleserver` (tf)

### ISSUE THREAD

**Issue by timchapman** [Azure/Azure-Verified-Modules#273]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-dbforpostgresql-flexibleserver

### Module Details

Module for deploying an Azure PostgreSQL Flexible Server

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

timchapman

**Comment by mbilalamjad** [comment]
Hi @timchapman,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

<br>

> **NOTE**:
>
> - This Module Proposal issue **MUST remain open** until the module is fully developed, tested and published to the relevant registry. **Do NOT close** the issue before the successful publication is confirmed!
> - Once the module is fully developed, tested and published to the relevant registry, and the Module Proposal issue was closed, it **MUST remain closed**.

**Comment by mbilalamjad** [comment]
@timchapman  please note that I've updated the name per the following spec, hope that makes sense
https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-rmnfr1---category-naming---module-naming

**Comment by timchapman** [comment]
> Hi @timchapman,
> 
> Thanks for requesting/proposing to be an AVM module owner!
> 
> We just want to confirm **you agree to the below pages** that define what module ownership means:
> 
> * [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
> * [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
> * [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)
> 
> Any questions or clarifications needed, let us know!
> 
> If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):
> 
> "I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"
> 
> Thanks,
> 
> The AVM Core Team
> 
> #RR
> 
> 
> > **NOTE**:
> > 
> > * This Module Proposal issue **MUST remain open** until the module is fully developed, tested and published to the relevant registry. **Do NOT close** the issue before the successful publication is confirmed!
> > * Once the module is fully developed, tested and published to the relevant registry, and the Module Proposal issue was closed, it **MUST remain closed**.

I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by mbilalamjad** [comment]
Hi @timchapman,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

We just want to ask you to double check a few important things and take the next steps before you start the development.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - to name your module
  - `TelemetryIdPrefix` - to be used in your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repository name and folder path are defined in `RepoURL`
  - Create the GitHub teams defined in the `ModuleOwnersGHTeam` and `ModuleContributorsGHTeam` columns and grant them permissions as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
    - In case of a Bicep module, **please let the AVM core team know** when you created these teams, and we'll help you with assigning the necessary permissions as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#grant-permissions---bicep).
    - In case of a Terraform module, follow the instructions [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#grant-permissions---terraform) and assign the necessary permissions.

Grant the right level of permissions for  the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published!** Please include a link pointing to your PR if available. 🙏

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

<br>

> **NOTE**:
>
> - This Module Proposal issue **MUST remain open** until the module is fully developed, tested and published to the relevant registry. **Do NOT close** the issue before the successful publication is confirmed!
> - Once the module is fully developed, tested and published to the relevant registry, and the Module Proposal issue was closed, it **MUST remain closed**.

**Comment by mbilalamjad** [comment]
Reached out to @timchapman offline, this proposal will be updated accordingly here based on his input.

**Comment by mbilalamjad** [comment]
Reached out to @timchapman offline to check-in on any updates or support needed, he or I will update accordingly.

**Comment by v-xuto** [comment]
Requested to issue: https://github.com/Azure/Azure-Verified-Modules/issues/261
CC: @jongio

**Comment by v-xuto** [comment]
@timchapman - Do you have an ETA for this?

**Comment by kewalaka** [comment]
https://github.com/kewalaka/terraform-azurerm-avm-res-dbforpostgresql-flexibleserver

this covers the server & the database resources, needs a little love to add things like the entra admin & firewall rules children.

I'll probably get to it at some point, but anyone reading this - help much appreciated.

**Comment by v-xuto** [comment]
@timchapman - Do you have an ETA for this?

**Comment by marcingastol** [comment]
@kewalaka @timchapman  I'd like to volunteer to contribute to this module. Let me know what should be my next steps? thanks.

**Comment by alefteris** [comment]
@mbilalamjad Is a process missing for reassigning a module to a different person, when the original person is not responding?

It's been almost a year since the original person @timchapman accepted to be the owner of the module and since then, there as not been a single reply from them (at least publicly here, not sure if you communicate internally at MS).

Since then, two different people expressed interest to take ownership of the module (@marcingastol, @cmaclaughlin) and also another person (@kewalaka) published an initial implementation of the module already, but with no way to progress the module in a road to be published officially, since it's being blocked by the original module owner assignment.

The resource that this module implements is, by my impression at least, a very used one and also it's blocking the azd migration to avm, as I understand.

**Comment by kewalaka** [comment]
happy to assist here, but as I'm not a MSFT'er I am not allowed to be the owner.

It's been a little while since I touched my implementation but it shouldn't take much to align to changes in spec.

**Comment by mbilalamjad** [comment]
Hey everyone, I've had a discussion with the original module owner and I'm taking over in the interim to help get this module out. I've reviewed what @kewalaka has shared above and added my contribution on top of it to align it with all updated AVM specs and checks, please review and share feedback in terms of issues & PRs on the below repo
https://github.com/Azure/terraform-azurerm-avm-res-dbforpostgresql-flexibleserver
CC: @kewalaka, @marcingastol, @cmaclaughlin
