### ISSUE TITLE
[Module Proposal]: `avm-res-dbformysql-flexibleserver` (tf)

### ISSUE THREAD

**Issue by timchapman** [Azure/Azure-Verified-Modules#274]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-dbformysql-flexibleserver

### Module Details

Module for deploying MySQL Flexible Server

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

timchapman

**Comment by mbilalamjad** [comment]
Hi @timchapman,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

<br>

> **NOTE**:
>
> - This Module Proposal issue **MUST remain open** until the module is fully developed, tested and published to the relevant registry. **Do NOT close** the issue before the successful publication is confirmed!
> - Once the module is fully developed, tested and published to the relevant registry, and the Module Proposal issue was closed, it **MUST remain closed**.

**Comment by mbilalamjad** [comment]
@timchapman please note that I've updated the name per the following spec, hope that makes sense
https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-rmnfr1---category-naming---module-naming

**Comment by timchapman** [comment]
> Hi @timchapman,
> 
> Thanks for requesting/proposing to be an AVM module owner!
> 
> We just want to confirm **you agree to the below pages** that define what module ownership means:
> 
> * [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
> * [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
> * [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)
> 
> Any questions or clarifications needed, let us know!
> 
> If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):
> 
> "I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"
> 
> Thanks,
> 
> The AVM Core Team
> 
> #RR
> 
> 
> > **NOTE**:
> > 
> > * This Module Proposal issue **MUST remain open** until the module is fully developed, tested and published to the relevant registry. **Do NOT close** the issue before the successful publication is confirmed!
> > * Once the module is fully developed, tested and published to the relevant registry, and the Module Proposal issue was closed, it **MUST remain closed**.

I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by mbilalamjad** [comment]
Hi @timchapman,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

We just want to ask you to double check a few important things and take the next steps before you start the development.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - to name your module
  - `TelemetryIdPrefix` - to be used in your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repository name and folder path are defined in `RepoURL`
  - Create the GitHub teams defined in the `ModuleOwnersGHTeam` and `ModuleContributorsGHTeam` columns and grant them permissions as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
    - In case of a Bicep module, **please let the AVM core team know** when you created these teams, and we'll help you with assigning the necessary permissions as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#grant-permissions---bicep).
    - In case of a Terraform module, follow the instructions [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#grant-permissions---terraform) and assign the necessary permissions.

Grant the right level of permissions for  the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published!** Please include a link pointing to your PR if available. 🙏

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

<br>

> **NOTE**:
>
> - This Module Proposal issue **MUST remain open** until the module is fully developed, tested and published to the relevant registry. **Do NOT close** the issue before the successful publication is confirmed!
> - Once the module is fully developed, tested and published to the relevant registry, and the Module Proposal issue was closed, it **MUST remain closed**.

**Comment by mbilalamjad** [comment]
Reached out to @timchapman offline, this proposal will be updated accordingly here based on his input.

**Comment by suchi271** [comment]
Hi, 

Would like to contribute to this module. What are the next steps?

**Comment by kewalaka** [comment]
hi @suchi271 - one of my colleagues has also offered help and we've got a baseline started, pending feedback from Tim on his current progress.  If you want to contact me (email on my github profile) - happy to team up and show you where we are up to.

**Comment by kewalaka** [comment]
@charliekw411 has made excellent progress towards an AVM-style module here:

https://github.com/charliekw411/terraform-azurerm-avm-res-dbformysql-flexibleserver/

This has full coverage of the parent mysql server resource, & private endpoints.

On the feature branch there's the database child resource:

https://github.com/charliekw411/terraform-azurerm-avm-res-dbformysql-flexibleserver/tree/feat/sql-server-database-resource

The main branch, and the above feature branch, is passing all E2E tests, including linting & docs.

![image](https://github.com/Azure/Azure-Verified-Modules/assets/3146590/78040281-e321-4fd4-8ce6-caf2796d5f32)

Suggested next steps:

- @timchapman  It would be great if the Azure org repo can be created.  What I've done with other Microsoft'ers is to create a 'dev' branch - as that allows us to contribute without breaking the login mechanism for the E2E tests.  I can go into details on this if you like.

- There's more "child resources" to be added, will create some issues for these & we'll work on them next week.  @suchi271  happy if you would like to contribute to these

- We haven't yet run the governance tool 'grept' across it.

**Comment by suchi271** [comment]
Happy to contribute to the child resources required here @kewalaka. Meanwhile, I'll go through the repo structure and code to get myself familiar with the environment. Will reach out to you or @charliekw411 if I have doubts. If the issues are already created, feel free to mention me under those for me to start working.

Thanks!

**Comment by kewalaka** [comment]
hi @suchi271 - great - more the merrier :)  Yes I've replied on the issue you've mentioned you're interested in.

**Comment by segraef** [comment]
@mbilalamjad, cross-check, do we have an owner and I can help with creating the repo to enable @kewalaka, correct?

**Comment by mbilalamjad** [comment]
Reached out to @timchapman offline to check-in on any updates or support needed, he or I will update accordingly

**Comment by kewalaka** [comment]
@mbilalamjad -

@segraef has offered to help create the repo - can you confirm he can proceed please?  This is currently the blocker.   

@charliekw411 has done much of the work already as advised above, and it is now close to feature complete from the perspective of module & child module coverage.

**Comment by kewalaka** [comment]
> @mbilalamjad, cross-check, do we have an owner and I can help with creating the repo to enable @kewalaka, correct?

@mbilalamjad would you be able to provide an update to @segraef please?  Is there anything I can help to do to help with this process?

**Comment by kewalaka** [comment]
@timchapman wondering if you can create the repo please?

The name would be ``terraform-azurerm-avm-res-dbformysql-flexibleserver``

If you can help with the set up, we have code written with the AVM specification in mind ready to post.

many thanks!

**Comment by prjelesi** [comment]
@kewalaka @segraef Any progress?

**Comment by kewalaka** [comment]
@prjelesi we have something in an external repo close to code complete, waiting on the repo from the module owner @timchapman, I'm unclear if @segraef can assist with this

**Comment by prjelesi** [comment]
@kewalaka so i tag you, i wanted to tag @timchapman to get update.

**Comment by segraef** [comment]
@mbilalamjad what's the current state for this module and its repo creation? I didn't proceed due to an internal blocker. If fine, either @prjelesi or me initiate the repo creation (if not initiated already).

**Comment by prjelesi** [comment]
@kewalaka sorry for delays. We will have everything clear by Friday this week.

**Comment by charliekw411** [comment]
@prjelesi @segraef @timchapman 

Can we confirm who is taking ownership for creating the repo please. Am keen to get external contribution underway. 

TIA

**Comment by panwar28** [comment]
@mbilalamjad I can be co-owner on this module along with you. Please let me know if I can be a co-author or contributor of this module.
