### ISSUE TITLE
[Module Proposal]: `avm/res/api-management/service`

### ISSUE THREAD

**Issue by matebarabas** [Azure/Azure-Verified-Modules#292]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/api-management/service

### Module Details

- To be migrated from CARML: https://github.com/Azure/ResourceModules/tree/main/modules/api-management/service
- Requested by the AZD team: #261 
- Needs module owner.
CC: @jongio

### Do you want to be the owner of this module?

No

**Comment by krbar** [comment]
@matebarabas @jeanchg Please assign this issue to me, I will attempt to migrate this module (as orphaned).

**Comment by krbar** [comment]
@matebarabas Module has been migrated from CARML and merged into BRM: https://github.com/Azure/bicep-registry-modules/pull/713

**Comment by matebarabas** [comment]
- [x] Module published.
- [x] GitHub teams are available and assigned to their parents.
- [x] `CODEOWNERS` file updated.
 
Thank you for your work @krbar! I'm closing this issue now.

Since this module was migrated from CARML without an owner, an orphaned module request was also created: https://github.com/Azure/Azure-Verified-Modules/issues/418
