### ISSUE TITLE
[Module Proposal]: `avm/res/app/managed-environment`

### ISSUE THREAD

**Issue by matebarabas** [Azure/Azure-Verified-Modules#296]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/app/managed-environment

### Module Details

- To be migrated from CARML: https://github.com/Azure/ResourceModules/tree/main/modules/app/managed-environment
- Requested by the AZD team: #261 
- Needs module owner.
CC: @jongio 

### Do you want to be the owner of this module?

No

**Comment by arnoldna** [comment]
Working on the migration of the module from CARML to AVM. This module will need a long term owner.

**Comment by matebarabas** [comment]
> @matebarabas - Created new teams

I've just requested the -owners- team to be added to the -technical-reviewers- team. Please approve.

**Comment by arnoldna** [comment]
@matebarabas - Done

**Comment by matebarabas** [comment]
- [x] PR merged; Module published. https://github.com/Azure/bicep-registry-modules/pull/737
- [ ] GitHub teams are available and assigned to their parents. --> @arnoldna, can you please create the required GH teams and assign them to their corresponding parents? Thank you!
- [x] `CODEOWNERS` file updated.
 
Since this module was migrated from CARML without an owner, an orphaned module request was also created: https://github.com/Azure/Azure-Verified-Modules/issues/472

**Comment by matebarabas** [comment]
- [x] GitHub teams are available and assigned to their parents. Thanks @arnoldna!

I'm closing this issue now.
