### ISSUE TITLE
[Module Proposal]: `avm/res/load-test-service/load-test`

### ISSUE THREAD

**Issue by matebarabas** [Azure/Azure-Verified-Modules#299]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/load-test-service/load-test

### Module Details

- New module.
- Requested by the AZD team: #261 

CC: @jongio 

### Do you want to be the owner of this module?

No

### Module Owner's GitHub Username (handle)

sebassem

**Comment by PmeshramPM** [comment]
@matebarabas  - could you check the correct naming convention for this module? I was trying to replicate the same for Terraform and noticed this in the resource explorer - 

![Image](https://github.com/Azure/Azure-Verified-Modules/assets/41123792/ca39c54e-e1fc-468d-9b19-d2661afbc77c)

**Comment by sebassem** [comment]
@matebarabas I can own this one

**Comment by matebarabas** [comment]
Hi @sebassem,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

<br>

> **NOTE**:
>
> - This Module Proposal issue **MUST remain open** until the module is fully developed, tested and published to the relevant registry. **Do NOT close** the issue before the successful publication is confirmed!
> - Once the module is fully developed, tested and published to the relevant registry, and the Module Proposal issue was closed, it **MUST remain closed**.

**Comment by matebarabas** [comment]
@sebassem, can you please respond by repeating the above quoted text, so that we can move on with the standard triage process. Thank you!

**Comment by sebassem** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER



Seif Bassem
Sr Cloud Solution Architect - Azure Core
Tech strategy team
Office: +20235315608
***@***.******@***.***>

[Microsoft Logo]

**Comment by matebarabas** [comment]
Hi @sebassem,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

We just want to ask you to double check a few important things and take the next steps before you start the development.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - to name your module
  - `TelemetryIdPrefix` - to be used in your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repository name and folder path are defined in `RepoURL`
  - Create the GitHub teams defined in the `ModuleOwnersGHTeam` and `ModuleContributorsGHTeam` columns and grant them permissions as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
    - In case of a Bicep module, **please let the AVM core team know** when you created these teams, and we'll help you with assigning the necessary permissions as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#grant-permissions---bicep).
    - In case of a Terraform module, follow the instructions [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#grant-permissions---terraform) and assign the necessary permissions.

Grant the right level of permissions for  the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published!** Please include a link pointing to your PR if available. 🙏

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

<br>

> **NOTE**:
>
> - This Module Proposal issue **MUST remain open** until the module is fully developed, tested and published to the relevant registry. **Do NOT close** the issue before the successful publication is confirmed!
> - Once the module is fully developed, tested and published to the relevant registry, and the Module Proposal issue was closed, it **MUST remain closed**.

**Comment by sebassem** [comment]
Currently blocked by issue in resource provider. Submitted an issue and contacted the service PG who are currently investigating. [Issue reference](https://github.com/Azure/bicep-types-az/issues/1987)

**Comment by matebarabas** [comment]
Hi @sebassem, Happy New Year! I hope you had a great holiday season and had a chance to recharge! 😊

I just would like to check back on this issue and ask if you have any updates. Once the external dependency is resolved, could you please share your expected timeline on publishing this module? 

Thank you!

CC: @jeanchg

**Comment by sebassem** [comment]
> Hi @sebassem, Happy New Year! I hope you had a great holiday season and had a chance to recharge! 😊
> 
> I just would like to check back on this issue and ask if you have any updates. Once the external dependency is resolved, could you please share your expected timeline on publishing this module?
> 
> Thank you!
> 
> CC: @jeanchg

Hello Mate, the issue is still open https://github.com/Azure/bicep-types-az/issues/1987#issuecomment-1879925768

**Comment by matebarabas** [comment]
Update: the [bug](https://github.com/Azure/bicep-types-az/issues/1987) blocking the development of this issue "_should be fixed by the end of the month_".

**Comment by sebassem** [comment]
Quick update: Reached out to the engineer working on this issue from PG. The work has been done but there is a partner dependency that is pending to close this issue so we can continue working on this module

**Comment by sebassem** [comment]
Update: Fix pushed, will take ~ 2 weeks to propagate to canary where I can start testing

**Comment by sebassem** [comment]
Fix has been pushed, here is the PR for the new module: https://github.com/Azure/bicep-registry-modules/pull/1613

**Comment by matebarabas** [comment]
- [x] Module published.
- [x] GitHub teams are available and assigned to their parents.
- [x] `CODEOWNERS` file updated.
 
Thank you for your work @sebassem! I'm closing this issue now.
