### ISSUE TITLE
[Question/Feedback]:  Inconsistency between CodeOwners guidance and team definitions

### ISSUE THREAD

**Issue by jchancellor-ms** [Azure/Azure-Verified-Modules#308]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

The CODEOWNERS guidance and Terraform repo template assign permissions using the `avm-core-team-technical` github group for ownership of the CODEOWNERS and policies files.  However, the spec definition requires assignment of the `avm-core-team` group.  

I believe we need to update spec guidance to ensure permissions are configured on the repo for both avm-core-team and avm-core-team-technical.

**Comment by mbilalamjad** [comment]
Thanks @jchancellor-ms for the feedback, have raised this with the AVM Core Team, will update next week on the resolution

**Comment by jchancellor-ms** [comment]
@mbilalamjad - Updating this thread with the latest discovery.  The spec requires the CODEOWNERS file to include a line for the  -module-owners- group to own all of the code.  In modules where the code-owners group contains one member, PR's can't be approved without adding another team-member to the code owners group due to the restriction that a submitter can't approve their own code.  Recommend we look at allowing core-team-technical to also be an owner of the full repo content as a fallback for single owner repos.

**Comment by mbilalamjad** [comment]
Thanks @jchancellor-ms for the update, will discuss with the team and get back to you accordingly this week

**Comment by mbilalamjad** [comment]
@matt-FFFFFF appreciate in input on this one

**Comment by matt-FFFFFF** [comment]
Agreed to remove the wildcard line requiring module owner team to approve PRs. This doesn't work for single person teams

**Comment by matt-FFFFFF** [comment]
@mbilalamjad think this can be closed now?

**Comment by matt-FFFFFF** [comment]
The spec has been updated - closing
