### ISSUE TITLE
[Module Proposal]: `avm-res-authorization-roleassignment` (tf)

### ISSUE THREAD

**Issue by jaredfholgate** [Azure/Azure-Verified-Modules#311]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-authorization-roleassignment
(terraform-azurerm-avm-res-authorization-roleassignment)
Note: Chose `azurerm` here, but will also need to use the azuread provider.

### Module Details

The module would be able to create role assignments for all service principal types and groups at all layers of the ARM hierarchy and Entra ID roles. It could optionally just output a map of unique assignments that can be used in other tools.

The module would augment other modules, such as subscription vending providing a convenient way to map human readable names to the ids required by the API.

It could support yaml or json as input as well as a map variable for simple use cases.

It will support the following types of identity:

- Entra ID User 
- Entra ID App Registration
- System Assigned Managed Identity
- User Assigned Managed Identity
- Entra ID Group

It will accept either different keys for each as a convenience and map them to data sources:

- User: SPN, ObjectID, mail
- Group: Name, ObjectID
- System Assigned Managed Identity: Name, ObjectID
- User Assigned Managed Identity: Name, ObjectID
- Entra ID Group: Name, ObjectID

It will validate that they exist / the creds being used has access to them.

It will accept a data structure (TBD) of:

- Management groups
- Subscriptions
- Resource groups
- Resources
- Entra ID role flag

Each will have one or many roles (built in or custom) associated with it.

It would optionally validate that each of the resources and role assignments exist prior to attempting to apply the role assignments.

It would create a distinct set of roles assignments.

It would then optionally create the roll assignments or just output a set for use in other modules.

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

jaredfholgate

**Comment by PmeshramPM** [comment]
@jaredfholgate  - FYI -I have updated the module name and github repo name to reflect the correct naming ( resources are singular ) based on specs.

**Comment by mbilalamjad** [comment]
Hi @jaredfholgate,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

<br>

> **NOTE**:
>
> - This Module Proposal issue **MUST remain open** until the module is fully developed, tested and published to the relevant registry. **Do NOT close** the issue before the successful publication is confirmed!
> - Once the module is fully developed, tested and published to the relevant registry, and the Module Proposal issue was closed, it **MUST remain closed**.

**Comment by jaredfholgate** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by mbilalamjad** [comment]
Hi @jaredfholgate,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

We just want to ask you to double check a few important things and take the next steps before you start the development.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - to name your module
  - `TelemetryIdPrefix` - to be used in your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repository name and folder path are defined in `RepoURL`
  - Create the GitHub teams defined in the `ModuleOwnersGHTeam` and `ModuleContributorsGHTeam` columns and grant them permissions as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
    - In case of a Bicep module, **please let the AVM core team know** when you created these teams, and we'll help you with assigning the necessary permissions as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#grant-permissions---bicep).
    - In case of a Terraform module, follow the instructions [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#grant-permissions---terraform) and assign the necessary permissions.

Grant the right level of permissions for  the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published!** Please include a link pointing to your PR if available. 🙏

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

<br>

> **NOTE**:
>
> - This Module Proposal issue **MUST remain open** until the module is fully developed, tested and published to the relevant registry. **Do NOT close** the issue before the successful publication is confirmed!
> - Once the module is fully developed, tested and published to the relevant registry, and the Module Proposal issue was closed, it **MUST remain closed**.

**Comment by jaredfholgate** [comment]
> Hi @jaredfholgate Jared Holgate FTE,
> 
> Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!
> 
> We just want to ask you to double check a few important things and take the next steps before you start the development.
> 
> **Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:
> 
> * For your module:
>   
>   * `ModuleName` - to name your module
>   * `TelemetryIdPrefix` - to be used in your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
> * For your module's repository:
>   
>   * Repository name and folder path are defined in `RepoURL`
>   * Create the GitHub teams defined in the `ModuleOwnersGHTeam` and `ModuleContributorsGHTeam` columns and grant them permissions as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
>     
>     * In case of a Bicep module, **please let the AVM core team know** when you created these teams, and we'll help you with assigning the necessary permissions as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#grant-permissions---bicep).
>     * In case of a Terraform module, follow the instructions [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#grant-permissions---terraform) and assign the necessary permissions.
> 
> Grant the right level of permissions for the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).
> 
> You can now start the development of this module! ✅ Happy coding! 🎉
> 
> **Please respond to this comment and request a review from the AVM core team once your module is ready to be published!** Please include a link pointing to your PR if available. 🙏
> 
> Any further questions or clarifications needed, let us know!
> 
> Thanks,
> 
> The AVM Core Team
> 
> 
> > **NOTE**:
> > 
> > * This Module Proposal issue **MUST remain open** until the module is fully developed, tested and published to the relevant registry. **Do NOT close** the issue before the successful publication is confirmed!
> > * Once the module is fully developed, tested and published to the relevant registry, and the Module Proposal issue was closed, it **MUST remain closed**.

Ready for review.

PRs:

- https://github.com/Azure/terraform-azurerm-avm-res-authorization-roleassignment/pull/3
- https://github.com/Azure/terraform-azurerm-avm-res-authorization-roleassignment/pull/2

**Comment by jaredfholgate** [comment]
@mbilalamjad I may have misunderstood the message. If you don't want me to request the changes until the code is ready, let me know and I will cancel the PRs.

**Comment by jaredfholgate** [comment]
> @jaredfholgate Jared Holgate FTE, this issue has not had any activity in the last **3 weeks**. Please feel free to reach out to the AVM core team should you have any questions or need any help with the development of this module.

Work is in progress, I just have to fit it around my work and family commitments. I am probably about 5 / 6 hours away from v0.0.1 and a PR.

**Comment by jaredfholgate** [comment]
@mbilalamjad This [PR](https://github.com/Azure/terraform-azurerm-avm-res-authorization-roleassignment/pull/4) is now ready for review. E2E tests are passing. The lint check is failing due to an [external problem](https://github.com/Azure/terraform-azurerm-avm-template/issues/56) and will be re-run once that is resolved.

**Comment by jaredfholgate** [comment]
> @jaredfholgate Jared Holgate FTE, this issue has not had any activity in the last **3 weeks**. Please feel free to reach out to the AVM core team should you have any questions or need any help with the development of this module.

I am still waiting on a review. Code is complete for v1.0.

**Comment by mbilalamjad** [comment]
@jchancellor-ms just checking in to ask if you got the review Jared's module

**Comment by jaredfholgate** [comment]
@mbilalamjad and @matt-FFFFFF. @jchancellor-ms has kindly reviewed and approved the PR. I am just waiting on the core team to approve so I can merge and release. PR is here: https://github.com/Azure/terraform-azurerm-avm-res-authorization-roleassignment/pull/4. Thanks

**Comment by jaredfholgate** [comment]
> @mbilalamjad and @matt-FFFFFF. @jchancellor-ms has kindly reviewed and approved the PR. I am just waiting on the core team to approve so I can merge and release. PR is here: [Azure/terraform-azurerm-avm-res-authorization-roleassignment#4](https://github.com/Azure/terraform-azurerm-avm-res-authorization-roleassignment/pull/4). Thanks

Module published: https://registry.terraform.io/modules/Azure/avm-res-authorization-roleassignment/azurerm

Thanks for all your help.

**Comment by mbilalamjad** [comment]
Thank you so much @jaredfholgate for your contribution

Closing as module has been published to terraform registry below
https://registry.terraform.io/modules/Azure/avm-res-authorization-roleassignment/azurerm

Further discussion on this module including issues & PRs to take please on its repo below
https://github.com/Azure/terraform-azurerm-avm-res-authorization-roleassignment
