### ISSUE TITLE
[Question/Feedback]: make the location optional but still configurable

### ISSUE THREAD

**Issue by kewalaka** [Azure/Azure-Verified-Modules#313]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

I'd like to propose that the location becomes an optional parameter, which if not specified would inherit from the resource group.  This reduces that number of parameters that need to be supplied for most resources, and is a common default pattern. 

It could be done something like this:

```terraform
# in locals.tf
locals {
  location = var.location != null ? var.location : data.azurerm_resource_group.rg.location
}

# in main.tf
data "azurerm_resource_group" "rg" {
  name = var.resource_group_name
}

# variables.tf
variable "location" {
  type        = string
  default     = null
  description = <<DESCRIPTION
Azure region where the resource should be deployed.  
If null, the location will be inferred from the resource group location.
DESCRIPTION
}
```

It would also need an update to the standard private_endpoints variable declaration as that references `var.location` (to switch it to `local.location`)

**Comment by mbilalamjad** [comment]
@kewalaka thanks for the feedback, we have this documented here below, is that sufficient and addresses your feedback or is there something additional required
https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-rmnfr2---category-inputs---parametervariable-naming

**Comment by kewalaka** [comment]
hi @mbilalamjad  - agreed this is the right area.  I do find this a little difficult to read, quoting current state;

>(if supported by the resource and not a global resource, then use Resource Group location, if resource supports Resource Groups, otherwise no default)

what about the following, which breaks up the statements & also aligns with my suggestion:

> If the resource is a global resource then inherit from the resource group by default, allowing this to be optionally overridden.
> If the resource is not a global resource, then use the resource group location.
> If the resource does not support resource groups, then do not set a default.

If we take Key Vault as an example - I would suggest the default set of parameters should not need to include the location & tenant_id, they should be set to the resource group location & current tenant by default, again, allowing them to be overridden (same pattern as above).

Aim is to reduce the number of parameters that have to be specified, and align to common patterns, which seems the general aim for the "default" use case.

**Comment by mbilalamjad** [comment]
@matt-FFFFFF, @jtracey93 guys appreciate your comments on the above, makes sense to me, the current verbage of the spec is a bit jumbled and could be improved based on what @kewalaka has shared, if it makes sense to you too than I'll update the spec accordingly

**Comment by matt-FFFFFF** [comment]
The data source needs a count making it conditional on location being null

**Comment by matt-FFFFFF** [comment]
As for the spec. If the resource is global then the location is global...

So:

> Use the resource group location but allow override using the location parameter/variable.
If the resource does not support resource groups but requires a location, then require a location input.

**Comment by mbilalamjad** [comment]
Given other priorities, we're marking this as long term but keeping it open, will circle back at an appropriate time.

**Comment by matt-FFFFFF** [comment]
Sure of course!

consider this:

```terraform
# we are using a terraform_data resource here but a data source would have the same issue
resource "terraform_data" "dependency" {
  input = {
    something_dependant_resources_care_about      = "uksouth"
    something_dependant_resources_dont_care_about = "baz" # this used to be "bar"
  }
}

# Note how change of any input to the terraform_data resource will result in the RG getting replaced
# even if it's not something that the resource depends on.
resource "azurerm_resource_group" "evil_data_source_issue" {
  name     = "evil_data_source_issue"
  location = terraform_data.dependency.output.something_dependant_resources_care_about
}
```

Apply this then change `terraform_data.dependency.input.something_dependant_resources_dont_care_about`.

You will get:

```text
Terraform will perform the following actions:

  # azurerm_resource_group.evil_data_source_issue must be replaced
-/+ resource "azurerm_resource_group" "evil_data_source_issue" {
      ~ id       = "/subscriptions/dabf9763-fbbb-435c-921b-61f5ed59b3d1/resourceGroups/evil_data_source_issue" -> (known after apply)
      ~ location = "uksouth" # forces replacement -> (known after apply) # forces replacement
        name     = "evil_data_source_issue"
      - tags     = {} -> null
    }
```

This is a simplified example but one that means we should be very careful of adding extra dependencies when we don't need to.

Overall I believe this should be done carefully outside of a resource module. There are likely to be multiple resources in a RG and each resource module having its own data source is adding unnecessary complexity.

**Comment by matebarabas** [comment]
@matt-FFFFFF, the AVM issue triage team is reviewing issues tagged as long-term. As part of this effort, we'd like to double check with you if this issue can be closed now? Thank you!

**Comment by matt-FFFFFF** [comment]
We have decided against this suggestion after realising there can be issues long term with data sources!
