### ISSUE TITLE
[Orphaned Module]: `avm/res/sql/server`

### ISSUE THREAD

**Issue by matebarabas** [Azure/Azure-Verified-Modules#322]
### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/sql/server

### Module Details

This module was migrated from CARML without an owner. 

- Module proposal: https://github.com/Azure/Azure-Verified-Modules/issues/295
- Initial PR: https://github.com/Azure/bicep-registry-modules/pull/637

### Do you want to be the new owner of this module?

No

**Comment by matebarabas** [comment]
This module was migrated from CARML by @krbar without an owner. Note: when someone volunteers to be the owner of this module, please reach out to @krbar to for changing the ownership of the existing GitHub teams as well.

**Comment by bryansan-msft** [comment]
Hello @matebarabas and @krbar, I would like to volunteer to be the owner of this module.

**Comment by bryansan-msft** [comment]
It seems @mbilalamjad is already working on this in #442

**Comment by matebarabas** [comment]
Hi @bryansan-msft,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by bryansan-msft** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by matebarabas** [comment]
Hi @bryansan-msft,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

We just want to ask you to double check a few important things.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- You must be the owner of the GitHub teams as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
- Please check that your name has been updated in the module index page (this should happen shortly after you confirmed ownership).

You can now take ownership of this module and start improving it as needed! ✅ Happy coding! 🎉

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by matebarabas** [comment]
@bryansan-msft, since this module has been migrated by @krbar (Kris Baranek), he's created the required GH teams. Please work with him to take ownership over these teams and let me know in a comment here when it happened. Thanks!

**Comment by krbar** [comment]
@matebarabas The GH team are transferred.

**Comment by matebarabas** [comment]
Thanks for confirming, I'm closing the issue now.

**Comment by drkclw** [comment]
I'd like to become a contributor to this module.

**Comment by matebarabas** [comment]
Hi @drkclw, thank you for volunteering to support this module's maintenance! Please note that this module is currently orphaned, with the related issue available here: https://github.com/Azure/Azure-Verified-Modules/issues/1141 - please use this for all following communications.

As this module is currently being handed over to a new owner (@emichellecarter), I need to ask for your patience, until the administration of the transfer is fully complete. Then, you'll be able to work together with the new owner on your contributions.

Thank you!
