### ISSUE TITLE
[Orphaned Module]: `avm/res/db-for-postgre-sql/flexible-server`

### ISSUE THREAD

**Issue by matebarabas** [Azure/Azure-Verified-Modules#324]
### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/db-for-postgre-sql/flexible-server

### Module Details

This module was migrated from CARML without an owner.
- Module proposal: https://github.com/Azure/Azure-Verified-Modules/issues/294
- PR: https://github.com/Azure/bicep-registry-modules/pull/664

### Do you want to be the new owner of this module?

No

**Comment by matebarabas** [comment]
This module was migrated from CARML by @krbar without an owner. Note: when someone volunteers to be the owner of this module, please reach out to @krbar to for changing the ownership of the existing GitHub teams as well.

**Comment by joaria** [comment]
I can take this one, I'm a PostgreSQL Insider

**Comment by matebarabas** [comment]
Hi @joaria,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by matebarabas** [comment]
Hi @joaria,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

We just want to ask you to double check a few important things.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- You must be the owner of the GitHub teams as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
- Please check that your name has been updated in the module index page (this should happen shortly after you confirmed ownership).

You can now take ownership of this module and start improving it as needed! ✅ Happy coding! 🎉

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by matebarabas** [comment]
@joaria, since this module has been migrated by @krbar (Kris Baranek), he's created the required GH teams. Please work with him to take ownership over these teams **and let me know in a comment here when it happened**.
**Please also remove the `ORPHANED.md` file** from the [module's folder](https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/db-for-postgre-sql/flexible-server) and it's content from the `README.md`, by following the steps described in point 5 [here](https://azure.github.io/Azure-Verified-Modules/help-support/issue-triage/avm-issue-triage/#when-a-new-owner-is-identified) and let me know in a comment when this is done. Thanks!

**Comment by krbar** [comment]
@matebarabas I've created a Pull Request to unorphan the module: https://github.com/Azure/bicep-registry-modules/pull/1086

Regarding the Github Teams, @joaria is currently not a member of the Azure Organization, we will have a chat to change it and then I will comment here when completed.

**Comment by krbar** [comment]
@matebarabas The GH teams are transferred to @joaria

**Comment by matebarabas** [comment]
Thanks @krbar, I can see that the `ORPHANED.md` file is also removed and the `README.md` is updated. I'm closing this issue now; the transition to @joaria is complete.

**Comment by matebarabas** [comment]
Update:
From now on, the module owner will use the following GH handle instead: @josearper. Module index updated with this information.
