### ISSUE TITLE
[Question/Feedback]: 

### ISSUE THREAD

**Issue by JefferyMitchell** [Azure/Azure-Verified-Modules#33]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

On the module submission form consider changing "resource or pattern module" to "module classification". This more closely reflect the language in the shared and specific requirements for each and the language about them.  
 
![image](https://github.com/Azure/Azure-Verified-Modules/assets/8091766/ed0b9235-eab8-4ff5-a149-cf3e21f60214)

**Comment by jtracey93** [comment]
Good point will update now :)

**Comment by jtracey93** [comment]
Fixed 👍 
![image](https://github.com/Azure/Azure-Verified-Modules/assets/41163455/2506531a-c796-479d-a4ac-e0dccaa1a906)
