### ISSUE TITLE
[Module Proposal]: `avm-res-cognitiveservices-account` (tf)

### ISSUE THREAD

**Issue by PmeshramPM** [Azure/Azure-Verified-Modules#334]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-cognitiveservices-account

### Module Details

Requested by the AZD team: https://github.com/Azure/Azure-Verified-Modules/issues/261
Needs module owner.
CC: @jongio

### Do you want to be the owner of this module?

No

**Comment by mbilalamjad** [comment]
Closing this module proposal as duplicate and in favor of [this one](https://github.com/Azure/Azure-Verified-Modules/issues/571) raised by @lonegunmanb
CC: @PmeshramPM
