### ISSUE TITLE
[Module Proposal]: `avm-res-devcenter-devcenter` (tf)

### ISSUE THREAD

**Issue by PmeshramPM** [Azure/Azure-Verified-Modules#335]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-devcenter-devcenter

### Module Details

Requested by the AZD team: https://github.com/Azure/Azure-Verified-Modules/issues/261
Needs module owner.
CC: @jongio

### Do you want to be the owner of this module?

No

**Comment by kewalaka** [comment]
hi @mbilalamjad - a query on this - is a dev center project part of this resource or not?  It exists in the same resource provider but it is a different namespace, which makes me think it should be separate, but logically it feels like a child of a dev center?

The scoping rules for AVM are a little hazy for me 😅

**Comment by mbilalamjad** [comment]
> hi @mbilalamjad - a query on this - is a dev center project part of this resource or not? It exists in the same resource provider but it is a different namespace, which makes me think it should be separate, but logically it feels like a child of a dev center?
> 
> i.e. should we have a separate resource for `avm-res-devcenter-project` ?
> 
> & also for `avm-res-devcenter-networkconnection`
> 
> The scoping rules for AVM are a little hazy for me 😅

Great question @kewalaka, I believe there should be one for avm-res-devcenter-devcenter, one for avm-res-devcenter-project and one for avm-res-devcenter-networkconnection, then all three together can be used appropriately, let me know if that makes sense.

**Comment by v-xuto** [comment]
@PmeshramPM - Do you have an ETA for this?

**Comment by mbilalamjad** [comment]
> @mbilalamjad Bilal Amjad FTE - Do you have an ETA for this?

We are currently looking for a module owner.

**Comment by mbilalamjad** [comment]
> @mbilalamjad Any progress about this issue?

We are currently looking for a module owner to own and develop this module

**Comment by cshea-msft** [comment]
@mbilalamjad I can own this project!

**Comment by mbilalamjad** [comment]
> @mbilalamjad I can own this project!

Thanks Charles, Requesting @prjelesi to help here as he owns this triage stage.

**Comment by prjelesi** [comment]
Hi @cshea-msft 

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by cshea-msft** [comment]
> Hi @cshea-msft
> 
> Thanks for requesting/proposing to be an AVM module owner!
> 
> We just want to confirm **you agree to the below pages** that define what module ownership means:
> 
> * [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
> * [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
> * [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)
> 
> Any questions or clarifications needed, let us know!
> 
> If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):
> 
> "I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"
> 
> Thanks,
> 
> The AVM Core Team
> 
> #RR

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

**Comment by prjelesi** [comment]
@cshea-msft 

Hi @avm_module_owner,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

Before starting development, please ensure ALL the following requirements are met.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - for naming your module
  - `TelemetryIdPrefix` - for your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repo name and folder path are defined in `RepoURL`
  - Create GitHub teams for module owners and contributors and grant them permissions as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
  - Grant permissions for the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

Check if this module exists in the other IaC language. If so, collaborate with the other owner for consistency. 👍

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published! Please include a link pointing to your PR, once available. 🙏**

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by cshea-msft** [comment]
@prjelesi for this module should I include the other dev box resources in the root? or create those as sub modules?

![Image](https://github.com/user-attachments/assets/7e4db2e8-a16d-400e-9ba9-b76754e94dc7)

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/dev_center

**Comment by cshea-msft** [comment]
@prjelesi @mbilalamjad  any thoughts to my comment above?

**Comment by matebarabas** [comment]
@cshea-msft, here are my 2 cents:
- based on the [Azure resource reference](https://learn.microsoft.com/en-us/azure/templates/microsoft.devcenter/projects?pivots=deployment-language-terraform),

![Image](https://github.com/user-attachments/assets/748e76b7-a11d-4729-926a-b87a69cbe1cb)

 - the following items are member of the Microsoft.DevCenter/devcenters resource:
    -  Microsoft.DevCenter/devcenters/catalogs
    - Microsoft.DevCenter/devcenters/devboxdefinitions
    - Microsoft.DevCenter/devcenters/environmentTypes
    - Microsoft.DevCenter/devcenters/galleries
- Microsoft.DevCenter/projects is a separate resource type
- Therefore, the default logic for structuring this would be 1 resource module to include devcenter, with its children, and another one to include projects.
- If this wrapping doesn't make sense from usability perspective, the whole thing can be structured as a pattern module.

I'd defer to @prjelesi and the TF side of the team to decide.

**Comment by cshea-msft** [comment]
thanks @matebarabas 

@prjelesi @mbilalamjad @matt-FFFFFF any thoughts on this? You can't create any of these without dev center in the code so in my opinion dev center would be the root module and add all the others as sub modules. 

![Image](https://github.com/user-attachments/assets/178d87cf-84d2-41d8-b92c-dc8dda2a83ee)

**Comment by matt-FFFFFF** [comment]
Are they child resources?

**Comment by matt-FFFFFF** [comment]
Like actual child resources?

If not then we can use a ptn module like we do with VWAN

**Comment by matebarabas** [comment]
> Like actual child resources?
> 
> If not then we can use a ptn module like we do with VWAN

@matt-FFFFFF, please see my above comment about their parent-child relationship: https://github.com/Azure/Azure-Verified-Modules/issues/335#issuecomment-2291687184

**Comment by matt-FFFFFF** [comment]
Child resources = submodules

Others can be grouped into a ptn to make a sensible deployment

**Comment by cshea-msft** [comment]
Got it thanks! Will create dev center module with the four submodules.

**Comment by cshea-msft** [comment]
here is the PR for this module

https://github.com/Azure/terraform-azurerm-avm-res-devcenter-devcenter/pull/5

**Comment by cshea-msft** [comment]
Module has been published to Terraform Registry. PR checks all have passed! 

https://registry.terraform.io/modules/Azure/avm-res-devcenter-devcenter/azurerm/latest
https://github.com/Azure/terraform-azurerm-avm-res-devcenter-devcenter
