### ISSUE TITLE
[Module Proposal]: `avm-res-documentdb-databaseaccount` (tf)

### ISSUE THREAD

**Issue by PmeshramPM** [Azure/Azure-Verified-Modules#336]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-documentdb-databaseaccount

### Module Details

Requested by the AZD team: https://github.com/Azure/Azure-Verified-Modules/issues/261
Needs module owner.
CC: @jongio

### Do you want to be the owner of this module?

No

**Comment by bryansan-msft** [comment]
Hello @mbilalamjad and @matebarabas, I would like to be the owner of this module and help with its development.

**Comment by mbilalamjad** [comment]
Hi @bryansan-msft,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by bryansan-msft** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by mbilalamjad** [comment]
Hi @bryansan-msft ,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

Before starting development, please ensure ALL the following requirements are met.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - for naming your module
  - `TelemetryIdPrefix` - for your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repo name and folder path are defined in `RepoURL`
  - Create GitHub teams for module owners and contributors and grant them permissions as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
  - Grant permissions for the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

Check if this module exists in the other IaC language. If so, collaborate with the other owner for consistency. 👍

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published! Please include a link pointing to your PR, once available. 🙏**

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by panwar28** [comment]
I would like to be a co-owner and contribute to this module.

**Comment by mbilalamjad** [comment]
@bryansan-msft would you like to have @panwar28 as co-owner, he mentioned to me that he's got a module written already and he could contribute his code to this module

**Comment by bryansan-msft** [comment]
Hello @mbilalamjad, yes, no problem. He can be a co-owner.

**Comment by mbilalamjad** [comment]
Requested @bryansan-msft to share an update here

**Comment by bryansan-msft** [comment]
Hello @mbilalamjad, It is "in development" I have been working on this but as it is my first modules, I have been slow to get started with the structure of everything. I am working with my assigned contribution mentor on this to speed up.

**Comment by bryansan-msft** [comment]
Hello @mbilalamjad, It is "in development" I have been working on this but as it is my first modules I have been getting problems to get started with structure of everything. I am working with my assigned contribution mentor on this.

**Comment by v-xuto** [comment]
@bryansan-msft  - Do you have an ETA for this?

**Comment by bryansan-msft** [comment]
> @bryansan-msft - Do you have an ETA for this?

It should be by the end of next month. I'm currently wrapping up the service bus one

**Comment by bryansan-msft** [comment]
Module is published https://registry.terraform.io/modules/Azure/avm-res-documentdb-databaseaccount/azurerm/latest

**Comment by mbilalamjad** [comment]
Hi @bryansan-msft the module needs to go through the [review ](https://azure.github.io/Azure-Verified-Modules/contributing/terraform/review/)process before being published to the terraform registry. Pre-req of the review process is that all checks must pass which I can see on a [PR ](https://github.com/Azure/terraform-azurerm-avm-res-documentdb-databaseaccount/pull/28)are currently failing, can you ensure that all check are passing and follow the [review ](https://azure.github.io/Azure-Verified-Modules/contributing/terraform/review/)process to have the module reviewed.

**Comment by bryansan-msft** [comment]
But @mbilalamjad that PR is yours, my PR to publish a new module is this one https://github.com/Azure/terraform-azurerm-avm-res-documentdb-databaseaccount/pull/16

I was approved by @matt-FFFFFF and with all checks in green

**Comment by mbilalamjad** [comment]
> But @mbilalamjad that PR is yours, my PR to publish a new module is this one [Azure/terraform-azurerm-avm-res-documentdb-databaseaccount#16](https://github.com/Azure/terraform-azurerm-avm-res-documentdb-databaseaccount/pull/16)
> 
> It was approved by @matt-FFFFFF and with all checks in green

Hi @bryansan-msft my PR is actually an automated governance PR which needs to be merged with all checks passing before a module can be published per the review process. Approval of your PR by @matt-FFFFFF is part of the review process but not the whole process. Appreciate if you could push updates on the branch of my PR to fix the failing checks and also incorporated any other changes as you address the "Requested Actions" in the [AVM-Review](https://github.com/Azure/terraform-azurerm-avm-res-documentdb-databaseaccount/issues/30) of your module.

**Comment by bryansan-msft** [comment]
@mbilalamjad in your PR, version-check is still failing even though version v0.1.0 was specified. linting / avm-fix is also failing because it cant find the image. As both of these tasks are owned by the AVM team I cant guess what they do or fix them. There is no documentation in AVM page as well.

On the other hand. In the AVM page the version format suggested in the owner flow is "0.1.0" not "v0.1.0" so I dont know why this version-check is expecting something prefixed with "v"

Lastly, when the PR was approved and merged. All these checks that are failing now passed. So it was a change in the AVM tools after the PR

**Comment by mbilalamjad** [comment]
Hey @bryansan-msft, the name of the release was 'initial module release', I updated it to '0.1.0' after which the version-check is passing now, I can see the same on your other module for service bus. To fix the linting / avm-fix you need to run  avm pre-commit locally and then commit the changes as mentioned in the error of the check. I have done that for you and committed the changes, that check is also passing now. Hope that helps, please continue with the the "Requested Actions" in the [AVM-Review]( https://github.com/Azure/terraform-azurerm-avm-res-documentdb-databaseaccount/issues/30) of your module.

**Comment by bryansan-msft** [comment]
@mbilalamjad I will have a look at the service bus one. Can you merge the PR of documentdb so we can close this ticket? I cant approve or merge that PR

**Comment by mbilalamjad** [comment]
> @mbilalamjad I will have a look at the service bus one. Can you merge the PR of documentdb so we can close this ticket? I cant approve or merge that PR

Hey @bryansan-msft, would recommend to perform the "Requested Actions" on the [AVM-Review](https://github.com/Azure/terraform-azurerm-avm-res-documentdb-databaseaccount/issues/30) and push any updates necessary to the branch of this [PR](https://github.com/Azure/terraform-azurerm-avm-res-documentdb-databaseaccount/pull/35) before we merge it

**Comment by mbilalamjad** [comment]
The module has been published to the registry, but the initial review of this module is pending. AVM team is closing this module proposal and mark the module available in the module index while continuing the review on the repo.
Terraform Registry Link: https://registry.terraform.io/modules/Azure/avm-res-documentdb-databaseaccount/azurerm/latest
GitHub Repo Link: https://github.com/Azure/terraform-azurerm-avm-res-documentdb-databaseaccount
