### ISSUE TITLE
[Module Proposal]: `avm-res-insights-component` (tf)

### ISSUE THREAD

**Issue by PmeshramPM** [Azure/Azure-Verified-Modules#337]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-insights-component

### Module Details

Requested by the AZD team: https://github.com/Azure/Azure-Verified-Modules/issues/261
Needs module owner.
CC: @jongio

### Do you want to be the owner of this module?

No

**Comment by mbilalamjad** [comment]
Hi @JFolberth,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

Before starting development, please ensure ALL the following requirements are met.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - for naming your module
  - `TelemetryIdPrefix` - for your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repo name and folder path are defined in `RepoURL`
  - Create GitHub teams for module owners and contributors and grant them permissions as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
  - Grant permissions for the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

Check if this module exists in the other IaC language. If so, collaborate with the other owner for consistency. 👍

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published! Please include a link pointing to your PR, once available. 🙏**

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by JFolberth** [comment]
Have an open PR for this: 

https://github.com/Azure/terraform-azurerm-avm-res-managedidentity-userassignedidentity/pull/1

**Comment by v-xuto** [comment]
@JFolberth - Do you have an ETA for this?

**Comment by JFolberth** [comment]
@v-xuto this has been published: https://registry.terraform.io/modules/Azure/avm-res-managedidentity-userassignedidentity/azurerm/latest

**Comment by JFolberth** [comment]
Development will begin next week

**Comment by JFolberth** [comment]
Just to update this repository has been submitted for business review for creation

**Comment by JFolberth** [comment]
PR submitted for this: https://github.com/Azure/terraform-azurerm-avm-res-insights-component/pull/1 working through checks now.

**Comment by JFolberth** [comment]
PR Completed: https://github.com/Azure/terraform-azurerm-avm-res-insights-component/pull/11

**Comment by Menghua1** [comment]
@PmeshramPM this new module `avm-res-insights-component` has been verified and there is no issue. Please close the current issue.

**Comment by mbilalamjad** [comment]
The module has been published to the registry, but the initial review of this module is pending. AVM team is closing this module proposal and marking the module available in the module index while continuing the review on the repo.
Terraform Registry Link: https://registry.terraform.io/modules/Azure/avm-res-insights-component/azurerm/latest
GitHub Repo Link: https://github.com/Azure/terraform-azurerm-avm-res-insights-component
