### ISSUE TITLE
[Module Proposal]: `avm-res-insights-diagnosticsetting` (tf)

### ISSUE THREAD

**Issue by PmeshramPM** [Azure/Azure-Verified-Modules#338]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-insights-diagnosticsetting

### Module Details

Requested by the AZD team: https://github.com/Azure/Azure-Verified-Modules/issues/261
Needs module owner.
CC: @jongio

### Do you want to be the owner of this module?

No

**Comment by jensheerin** [comment]
Hi @jongio, Can you please clarify if this request will use the new AMA agent and DCR? Thank you!

**Comment by matt-FFFFFF** [comment]
Hi please can we have a discussion as to why this is required?

Thanks

**Comment by jongio** [comment]
> Hi @jongio, Can you please clarify if this request will use the new AMA agent and DCR? Thank you!

I'm not sure.  Here's how it's being used: https://github.com/Azure/azure-dev/blob/df69a8cf361b03b6067cd4ab292df631fbfc2575/templates/common/infra/bicep/core/host/container-registry.bicep#L57

**Comment by mbilalamjad** [comment]
@matt-FFFFFF based on @jongio response, any further input from you ?

**Comment by matt-FFFFFF** [comment]
This would ordinarily be part of a resource module for the associated resource.

Is there a reason we need this as a separate module when we have the interface and implementation defined in the spec?

**Comment by mbilalamjad** [comment]
Based on @matt-FFFFFF's comment above and the fact that we have this as an interface, closing the module proposal
