### ISSUE TITLE
[Module Proposal]: `avm-ptn-virtualwan` (tf)

### ISSUE THREAD

**Issue by JefferyMitchell** [Azure/Azure-Verified-Modules#34]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals

### Terraform or Bicep?

Terraform

### Module Classification?

Pattern Module

### Module Name

The module name is avm-ptn-vwan based on naming convention 
GitHub Repo name is  terraform-azurerm-avm-ptn-vwan

### Module Details

Outlined here.

https://dev.azure.com/CSUSolEng/Azure%20Infra%20Networking/_workitems/edit/30510

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username

khushal08

**Comment by jeanchg** [comment]
@khushal08, understand you've been working on this for some time, thank you for joining the AVM initiative.
@matt-FFFFFF has asked you to convert from TFVM to AVM

**Comment by matt-FFFFFF** [comment]
Hi all,

This is just a repo rename as will be a pattern module

**Comment by JefferyMitchell** [comment]
adding the official name update as a note here:  terraform-azurerm-avm-ptn-virtualwan

**Comment by matt-FFFFFF** [comment]
This has been completed now

**Comment by jtracey93** [comment]
@matt-FFFFFF as in the rename or the module dev work? If so we need to get on our indexes etc..

**Comment by matt-FFFFFF** [comment]
The rename. It's now a pattern module. Need to check publishing status to the registry

**Comment by jtracey93** [comment]
@matebarabas can we get this one in the index please?

**Comment by matebarabas** [comment]
@Azure/avm-core-team, can we please have a quick chat on the classification of this one to be a pattern module? We do have a VWAN resource module for Bicep (planned to be migrated from CARML). Let's align on how this one is (going to be) different and what the logic would be behind classifying this as a pattern. Thanks!

**Comment by jtracey93** [comment]
@matebarabas add it to our list for Tuesday 👍

But in short. Technically a virtual wan is a resource on it own from an API perspective so if the resource deploys virtual wan hubs, route tables, labels, connections, gateways, firewalls etc it's no longer a resource module and is now a pattern module as it's deploying more than one resource. 

That was mine and @matt-FFFFFF's thinking earlier today. 

Happy to discuss

**Comment by PmeshramPM** [comment]
@JefferyMitchell  - I have updated the module name with github repo name. Please do look at the naming conventions from the spec 

The module name is avm-ptn-vwan 
GitHub Repo name is - terraform-azurerm-avm-ptn-vwan

**Comment by JefferyMitchell** [comment]
@matebarabas @jtracey93 So should we update this to be a resource module? Do you think that we can break the other components included into resource modules?

So @matebarabas you were thinking there would be resource module for each of the below on the Bicep side? 

Virtual WAN
Azure Firewall
Site-to-Site Virtual Network Gateway:
ER Gateway

**Comment by matebarabas** [comment]
@JefferyMitchell, here are my two cents on your above questions:
- The TF and Bicep implementations of the same module (whether resource or pattern) should always be aligned - unless there's a technology limition that doesn't allow for it. We encourage everyone to do this via identify who the owner of the module in question in the other language is (if any), and work with the owner to make sure everything is thought of. In this case, the Bicep version of these modules already exist and will be migrated from CARML, and we already have volunteers for some of the modules in question; listed in the module index, [here](http://localhost:1313/Azure-Verified-Modules/indexes/bicep/bicep-resource-modules/).
- The Bicep version of these modules ara available here in CARML:
    - [S2S VPN GW](https://github.com/Azure/ResourceModules/tree/main/modules/network/virtual-network-gateway)
    - [ER GW](https://github.com/Azure/ResourceModules/tree/main/modules/network/express-route-gateway) - @arnoldna volunteered to be the module owner of the Bicep module, once it's migrated to AVM.
    - [Azure FW](https://github.com/Azure/ResourceModules/tree/main/modules/network/azure-firewall) - @rahalan volunteered to be the module owner of the Bicep module, once it's migrated to AVM.
    - [VWAN](https://github.com/Azure/ResourceModules/tree/main/modules/network/virtual-wan)
- That said, Azure FW and VWAN are more complex beasts, hence the AVM core team thinks it might make sense to break these down to separate resource modules and implement a higher-level pattern that stitches them together to an Azure FW and a VWAN pattern respectively (in which case, resource modules should have separate Module proposals opened for each resource module required).

I'd also like to let others comment: @jtracey93, @matt-FFFFFF, @AlexanderSehr, @eriqua

**Comment by jtracey93** [comment]
To me this is a pattern module as its stitching together the multiple resources, whether children or external. https://github.com/Azure/terraform-azurerm-avm-ptn-virtualwan

There **is not** a CARML equivalent module of this, only a resource module for the virtual wan instance itself, which is not the same: https://github.com/Azure/ResourceModules/tree/main/modules/network/virtual-wan

So I think this **is a pattern module and should carry on as such**. No one is just deploying a single VWAN instance, that technically wouldn't even include a hub or anything useful 😆

**Comment by matt-FFFFFF** [comment]
I agree. It's a pattern, for the reasons stated above by @jtracey93

**Comment by mbilalamjad** [comment]
Closing as module has been published to terraform registry
https://registry.terraform.io/modules/Azure/avm-ptn-virtualwan/azurerm/latest

Further discussion on this module including issues & PRs to take please on the below repo
https://github.com/Azure/terraform-azurerm-avm-ptn-virtualwan
