### ISSUE TITLE
[Module Proposal]: `avm-res-search-searchservice` (tf)

### ISSUE THREAD

**Issue by PmeshramPM** [Azure/Azure-Verified-Modules#340]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-search-searchservice

### Module Details

Requested by the AZD team: https://github.com/Azure/Azure-Verified-Modules/issues/261
Needs module owner.
CC: @jongio

### Do you want to be the owner of this module?

No

**Comment by kewalaka** [comment]
hi folks, my colleague @charliekw411 has a sample implementation in the style of AVM here;

https://github.com/charliekw411/terraform-azurerm-avm-res-search-searchservice

**Comment by mbilalamjad** [comment]
Thank you @kewalaka, let me locate a MSFT FTE to help with the setup and work with @charliekw411

**Comment by mbilalamjad** [comment]
@PmeshramPM I'm happy to own this for now till we find some else so that we can work with @charliekw411

**Comment by PmeshramPM** [comment]
Hi @mbilalamjad ,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

Before starting development, please ensure ALL the following requirements are met.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - for naming your module
  - `TelemetryIdPrefix` - for your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repo name and folder path are defined in `RepoURL`
  - Create GitHub teams for module owners and contributors and grant them permissions as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
  - Grant permissions for the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

Check if this module exists in the other IaC language. If so, collaborate with the other owner for consistency. 👍

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published! Please include a link pointing to your PR, once available. 🙏**

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by charliekw411** [comment]
hi team, is there any update on getting a MSFTE to help with the setup for this module? TIA 😄

**Comment by mbilalamjad** [comment]
> hi team, is there any update on getting a MSFTE to help with the setup for this module? TIA 😄

Hey @charliekw411 I'll be working with you on this, currently working on getting the repo setup, once its done, I'll update you and we can get started with this module.

**Comment by charliekw411** [comment]
hey @mbilalamjad 
thanks for the update. Look forward to working with you in the near future!

**Comment by v-xuto** [comment]
@mbilalamjad - Do you have an ETA for this?

**Comment by mbilalamjad** [comment]
@charliekw411 @v-xuto the repo is in review once approved, will make it public for contribution

**Comment by charliekw411** [comment]
awesome, thanks for the update @mbilalamjad

**Comment by charliekw411** [comment]
Hi @mbilalamjad , 

Is there any update on the status of this repo. Would be good to get contribution to this repo underway. 

TIA

**Comment by mbilalamjad** [comment]
Transferring ownership of this module to @seekerofsai

**Comment by seekerofsai** [comment]
The initial review of this module is complete, and the module has been published to the registry. Requesting AVM team to close this module proposal and mark the module available in the module index.
Terraform Registry Link: https://registry.terraform.io/modules/Azure/avm-res-search-searchservice/azurerm/latest
GitHub Repo Link: https://github.com/Azure/terraform-azurerm-avm-res-search-searchservice
