### ISSUE TITLE
[Module Proposal]: `avm-res-web-site` (tf)

### ISSUE THREAD

**Issue by PmeshramPM** [Azure/Azure-Verified-Modules#342]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-web-site

### Module Details

Requested by the AZD team: https://github.com/Azure/Azure-Verified-Modules/issues/261
Needs module owner.
CC: @jongio

### Do you want to be the owner of this module?

No

**Comment by donovm4** [comment]
Hi @mbilalamjad - which Azure resource does this apply to within the azurerm registry?

**Comment by mbilalamjad** [comment]
Hey @donovm4 this is Web and Function App, have a look here at the corresponding Bicep module for this which is being ported from CARML
https://github.com/Azure/Azure-Verified-Modules/issues/172
https://github.com/Azure/ResourceModules/tree/main/modules/web/site

**Comment by donovm4** [comment]
@mbilalamjad - I may pick this module up but want to leave this for future reference. 

There are some deprecations happening once the provider moves to 4.0 (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service). 

Would it be better to use the resources from the provider that will be used in the latest "announced" version of the provider?

**Comment by mbilalamjad** [comment]
Reading through the deprecation notice, the recommendation is to use [azurerm_linux_web_app](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_web_app) and [azurerm_windows_web_app](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_web_app) resources instead.

**Comment by donovm4** [comment]
@mbilalamjad - thanks for the clarification. I am interested in being a module owner for this one. 

I am again not that well-versed in how web/function apps work, but I think I'll learn a lot through this.

**Comment by mbilalamjad** [comment]
Hi @donovm4 ,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by donovm4** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by mbilalamjad** [comment]
Hi @donovm4,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

Before starting development, please ensure ALL the following requirements are met.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - for naming your module
  - `TelemetryIdPrefix` - for your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repo name and folder path are defined in `RepoURL`
  - Create GitHub teams for module owners and contributors and grant them permissions as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
  - Grant permissions for the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

Check if this module exists in the other IaC language. If so, collaborate with the other owner for consistency. 👍

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published! Please include a link pointing to your PR, once available. 🙏**

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by matt-FFFFFF** [comment]
@donovm4 please can you fix the issue here: https://github.com/Azure/terraform-azurerm-avm-res-web-site/issues/2

It's preventing the repo governance from working

thanks

**Comment by mbilalamjad** [comment]
Requested @donovm4 to share an update here

**Comment by donovm4** [comment]
Hi @mbilalamjad + @matt-FFFFFF:
This is an update regarding the avm-res-web-site module, but please read fully as I am not sure if I could truly determine where I am with this.

This module is published v0.1.0 but only supports function apps currently, as I have some questions in regards to the relation of:

- Function Apps
- Web Apps
- Logic Apps

These resources leverage app service plans and have similar configurations (not exactly the same) but aren't technically the same resource:

- Windows + Linux (`azurerm_<windows or linux>_function_app`)
- Windows + Linux (`azurerm_<windows or linux>_web_app`)
- Logic App (`azurerm_logic_app_standard`)

I would like to request if someone from AVM side can provide guidance through this process. It might involve making some of the flowing decisions:

- function apps ONLY in this module, so ALL separate modules
- function apps + web apps in this module with logic apps having their own module (not sure if logic apps are type "web" or "site")
- function app, web app, and logic app all within the same module (not sure if anyone already made a separate request

This module is currently published and available [here](https://registry.terraform.io/modules/Azure/avm-res-web-site/azurerm/latest).

**Comment by mbilalamjad** [comment]
Thank you so much @donovm4 for owning and developing this module, since the module is published to the registry lets take further discussion on the repo itself

Closing this proposal as module has been published to terraform registry below
https://registry.terraform.io/modules/Azure/avm-res-web-site/azurerm/latest

Further discussion on this module including issues & PRs to take please on its repo below
https://github.com/Azure/terraform-azurerm-avm-res-web-site
