### ISSUE TITLE
[Module Proposal]: `avm-ptn-alz-management` (tf)

### ISSUE THREAD

**Issue by luke-taylor** [Azure/Azure-Verified-Modules#344]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Pattern Module

### Module Name

avm-ptn-alz-management

### Module Details

A pattern module that handles all aspects of the ALZ management resources. This module already exists here, https://github.com/Azure/terraform-azurerm-alz-management

But will be beneficially if it got realigned with AVM.

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

luke-taylor

**Comment by matt-FFFFFF** [comment]
Excellent news - feel free to work on the conversion

**Comment by prjelesi** [comment]
@matt-FFFFFF @luke-taylor i move this back to 'proposals' so @mbilalamjad or @PmeshramPM can view and process.

**Comment by PmeshramPM** [comment]
@luke-taylor  - Thanks for requesting/proposing to be an AVM module owner.

We just want to confirm you agree to the below pages that define what module ownership means:

https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions
https://azure.github.io/Azure-Verified-Modules/specs/shared
https://azure.github.io/Azure-Verified-Modules/help-support/module-support
Any questions or clarifications needed, let us know.

If you agree please just reply to this issue with the exact sentence below (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,
The AVM Core Team

**Comment by luke-taylor** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by PmeshramPM** [comment]
Hi @luke-taylor ,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

We just want to ask you to double check a few important things and take the next steps before you start the development.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - to name your module
  - `TelemetryIdPrefix` - to be used in your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repository name and folder path are defined in `RepoURL`
  - Create the GitHub teams defined in the `ModuleOwnersGHTeam` and `ModuleContributorsGHTeam` columns and grant them permissions as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
    - In case of a Bicep module, **please let the AVM core team know** when you created these teams, and we'll help you with assigning the necessary permissions as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#grant-permissions---bicep).
    - In case of a Terraform module, follow the instructions [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#grant-permissions---terraform) and assign the necessary permissions.

Grant the right level of permissions for  the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published!** Please include a link pointing to your PR if available. 🙏

**Comment by luke-taylor** [comment]
@mbilalamjad The module has been published on the registry https://registry.terraform.io/modules/Azure/avm-ptn-alz-management/azurerm/latest

**Comment by mbilalamjad** [comment]
Thank you so much @luke-taylor for your contribution.

Closing as module has been published to terraform registry below.
https://registry.terraform.io/modules/Azure/avm-ptn-alz-management/azurerm/latest

Further discussion on this module including issues & PRs to take please on its repo below.
https://github.com/Azure/terraform-azurerm-avm-ptn-alz-management
