### ISSUE TITLE
[Module Proposal]: `avm-res-databricks-workspace` (tf)

### ISSUE THREAD

**Issue by acauret** [Azure/Azure-Verified-Modules#383]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-databricks-workspace

### Module Details

I would like to work on this module as an external SME for the purposes of expanding our library based on current Data requirements with Azure Verified Modules. Can you please find a FTE owner that I can work with?

### Do you want to be the owner of this module?

No

### (Optional) Secondary Module Owner's GitHub Username (handle)

acauret

**Comment by matebarabas** [comment]
@segraef, as we discussed internally, would you be able to help Andrew (@acauret) with this issue? Thank you so much!

**Comment by segraef** [comment]
happy to assist as owner, awaiting the agreement to sign

**Comment by segraef** [comment]
Teams @Azure/avm-res-databricks-workspace-module-contributors-bicep and @Azure/avm-res-databricks-workspace-module-owners-bicep created.

**Comment by mbilalamjad** [comment]
Hi @segraef,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by jeanchg** [comment]
> Teams @Azure/avm-res-databricks-workspace-module-contributors-bicep and @Azure/avm-res-databricks-workspace-module-owners-bicep created.

@segraef it's a TF module, right? (I'm confused by the teams creation here)

**Comment by segraef** [comment]
> Hi @segraef,
> 
> Thanks for requesting/proposing to be an AVM module owner!
> 
> We just want to confirm **you agree to the below pages** that define what module ownership means:
> 
> * [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
> * [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
> * [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)
> 
> Any questions or clarifications needed, let us know!
> 
> If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):
> 
> "I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"
> 
> Thanks,
> 
> The AVM Core Team
> 
> #RR

I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by segraef** [comment]
@acauret https://github.com/Azure/terraform-azurerm-avm-res-databricks-workspace/ created, will be set to public once internal review is done.

**Comment by acauret** [comment]
> @acauret https://github.com/Azure/terraform-azurerm-avm-res-databricks-workspace/ created, will be set to public once internal review is done.

I get a 404 when trying to access

**Comment by mbilalamjad** [comment]
> > @acauret https://github.com/Azure/terraform-azurerm-avm-res-databricks-workspace/ created, will be set to public once internal review is done.
> 
> I get a 404 when trying to access

@acauret You are getting a 404 because the repo is currrently private due to an internal review post which it will become public which might take upto a week. In the mean time as @segraef mentioned please feel free to follow terraform contribution guide [here](https://azure.github.io/Azure-Verified-Modules/contributing/terraform/) in a repo of your own, later we can transfer from your repo to the official repo once it becomes public after the review

**Comment by mbilalamjad** [comment]
> @Azure/avm-res-databricks-workspace-module-contributors-bicep and @Azure/avm-res-databricks-workspace-module-owners-bicep

Hey @segraef the teams you've created having bicep in their names towards the end whereas the module is a terraform one, just double checking with you if this needs to be corrected.

**Comment by segraef** [comment]
> > @Azure/avm-res-databricks-workspace-module-contributors-bicep and @Azure/avm-res-databricks-workspace-module-owners-bicep
> 
> Hey @segraef the teams you've created having bicep in their names towards the end whereas the module is a terraform one, just double checking with you if this needs to be corrected.

@Azure/avm-res-databricks-workspace-module-contributors-tf 
@Azure/avm-res-databricks-workspace-module-owners-tf

**Comment by acauret** [comment]
Thanks .. Let me know . I will be away from Wednesday until the 8th January, Happy holidays!

**Comment by segraef** [comment]
There you go @acauret https://github.com/Azure/terraform-azurerm-avm-res-databricks-workspace.

**Comment by mbilalamjad** [comment]
Hey @acauret hope you're doing well and happy new year, just wanted to check-in and ask if had the chance to look at the above repo @segraef has created and could you create a PR with the code that you currently have for @segraef to review.

**Comment by acauret** [comment]
Sorry busy first week back.. just did it this morning

**Comment by segraef** [comment]
Set up a session to sync with @acauret tonight.

**Comment by segraef** [comment]
https://github.com/Azure/terraform-azurerm-avm-res-databricks-workspace/pull/11 in review

**Comment by segraef** [comment]
Published: https://registry.terraform.io/modules/Azure/avm-res-databricks-workspace/azurerm/latest
