### ISSUE TITLE
[Module Proposal]: `avm-res-network-loadbalancer` (res) (tf)

### ISSUE THREAD

**Issue by PmeshramPM** [Azure/Azure-Verified-Modules#40]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals

### Terraform or Bicep?

Terraform

### Module Classification?

Resource Module

### Module Name
Module name -> avm-res-network-loadbalancer
GH repo name -> terraform-azurerm-avm-res-network-loadbalancer

### Module Details

Evolving the existing Terraform module from TFVM - https://github.com/Azure/terraform-azurerm-loadbalancer to AVM standards. 

### Do you want to be the owner of this module?

No

**Comment by PmeshramPM** [comment]
@donovm4 - Please pay attention to the module name description. I have updated that based on specs.

**Comment by donovm4** [comment]
@PmeshramPM - I recently submitted a second PR and seems like it passed all of the tests.

**Comment by mbilalamjad** [comment]
Thank you so much @donovm4 for your contribution

Closing as module has been published to terraform registry below
https://registry.terraform.io/modules/Azure/avm-res-network-loadbalancer/azurerm/latest

Further discussion on this module including issues & PRs to take please on its repo below
https://github.com/Azure/terraform-azurerm-avm-res-network-loadbalancer
