### ISSUE TITLE
[Orphaned Module]: `avm/res/insights/metric-alert`

### ISSUE THREAD

**Issue by matebarabas** [Azure/Azure-Verified-Modules#409]
### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/insights/metric-alert

### Module Details

This module was migrated from CARML by @krbar without an owner. 

**Note**: when someone volunteers to be the owner of this module, please reach out to @krbar to for changing the ownership of the existing GitHub teams as well.

- Module proposal: https://github.com/Azure/Azure-Verified-Modules/issues/375
- PR: https://github.com/Azure/bicep-registry-modules/pull/711

### Do you want to be the new owner of this module?

No

### Module Owner's GitHub Username (handle)

kijunkang

**Comment by kijunkang** [comment]
Hi @matebarabas.
I would like to take ownership of this module.

**Comment by matebarabas** [comment]
Hi @kijunkang,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by kijunkang** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by matebarabas** [comment]
Hi @kijunkang,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

We just want to ask you to double check a few important things.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- You must be the owner of the GitHub teams as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
- Please check that your name has been updated in the module index page (this should happen shortly after you confirmed ownership).

You can now take ownership of this module and start improving it as needed! ✅ Happy coding! 🎉

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by matebarabas** [comment]
@kijunkang, since this module has been migrated by @krbar (Kris Baranek), he's created the required GH teams. Please work with him to take ownership over these teams **and let me know in a comment here when it happened**.

**Please also remove the `ORPHANED.md` file** from the [module's folder](https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/insights/metric-alert) and its content from the `README.md`, by following the steps described in point 5 [here](https://azure.github.io/Azure-Verified-Modules/help-support/issue-triage/avm-issue-triage/#when-a-new-owner-is-identified) and let me know in a comment when this is done. Thanks!

**Comment by krbar** [comment]
@kijunkang Before I can transfer the GitHub teams to you, you must join the @Azure organization on GitHub. 
This link describes how: [Account linking and join organizations | Docs - Microsoft Open Source](https://docs.opensource.microsoft.com/github/opensource/accounts/linking/) (see section "Join organizations")

**Comment by krbar** [comment]
PR to unorphan the module is in review: https://github.com/Azure/bicep-registry-modules/pull/1265

**Comment by kijunkang** [comment]
Thank you @krbar, I just joined the [@Azure](https://github.com/Azure) organization on GitHub.

**Comment by krbar** [comment]
Thank you. The teams are transferred and the "module orphaned" note has been removed

**Comment by matebarabas** [comment]
Thank you for confirming, this concludes this issue!
