### ISSUE TITLE
[Module Proposal]: `avm-res-network-applicationgateway`

### ISSUE THREAD

**Issue by PmeshramPM** [Azure/Azure-Verified-Modules#41]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals

### Terraform or Bicep?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-network-applicationgateway

### Module Details

GH repo name - terraform-azurerm-avm-res-network-applicationgateway

Application Gateway is one of the most common requirement for Internet facing applications to manage the web traffic. 

Please refer to the this CARML Bicep module as it already implements RBAC, Locks, Tags, and Diag. https://github.com/Azure/ResourceModules/tree/main/modules/network/application-gateway

### Do you want to be the owner of this module?

No

**Comment by PankajMeshramCSA** [comment]
@mofaizal - Please see that the ask here is to build two modules. Please see the details here 
https://azure.github.io/Azure-Verified-Modules/indexes/terraform/tf-resource-modules/

1. avm-res-network-applicationgateway - deploying the app gateway 
2. avm-res-network-applicationgatewaywebapplicationfirewallpolicy - WAF policies 

We have the same reference in Bicep registry and keen to keep that consistent with TF. 

Please do let me know if you are happy with this and any thoughts.

**Comment by kewalaka** [comment]
watching this with some interest, I've recently created these resources uses the two modules as you suggest, it occurred to me when writing them that there's a generic pattern that can be followed to dynamically support all attributes and provide some baseline defaults to minimise what the calling code needs to pass in.

e.g. taking the backend http settings block for the appgw as an example:

```terraform
  dynamic "backend_http_settings" {
    for_each = var.backend_http_settings
    content {
      name                                = lookup(backend_http_settings.value, "name", "${local.http_setting_name}${count.index + 1}")
      cookie_based_affinity               = lookup(backend_http_settings.value, "cookie_based_affinity", "Disabled")
      affinity_cookie_name                = lookup(backend_http_settings.value, "affinity_cookie_name", "affinity")
      path                                = lookup(backend_http_settings.value, "path", null)
      port                                = lookup(backend_http_settings.value, "port", 443)
      probe_name                          = lookup(backend_http_settings.value, "probe_name", "${local.probe_name}${count.index + 1}")
      protocol                            = lookup(backend_http_settings.value, "protocol", "Https")
      request_timeout                     = lookup(backend_http_settings.value, "request_timeout", 30)
      host_name                           = lookup(backend_http_settings.value, "pick_host_name_from_backend_address", false) == true ? null : backend_http_settings.value.host_name
      pick_host_name_from_backend_address = lookup(backend_http_settings.value, "pick_host_name_from_backend_address", true)
      dynamic "authentication_certificate" {
        for_each = lookup(backend_http_settings.value, "authentication_certificate", [])
        content {
          name = authentication_certificate.value.name
        }
      }
      trusted_root_certificate_names = lookup(backend_http_settings.value, "trusted_root_certificate_names", [])
      dynamic "connection_draining" {
        for_each = lookup(backend_http_settings.value, "connection_draining", null) == null ? [] : [1]
        content {
          enabled           = backend_http_settings.value.connection_draining.enabled
          drain_timeout_sec = backend_http_settings.value.connection_draining.drain_timeout_sec
        }
      }
    }
  }
```

...and an example of usage:

```terraform
module "app_gateway" {

  # <snip other parameters>

  # this one reliant on many of the default settings
  backend_http_settings = [{
    probe_name                          = "appgw1-probe1"
    pick_host_name_from_backend_address = true
  }]

  # <snip other parameters>
}
```

Another example illustrating coverage & replacing the defaults:

```terraform
module "app_gateway" {

  # <snip other parameters>
  backend_http_settings = [{
    cookie_based_affinity               = "Enabled"
    affinity_cookie_name                = "affinity1"
    name                                = "setting1"
    path                                = "/"
    port                                = "80"
    probe_name                          = "probe1"
    protocol                            = "Http"
    request_timeout                     = "60"
    host_name                           = "stuff.things.co.nz"
    pick_host_name_from_backend_address = false
    connection_draining = {
      enabled           = "true"
      drain_timeout_sec = "30"
    }
  }]

  # <snip other parameters>
}
```

When writing the above, it occurred to me that the pattern _should_ be generic enough to map from supported parameters to code, except for the identification of what should be the defaults.

Happy to share the broader pattern, it's currently mixed in with some other pieces that make it tricky for me to link to, but I can make a stand-alone copy if that would be useful.

Equally happy just to watch and learn if you've got a better approach in mind 😊

**Comment by JefferyMitchell** [comment]
@mofaizal Any update?

**Comment by mbilalamjad** [comment]
Tagging @matt-FFFFFF as he is going to be reviewing this module before its published into the terraform registry

**Comment by PmeshramPM** [comment]
@mofaizal is meeting with @matt-FFFFFF this week to get the feedback after module review and then work on the feedback.

**Comment by JefferyMitchell** [comment]
@mofaizal @PmeshramPM Please let me know when ready for AG PG Team review and I will forward the monthly meeting or schedule a one off meeting. 

CC: @matt-FFFFFF

**Comment by mbilalamjad** [comment]
Reached out to @mofaizal offline, proposal will be updated here based on his input accordingly.

**Comment by mbilalamjad** [comment]
Reached out to @mofaizal and team offline to check-in on any updates or support needed from the AVM team, he or I will update here accordingly

**Comment by mofaizal** [comment]
Thanks for the follow up the In development

**Comment by kewalaka** [comment]
@mofaizal I'm interested in using this module.  Can you share current state so I can help get this ready for v0.1 please?  

I've got a few AVMs contributed so I may be able to help get this to done.

**Comment by mofaizal** [comment]
@kewalaka Thank you for the interested in using this module, I got few feedback from @matt-FFFFFF planning to work this week. Once done will ping you for testing and feedback.

**Comment by mofaizal** [comment]
Testing in progress, for 
- Http Gateway, 
- Route by url, 
- hosting sing single site, 
- host multiple site,
Completed and test in progress  

The following in development 
- WAF
- Self Sign SSL
- KV with SSL 
will complete soon and release it

**Comment by mbilalamjad** [comment]
> @mbilalamjad @matt-FFFFFF @Azure/avm-core-team looking forward your feedback to publish the module. Thanks

Hey @mofaizal, will do a review and update this week accordingly.

**Comment by mbilalamjad** [comment]
Hey @mofaizal, kindly perform the "Requested Actions" in the [AVM-Review](https://github.com/Azure/terraform-azurerm-avm-res-network-applicationgateway/issues/18) of the module, feel free to reach out if you have any questions or need any support.

**Comment by JefferyMitchell** [comment]
@mbilalamjad What are the next steps?

**Comment by mbilalamjad** [comment]
> @mbilalamjad What are the next steps?

Per my above comment, @mofaizal to do the ["Requested Actions"](https://github.com/Azure/terraform-azurerm-avm-res-network-applicationgateway/issues/18) to complete the module review.

**Comment by kewalaka** [comment]
@mofaizal if you'd like to invite me as a contributor I'm happy to help complete the review tasks or help with any areas you need guidance on.

**Comment by mofaizal** [comment]
@kewalaka thanks for offering help. The code is completed, and review also done. There is issue with avmtest, understand from @mbilalamjad that there's been some problem with the runners the team trying to address it.

**Comment by kewalaka** [comment]
@mofaizal thanks for the update - is the `azurerm_web_application_firewall_policy` resource included in the module, or is that needed separately?

**Comment by mofaizal** [comment]
Thanks for the follow up, @mbilalamjad any update on my repo mainly on AVM check the Destroy complete!

TestExample/simple_http_route_by_url_app_gateway 2024-05-29T05:44:06Z command.go:185: Destroy complete! Resources: 13 destroyed.
Error: Process completed with exit code 2.

Due to above error unable to merge to make it public :-( i need to help from core team

**Comment by kewalaka** [comment]
@mofaizal if you invite me as a contributor I can take a look for you, if you like.  I've been across helping with several AVMs so this isn't breaking ground 😄

**Comment by matt-FFFFFF** [comment]
Hi @mofaizal

Consider releasing this on the registry as a `0.1.0` to get initial feedback, even with the destroy error I think it's be good to see this land.

Thanks for all your efforts!

**Comment by mbilalamjad** [comment]
> Hi @mofaizal
> 
> Consider releasing this on the registry as a `0.1.0` to get initial feedback, even with the destroy error I think it's be good to see this land.
> 
> Thanks for all your efforts!

@matt-FFFFFF, @mofaizal the [linting / terraform check](https://github.com/Azure/terraform-azurerm-avm-res-network-applicationgateway/actions/runs/9786636332/job/27021857992?pr=24) is failing with 33 issues, would recommend we address those first and complete the [AVM-Review](https://github.com/Azure/terraform-azurerm-avm-res-network-applicationgateway/issues/18) before publishing

**Comment by matt-FFFFFF** [comment]
We released a new version of the container that should properly print the errors now

**Comment by mofaizal** [comment]
Thanks @matt-FFFFFF back from leave, will check and update the status here.

**Comment by mbilalamjad** [comment]
The initial review of this module is complete, and the module has been published to the registry. Requesting AVM team to close this module proposal and mark the module available in the module index.
Terraform Registry Link: https://registry.terraform.io/modules/Azure/avm-res-network-applicationgateway/azurerm/latest
GitHub Repo Link: https://github.com/Azure/terraform-azurerm-avm-res-network-applicationgateway
