### ISSUE TITLE
[Orphaned Module]: `avm/res/insights/activity-log-alert`

### ISSUE THREAD

**Issue by matebarabas** [Azure/Azure-Verified-Modules#410]
### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/insights/activity-log-alert

### Module Details

This module was migrated from CARML by @krbar without an owner. 

**Note**: when someone volunteers to be the owner of this module, please reach out to @krbar to for changing the ownership of the existing GitHub teams as well.

- Module proposal: https://github.com/Azure/Azure-Verified-Modules/issues/374
- PR: https://github.com/Azure/bicep-registry-modules/pull/708

### Do you want to be the new owner of this module?

No

**Comment by donk-msft** [comment]
Do you want to be the new owner of this module?
Yes

Module Owner's GitHub Username (handle)
donk-msft

**Comment by matebarabas** [comment]
Hi @donk-msft,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by donk-msft** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by matebarabas** [comment]
Hi @donk-msft,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

We just want to ask you to double check a few important things.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- You must be the owner of the GitHub teams as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
- Please check that your name has been updated in the module index page (this should happen shortly after you confirmed ownership).

You can now take ownership of this module and start improving it as needed! ✅ Happy coding! 🎉

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by matebarabas** [comment]
@donk-msft , since this module has been migrated by @krbar (Kris Baranek), he's created the required GH teams. Please work with him to take ownership over these teams **and let me know in a comment here when it happened**.

**Please also remove the `ORPHANED.md` file** from the [module's folder](https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/insights/activity-log-alert) and its content from the `README.md`, by following the steps described in point 5 [here](https://azure.github.io/Azure-Verified-Modules/help-support/issue-triage/avm-issue-triage/#when-a-new-owner-is-identified) and let me know in a comment when this is done. Thanks!

**Comment by Brunoga-MS** [comment]
Hello, I would like to take an ownership of this module.

**Comment by matebarabas** [comment]
Hi @Brunoga-MS,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by donk-msft** [comment]
@matebarabas - static validation fails because of the orphaned state, even though I removed the orphaned.md file . I think it's because the 'https://aka.ms/avm/index/bicep/res/csv' still has the module marked as orphaned.

`Expected $true, because The module is orphaned., but got $false.
  at $pathExisting | Should -Be $true -Because 'The module is orphaned.', /home/runner/work/bicep-registry-modules/bicep-registry-modules/avm/utilities/pipelines/staticValidation/compliance/module.tests.ps1:137
  at <ScriptBlock>, /home/runner/work/bicep-registry-modules/bicep-registry-modules/avm/utilities/pipelines/staticValidation/compliance/module.tests.ps1:137`

**Comment by matebarabas** [comment]
@donk-msft, thank you for calling this out - you're absolutely right! While the change in ownership was already updated in our internal records, it hasn't been propagated to the public indexes yet. That's until now. Please check again, I just [updated](https://github.com/Azure/Azure-Verified-Modules/pull/858) the public index. Thanks again!

**Comment by krbar** [comment]
@matebarabas FYI: @donk-msft is now maintainer of the following GH teams:

https://github.com/orgs/Azure/teams/avm-res-insights-activitylogalert-module-contributors-bicep/members
https://github.com/orgs/Azure/teams/avm-res-insights-activitylogalert-module-owners-bicep/members
