### ISSUE TITLE
[Orphaned Module]: `avm/res/insights/scheduled-query-rule`

### ISSUE THREAD

**Issue by matebarabas** [Azure/Azure-Verified-Modules#411]
### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/insights/scheduled-query-rule

### Module Details

This module was migrated from CARML by @krbar without an owner. 

**Note**: when someone volunteers to be the owner of this module, please reach out to @krbar to for changing the ownership of the existing GitHub teams as well.

- Module proposal: https://github.com/Azure/Azure-Verified-Modules/issues/376
- PR: https://github.com/Azure/bicep-registry-modules/pull/712

### Do you want to be the new owner of this module?

No

**Comment by mcarter106** [comment]
Hi.  I'd like to take ownership of this module.  Thank you

**Comment by matebarabas** [comment]
Hi @mcarter106,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by mcarter106** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER.

**Comment by matebarabas** [comment]
Hi @emichellecarter,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

We just want to ask you to double check a few important things.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- You must be the owner of the GitHub teams as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
- Please check that your name has been updated in the module index page (this should happen shortly after you confirmed ownership).

You can now take ownership of this module and start improving it as needed! ✅ Happy coding! 🎉

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by matebarabas** [comment]
@emichellecarter, since this module has been migrated by @krbar (Kris Baranek), he's created the required GH teams. Please work with him to take ownership over these teams **and let me know in a comment here when it happened**.

**Please also remove the `ORPHANED.md` file** from the [module's folder](https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/insights/scheduled-query-rule) and its content from the `README.md`, by following the steps described in point 5 [here](https://azure.github.io/Azure-Verified-Modules/help-support/issue-triage/avm-issue-triage/#when-a-new-owner-is-identified) and let me know in a comment when this is done. Thanks!

**Comment by Brunoga-MS** [comment]
Hello, I would like to take an ownership of this module.

**Comment by matebarabas** [comment]
@Brunoga-MS, this module is already being handed over to @emichellecarter. If you're interested in taking ownership over another module, I suggest checking this list for modules that need an owner: https://github.com/Azure/Azure-Verified-Modules/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs%3A+Module+Owner+%3Amega%3A%22+label%3A%22Language%3A+Bicep+%3Amuscle%3A%22

**Comment by krbar** [comment]
> @emichellecarter, since this module has been migrated by @krbar (Kris Baranek), he's created the required GH teams. Please work with him to take ownership over these teams **and let me know in a comment here when it happened**.
> 
> **Please also remove the `ORPHANED.md` file** from the [module's folder](https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/insights/scheduled-query-rule) and its content from the `README.md`, by following the steps described in point 5 [here](https://azure.github.io/Azure-Verified-Modules/help-support/issue-triage/avm-issue-triage/#when-a-new-owner-is-identified) and let me know in a comment when this is done. Thanks!

@matebarabas  FYI: the teams are updated, @emichellecarter is now the maintainer of them

**Comment by matebarabas** [comment]
Thanks @krbar for closing the loop and handing over the teams ([realted issue](https://github.com/Azure/Azure-Verified-Modules/issues/895)). The orphaned.md file has also been removed and the readme has been regenerated ([PR](https://github.com/Azure/bicep-registry-modules/pull/1821)). I'm closing this issue now.
