### ISSUE TITLE
[Module Proposal]: `avm/res/aad/domain-service`

### ISSUE THREAD

**Issue by AoifeMc-G** [Azure/Azure-Verified-Modules#422]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/aad/domain-service

### Module Details

Migrate from CARML 

### Do you want to be the owner of this module?

No

### Module Owner's GitHub Username (handle)

CRYP70N1X

### (Optional) Secondary Module Owner's GitHub Username (handle)

ReneHezser (Primary Owner)
AoifeMc-G (Owner)
jamiepla1 (Owner) (Jamie Pla)

**Comment by matebarabas** [comment]
Hi @AoifeMc-G,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by matebarabas** [comment]
@AiofeMc-G please respond to this issue at your earliest convenience by repeating the above quoted text ("I CONFIRM..."). Thank you!

CC: @ChrisSidebotham

**Comment by AoifeMc-G** [comment]
"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Aoife McGuegan


Aoife McGurgan

she/her
Technology Consultant
Mobile: +44 7803340088
***@***.******@***.***>

[signatureImage]

________________________________

**Comment by matebarabas** [comment]
Hi @AoifeMc-G,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

Before starting development, please ensure ALL the following requirements are met.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - for naming your module
  - `TelemetryIdPrefix` - for your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repo name and folder path are defined in `RepoURL`
  - Create GitHub teams for module owners and contributors and grant them permissions as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
  - Grant permissions for the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

Check if this module exists in the other IaC language. If so, collaborate with the other owner for consistency. 👍

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published! Please include a link pointing to your PR, once available. 🙏**

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by AoifeMc-G** [comment]
Yes - development is in progress and have reached out to AVM team

**Comment by matebarabas** [comment]
This module is now looking for a new owner! If you're interested in picking it up, please leave a comment! 👍

**Comment by CRYP70N1X** [comment]
Hi @matebarabas, 
I'm working with a couple of folks on possibly taking ownership and working on this module. 
I'd like to bring this up for discussion with the AVM core team next Tuesday on regular meeting.
Please keep me open for this request. Thanks

**Comment by CRYP70N1X** [comment]
Hi @matebarabas, 
Please assign this module to the following owner. 
@ReneHezser (Primary Owner)
@CRYP70N1X (Primary Owner)
@AoifeMc-G (Owner)
@jamiepla1 (Owner) (Jamie Pla)
Thanks,

**Comment by matebarabas** [comment]
@CRYP70N1X, thank you for recruiting a team to help develop and maintain this module. 👍 

Note that while in the module index, we can only track one primary and one secondary owner, I've put down all the names listed above on this issue's description. Please let me know if you're happy with being _the_ primary owner (or if I should administer René), and please let me know who I should capture as _the_ secondary owner. We then will do a quick "handshake" with the primary owner, where we make things "official". Thanks!

**Comment by matebarabas** [comment]
Hi @CRYP70N1X,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by CRYP70N1X** [comment]
"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

**Comment by matebarabas** [comment]
Hi @CRYP70N1X,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

Before starting development, please ensure ALL the following requirements are met.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - for naming your module
  - `TelemetryIdPrefix` - for your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repo name and folder path are defined in `RepoURL`
  - Create GitHub teams for module owners and contributors and grant them permissions as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
  - Grant permissions for the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

Check if this module exists in the other IaC language. If so, collaborate with the other owner for consistency. 👍

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published! Please include a link pointing to your PR, once available. 🙏**

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by matebarabas** [comment]
@ReneHezser, this naming is correct as it follows the AVM naming convention for resource modules ([RMNFR1](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-rmnfr1---category-naming---module-naming)). 

Note that resource type is intentionally in a singular form as the AVM resource modules always deploy a single instance of the resource/service in question. Also, there's a hyphen between the word of domain and services, as there's camel casing in the original resource type's name.

The two GH teams you need to create (one for owners, one for contributors) follow a slightly different naming convention, described here: [SNFR20](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only), but the easiest and best way of making sure you don't make a mistake when you create them is to grab there name from the related module index CSV, which in your case is this one here: [Bicep Resource Modules](https://github.com/Azure/Azure-Verified-Modules/blob/main/docs/static/module-indexes/BicepResourceModules.csv)

**Comment by ReneHezser** [comment]
Thanks @matebarabas I missed that one. Let's keep it as it was then.

**Comment by ReneHezser** [comment]
Don't worry bot. There are a lot of activities. Just not in the main branch of this repo :-)

**Comment by matebarabas** [comment]
> Don't worry bot. There are a lot of activities. Just not in the main branch of this repo :-)

Please don't forget to provide a link to the PR, once there's one available! 😉 Thanks!

**Comment by ReneHezser** [comment]
Here we go [feat: aad/domain-service](https://github.com/Azure/bicep-registry-modules/pull/1457) 🎉

**Comment by ReneHezser** [comment]
Hey bot. Just wanted to inform you that the PR has been merged.

**Comment by matebarabas** [comment]
- [x] Module published.
- [x] GitHub teams are available and assigned to their parents.
- [x] `CODEOWNERS` file updated.
 
Thank you for your work @ReneHezser! I'm closing this issue now.

**Comment by ReneHezser** [comment]
Hi @matebarabas,
I discussed with @CRYP70N1X to rotate the primary and secondary ownership of this module. Can you please swap the order of our names?

I confirm I wish to own this AVM module and understand the requirements and definition of a module owner.

**Comment by CRYP70N1X** [comment]
[like]  Paul Chirila reacted to your message:
________________________________

**Comment by matebarabas** [comment]
@ReneHezser, @CRYP70N1X, no problem at all. I'll update the public records with the next index update.
