### ISSUE TITLE
[Question/Feedback]: Terraform resource module interface `lock` suggestion

### ISSUE THREAD

**Issue by MariusStorhaug** [Azure/Azure-Verified-Modules#423]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Terraforms default approach to resource existence is that you get what you define, and if terraform manages it and you remove the definition, it will be removed.

With this in mind I find the terraform `lock` interface implementation in the spec a bit strange. The default is an empty object ({}), the default for kind is "None" and the condition for the resource deployment is if kind is set to "None". This seems unnecessary and is not how you would remove a lock using terraform (?). Would you not remove the lock by omitting the lock property?

Suggestion to update: https://azure.github.io/Azure-Verified-Modules/specs/shared/interfaces/#resource-locks -> Terraform section

**Comment by mbilalamjad** [comment]
Makes sense to me since "None" is not listed as a possible value for "lock_level" argument per below
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/management_lock#lock_level

@matt-FFFFFF interested in your thoughts on this issue and the corresponding PR

**Comment by matt-FFFFFF** [comment]
At the moment the logic is correct, it's just not an idiomatic implementation.

Terraform's optional functions means that, even though the default value is an empty object, terraform evaluates the optional values and actually supplies an object with the defaults.

E.g. supplying the default value for `locks = {}` actually results in Terraform using this:

```terraform
{
  type = "None"
  name = null
}
```

Therefore removing the locks variable will delete the lock if it had previously been created, as the ternary expression is lock.type != "None".

I do understand that the use of None is not great here, we should have used `null`, which would be more aligned to the language.

I will make a proposal to alter the locks variable to:

```terraform
variable "lock" {
    type = object({
      name = optional(string, null)
      kind = optional(string, null)
    })
    description = "The lock level to apply to the Key Vault. Possible values are `None`, `CanNotDelete`, and `ReadOnly`."
    default     = {}
    nullable    = false
    validation {
      condition     = var.lock.kind == null || contains(["CanNotDelete", "ReadOnly"], var.lock.kind)
      error_message = "The lock level must be one of: `null`, '\"CanNotDelete\"', or '\"ReadOnly\"'."
    }
  }

# example resource
resource "azurerm_management_lock" "this" {
  count      = var.lock.kind != null ? 1 : 0
  name       = coalesce(var.lock.name, "lock-${var.name}")
  scope      = azurerm_MY_RESOURCE.this.id
  lock_level = var.lock.kind
}
```

**Comment by MariusStorhaug** [comment]
This will support empty property/variables in the code. Also looking at the MI decisions for hiding/removing a stale object block as the AAD team is not intending to use it. Would think that a feature a consumer would not want to use, would simply be omitted from the code not emptied.

```hcl
module "common_key_vault" {
  name                = "mykeyvault"
  role_assignments    = []
  lock                = {}
  diagnostic_settings = {}
}

# Instead of pushing the users to 
module "common_key_vault" {
  name = "mykeyvault"
}
```

**Comment by matt-FFFFFF** [comment]
See comments in #424.

I do think that https://github.com/Azure/Azure-Verified-Modules/issues/423#issuecomment-1857558251 is the best option going forward.

It simplifies the module's expressions, reducing the risk of bugs.

**Comment by MariusStorhaug** [comment]
I just did not fully read what you wrote, so ignore my previous point. 

I get the following error with your suggestion:
```
╷
│ Error: Invalid function argument
│ 
│   on ../../variables.tf line 101, in variable "lock":
│  101:     condition     = var.lock.kind == null || contains(["CanNotDelete", "ReadOnly"], var.lock.kind)
│     ├────────────────
│     │ while calling contains(list, value)
│     │ var.lock.kind is null
│ 
│ Invalid value for "value" parameter: argument must not be null.
```
As the PR i had opened with a suggestion was closed without further discussion, I will open a new with a working suggestion aligning more with your comment.

**Comment by matt-FFFFFF** [comment]
Hi - I don't like the mixed use of default and optional.

I prefer this:

```terraform
    type = object({
      name = optional(string, null)
      kind = optional(string, null)
    })
```

But with this validation:

```terraform
    validation {
      condition     = var.lock.kind == null || try(contains(["CanNotDelete", "ReadOnly"], var.lock.kind), false)
      error_message = "The lock level must be one of: `null`, '\"CanNotDelete\"', or '\"ReadOnly\"'."
    }
```

**Comment by matt-FFFFFF** [comment]
What about if did this instead:

```terraform
type = object({
  kind = string
  name = optional(string, null)
})
default = null
```

This would simplify the expression for creating the lock. A simple null test for the variable.

We could then use a simple validation rule for the `kind` value to be one of the two permitted strings?

**Comment by MariusStorhaug** [comment]
That would also make sense, as I suggested that in the initial PR (#424). What about the concerns regarding making the module code more fragile as you mentioned in the closing note of that PR? Is there a way we can make the implementation less fragile?

**Comment by matt-FFFFFF** [comment]
I will mock it out tomorrow and see what it looks like.

**Comment by matt-FFFFFF** [comment]
I think as long as we prevented the kind from being null as well then this would work.

**Comment by matt-FFFFFF** [comment]
It is possible that I was remembering the managed identity interface, where allowing null would increase the complexity of the expressions.

I guess I was trying to be consistent between locks and MI, however that probably isn't the best approach.

**Comment by matt-FFFFFF** [comment]
Apologies for radio silence here and for the flip flopping.

I have tested this and am happy with the code:


```terraform
variable "lock" {
  type = object({
    kind = string
    name = optional(string, null)
  })
  default = null
  validation {
    error_message = "Lock kind must be either `CanNotDelete` or `ReadOnly`"
    condition     = var.lock != null ? contains(["CanNotDelete", "ReadOnly"], var.lock.kind) : true
  }
}

resource "terraform_data" "test" {
  count = var.lock != null ? 1 : 0
  input = {
    kind = var.lock.kind
    name = coalesce(var.lock.name, "lock-${var.name}")
  }
}
```

**Comment by matt-FFFFFF** [comment]
I will suggest in #489
