### ISSUE TITLE
[Question/Feedback]: Terraform resource module interface `managed_identities`

### ISSUE THREAD

**Issue by MariusStorhaug** [Azure/Azure-Verified-Modules#425]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Add an implementation snippet for modules, so that they can use the managed_identity property.

Suggestion to update: https://azure.github.io/Azure-Verified-Modules/specs/shared/interfaces/#managed-identities -> Terraform section

**Comment by mbilalamjad** [comment]
@matt-FFFFFF interested in your thoughts on this issue and the corresponding PR

**Comment by matt-FFFFFF** [comment]
Have commented on the PR
