### ISSUE TITLE
[Module Proposal]: `avm-res-sql-managedinstance`

### ISSUE THREAD

**Issue by PmeshramPM** [Azure/Azure-Verified-Modules#44]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals

### Terraform or Bicep?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-sql-managedinstance

### Module Details

GH repo name -> terraform-azurerm-avm-res-sql-managedinstance
Please refer to the this CARML Bicep module as it already implements RBAC, Locks, Tags, and Diagnostics Settings

https://github.com/Azure/ResourceModules/tree/main/modules/sql/managed-instance

### Do you want to be the owner of this module?

No

**Comment by herms14** [comment]
@PankajMeshramCSA  I can take this up if no owner yet. Please assign to me

**Comment by PankajMeshramCSA** [comment]
@herms14  - I have assigned the Vnet one to you. Another resource will build this module.

**Comment by PankajMeshramCSA** [comment]
Hi @timchapman  - Thanks for proposing to be an AVM module owner.

We just want to confirm you agree to the below pages that define what module ownership means:

https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions
https://azure.github.io/Azure-Verified-Modules/specs/shared
https://azure.github.io/Azure-Verified-Modules/help-support/module-support
Any questions or clarifications needed let us know.

If you agree please just reply to this issue with the exact sentence below (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"


Thanks
The AVM Core Team

**Comment by PankajMeshramCSA** [comment]
Thanks @timchapman - Assigning this one to you.

**Comment by segraef** [comment]
Hey @PmeshramPM happy to get in touch with you since I'm set (at the moment) as module owner for SQL MI in Bicep and as per [SNFR21](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr21---category-publishing---cross-language-collaboration) we SHOULD collaborate. Let me know your thoughts.

**Comment by jtracey93** [comment]
Hey @segraef  please reach out to @timchapman as he is creating this module for TF for AVM 👍

**Comment by PmeshramPM** [comment]
@timchapman - FYI  - Please pay attention to the module name and GH repo name. I have updated based on the specs

**Comment by timchapman** [comment]
Im not sure I understand?

Thanks,
Tim

**Comment by PmeshramPM** [comment]
@mbilalamjad has given feedback to @timchapman who is working on the feedback.

**Comment by mbilalamjad** [comment]
Reached out to @timchapman offline, this proposal will be updated accordingly here based on his input.

**Comment by mbilalamjad** [comment]
Reached out to @timchapman offline to check-in on any updates or support needed, he or I will update accordingly.

**Comment by kewalaka** [comment]
@mbilalamjad I have customer requirements for this module so I'm going to make a start on it.  If there is activity going on in the background can you please help introduce me to it.  I've had previous conversations with Tim and I don't believe we are duplicating work there.

**Comment by mbilalamjad** [comment]
> @mbilalamjad I have customer requirements for this module so I'm going to make a start on it. If there is activity going on in the background can you please help introduce me to it. I've had previous conversations with Tim and I don't believe we are duplicating work there.

Hey @kewalaka we have a meeting with @timchapman this week, I'll ask him to share any updates here as he's the assigned module owner

**Comment by kewalaka** [comment]
have raised a PR here that illustrates an initial AVM implementation.  Needed this for a customer.

About to use this for deployment testing & will report back

https://github.com/Azure/terraform-azurerm-avm-res-sql-managedinstance/pull/5

cc @mbilalamjad & @timchapman 

Also @segraef - noting your comment above - happy to take on board your version too - if you can share.  I'm not using azapi in this one (am I missing any significant functionality with this decision?)

**Comment by segraef** [comment]
Reached out to @mbilalamjad internally to get in touch with you @kewalaka, thank you for your initiative!

**Comment by kewalaka** [comment]
My fork of this is alive in a customer environment (instance level settings only, they are doing databases via another process).  Base resource is good, going through fine tuning next.

**Comment by kewalaka** [comment]
hi @mbilalamjad & @adammontlake - what is the status here, please?

Regarding [this PR](https://github.com/Azure/terraform-azurerm-avm-res-sql-managedinstance/pull/5) that I mentioned last month - i've just been testing the security alert policies and vulnerability assessment with the storage account resource firewall enabled (as much as possible).

The managed identities are done using azapi because an azurerm provider bug prevents both user & system assigned managed identities.

I've nudged @timchapman on the actual PR issue.
