### ISSUE TITLE
[Module Proposal]: `avm-res-sql-server`

### ISSUE THREAD

**Issue by kewalaka** [Azure/Azure-Verified-Modules#442]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-sql-server

### Module Details

This is for the Azure SQL Database resource, i.e. the Terraform equivalent of #322

I have a start on this module available here: https://github.com/kewalaka/terraform-azurerm-avm-res-sql-server - covering the parent SQL server resource, and two children (elastic pools & databases).

Looking for help to build out the additional child resources, create more validations, & add more E2E tests to the existing set.

### Do you want to be the owner of this module?

No

### Module Owner's GitHub Username (handle)

mbilalamjad

### (Optional) Secondary Module Owner's GitHub Username (handle)

kewalaka

**Comment by mbilalamjad** [comment]
@matebarabas I'm happy to work with @kewalaka on this module, could you please help us with triaging this proposal

**Comment by matebarabas** [comment]
Hi @mbilalamjad,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by mbilalamjad** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by matebarabas** [comment]
Hi @mbilalamjad ,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

Before starting development, please ensure ALL the following requirements are met.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - for naming your module
  - `TelemetryIdPrefix` - for your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repo name and folder path are defined in `RepoURL`
  - Create GitHub teams for module owners and contributors and grant them permissions as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
  - Grant permissions for the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

Check if this module exists in the other IaC language. If so, collaborate with the other owner for consistency. 👍

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published! Please include a link pointing to your PR, once available. 🙏**

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by mbilalamjad** [comment]
Thanks @matebarabas, will get started on the internal process of setting up the repo which should be ready by the time I return from holidays in the first week of Jan and then work with @kewalaka accordingly in getting this module published.

**Comment by mbilalamjad** [comment]
Hey @kewalaka, I've created the official repo, please feel free to do a PR to it

https://github.com/Azure/terraform-azurerm-avm-res-sql-server

**Comment by kewalaka** [comment]
thanks @mbilalamjad - once it is available, what we've done with other AVM collaborations is to create a dev branch on the Azure repo.  

External contributors can then create PRs against azure:dev, which can be PR'ed against azure:main without hitting the issues with the workload identity for the E2E tests, until the internal runners are available.

**Comment by mbilalamjad** [comment]
Update: Repo is still in review, will update here once repo setup is complete

**Comment by kewalaka** [comment]
hi @mbilalamjad just wondered if there is any word on the repo availability, please?

**Comment by mbilalamjad** [comment]
> hi @mbilalamjad Bilal Amjad FTE just wondered if there is any word on the repo availability, please?

Hey @kewalaka, repo setup is finally complete, will be reaching out this week with details for us to get started, appreciate your patience

**Comment by v-xuto** [comment]
Requested to issue: https://github.com/Azure/Azure-Verified-Modules/issues/261
CC: @jongio

**Comment by kewalaka** [comment]
@mbilalamjad any update on this please?

**Comment by v-xuto** [comment]
@mbilalamjad  - Do you have an ETA for this?

**Comment by mbilalamjad** [comment]
Hey @kewalaka, hope you're doing great, apologies for the delay, getting back with an update, the repo setup is complete and public now and I've created a dev branch
https://github.com/Azure/terraform-azurerm-avm-res-sql-server
CC: @v-xuto

**Comment by kewalaka** [comment]
i've just raised a PR against the dev branch because the template version it was based on needs an update. 

I've tagged Bilal in the PR
https://github.com/Azure/terraform-azurerm-avm-res-sql-server/pull/4

I plan to fold in the SQL Server code from my repo after that - it's been a while since i wrote it so i'm anticipating some "re-alignment" work there too.

**Comment by mbilalamjad** [comment]
@PmeshramPM please help with finding a new owner for this module
