### ISSUE TITLE
[Question/Feedback]: Governance on nat-gw module?

### ISSUE THREAD

**Issue by davidkarlsen** [Azure/Azure-Verified-Modules#455]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Is there AVM governance around this module: https://github.com/Azure/terraform-azurerm-avm-res-network-natgateway ?
issues/pr's seem to go stale, the readme seems to be a standard-generated, there are some oddities like invalid diagnostics resources etc.

**Comment by prjelesi** [comment]
I am closing this, handled by @mbilalamjad
