### ISSUE TITLE
[Module Proposal]: `avm/res/compute/image`

### ISSUE THREAD

**Issue by segraef** [Azure/Azure-Verified-Modules#459]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/compute/image

### Module Details

carml > avm

### Do you want to be the owner of this module?

No

**Comment by matebarabas** [comment]
@segraef will migrate this module from CARML, without becoming its owner. The module will be marked as orphaned once the migration is complete, unless someone volunteers to own it.

**If someone wishes to become the owner of this module, please indicate your intent in a comment on this issue.**

**Comment by matebarabas** [comment]
PR: https://github.com/Azure/bicep-registry-modules/pull/742

**Comment by segraef** [comment]
https://github.com/Azure/bicep-registry-modules/pull/795 in draft, waiting for @ChrisSidebotham to see how we proceed with being able to set `knownRegionList` with `Get-AzDeploymentRegion`.

**Comment by segraef** [comment]
Merged and [published](https://github.com/Azure/bicep-registry-modules/actions/runs/7608245568).

**Comment by matebarabas** [comment]
- [x] PR merged; Module published.
- [x] GitHub teams are available and assigned to their parents.
- [x] `CODEOWNERS` file updated.
 
Thank you for your work @segraef! I'm closing this issue now.

Since this module was migrated from CARML without an owner, an orphaned module request was also created: https://github.com/Azure/Azure-Verified-Modules/issues/568
