### ISSUE TITLE
[Module Proposal]: `avm-res-kubernetes-connectedcluster`

### ISSUE THREAD

**Issue by PmeshramPM** [Azure/Azure-Verified-Modules#46]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals

### Terraform or Bicep?

Terraform

### Module Classification?

Resource Module

### Module Name

Module name - avm-res-kubernetes-connectedcluster
GH Repo name - terraform-azurerm-avm-res-kubernetes-connectedcluster

### Module Details

Terraform module for AKS, requirements from customers who wants to accelerate and standardize AKS automated deployments. 

### Do you want to be the owner of this module?

No

**Comment by matt-FFFFFF** [comment]
We have a very mature and successful module already here:

https://github.com/Azure/terraform-azurerm-aks

**Comment by matt-FFFFFF** [comment]
This will be one of the most contentious to migrate given its popularity and the almost certain fact there will be breaking changes

**Comment by jeanchg** [comment]
@mosabami Are you happy to take this? See above comments from Matt.
This would confirm you agree to the below:
	• https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions/
	• https://azure.github.io/Azure-Verified-Modules/specs/shared/
https://azure.github.io/Azure-Verified-Modules/help-support/module-support/

**Comment by mbilalamjad** [comment]
@PmeshramPM since this module already exists in TFVM, could you please either help identify an owner from the TFVM team that might be willing to migrate their module to AVM or another option could be to find an owner from App solution area team

**Comment by PmeshramPM** [comment]
@mbilalamjad  - please see @matt-FFFFFF  comments from above. The existing module is extremely popular and will introduce breaking changes. Lets discuss on a strategy on how do we move ahead with this module without causing disruption.

**Comment by matt-FFFFFF** [comment]
Decision is to leave as is to be maintained by TFVM team and create replacement for AVM

**Comment by mbilalamjad** [comment]
Hi @jchancellor-ms ,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

<br>

> **NOTE**:
>
> - This Module Proposal issue **MUST remain open** until the module is fully developed, tested and published to the relevant registry. **Do NOT close** the issue before the successful publication is confirmed!
> - Once the module is fully developed, tested and published to the relevant registry, and the Module Proposal issue was closed, it **MUST remain closed**.

**Comment by jchancellor-ms** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by mbilalamjad** [comment]
Hi @jchancellor-ms,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

We just want to ask you to double check a few important things and take the next steps before you start the development.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - to name your module
  - `TelemetryIdPrefix` - to be used in your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repository name and folder path are defined in `RepoURL`
  - Create the GitHub teams defined in the `ModuleOwnersGHTeam` and `ModuleContributorsGHTeam` columns and grant them permissions as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
    - In case of a Bicep module, **please let the AVM core team know** when you created these teams, and we'll help you with assigning the necessary permissions as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#grant-permissions---bicep).
    - In case of a Terraform module, follow the instructions [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#grant-permissions---terraform) and assign the necessary permissions.

Grant the right level of permissions for  the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published!** Please include a link pointing to your PR if available. 🙏

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

<br>

> **NOTE**:
>
> - This Module Proposal issue **MUST remain open** until the module is fully developed, tested and published to the relevant registry. **Do NOT close** the issue before the successful publication is confirmed!
> - Once the module is fully developed, tested and published to the relevant registry, and the Module Proposal issue was closed, it **MUST remain closed**.

**Comment by PmeshramPM** [comment]
followed up with @jchancellor-ms  and this is in progress

**Comment by mbilalamjad** [comment]
Reached out to @jchancellor-ms offline to confirm any updates or any supported need, he or I will update accordingly

**Comment by v-xuto** [comment]
Related to issue: https://github.com/Azure/Azure-Verified-Modules/issues/261
CC: @jongio

**Comment by jchancellor-ms** [comment]
I'm starting this module this week, and will only do the connected cluster portion.

**Comment by v-xuto** [comment]
@jchancellor-ms  - Do you have an ETA for this?

**Comment by jchancellor-ms** [comment]
@v-xuto - Targeting the end of the month pending repo business review.

**Comment by jchancellor-ms** [comment]
@v-xuto - I'm getting a test environment set up and working through some testing items.  I had a question, did you need the kubernetes extensions for Arc included in this module as well?

**Comment by mbilalamjad** [comment]
Discussed and agreed with both @jchancellor-ms and the AVM team to pause development of this module till further notice and guidance on Azure Arc related resources is provided from the PG which @jeanchg would be helping with.

**Comment by jeanchg** [comment]
@mbilalamjad @jchancellor-ms after reviewing Azure Arc related scenarios (such as Arc-enabled Kubernetes, which is the service/offering tied to this module proposal and not AKS, as stated above) with @sebassem , we think it's best to close this one for now. The two scenarios that might deserve AVM module proposals would most likely be:
- Arc-enabled VMware for VMware VM self service capabilities through code
- Arc-enabled data services (SQL MI)
But these are not prioritized right now.

**Comment by bahramr** [comment]
This module is marked as done but yet I don't find it in the list of completed modules here https://azure.github.io/Azure-Verified-Modules/indexes/terraform/tf-resource-modules/. Also where is the source code located?
