### ISSUE TITLE
[Question/Feedback]: Clarification on process to initiate GitHub Teams membership

### ISSUE THREAD

**Issue by arnoldna** [Azure/Azure-Verified-Modules#479]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Update the following section to describe the process to request that the newly created teams are added to the respective parent team. https://azure.github.io/Azure-Verified-Modules/specs/shared/#team-memberships

**Comment by matebarabas** [comment]
@arnoldna, could you please further elaborate on your request? The quoted section explicitly explains which teams need to be created, and to which parent teams they need to be assigned. 

Please note that we'd like to avoid repeating content from GH's documentation, such as what are the steps of creating a team.

If you have a specific suggestion, please submit a PR with your edits, and make me a reviewer! Thanks!

<img width="751" alt="image" src="https://github.com/Azure/Azure-Verified-Modules/assets/22733424/a4c8e16e-112d-4969-bdf5-3f212064352f">

**Comment by arnoldna** [comment]
@matebarabas  - What is not clear is how a contributor is to "request the addition of these teams to their respective parent teams". If I remember correctly, the process was to notify you via the proposed module issue that the owner had created the appropriate module owners and contributors teams. I had completed that step over a month ago but received a notification that a team was missing. https://github.com/Azure/Azure-Verified-Modules/issues/296. So then I went back to the specs and it wasn't clear to me and I ended up needed to get some additional help from Erika to fix.

Perhaps we could update the document to just have module owners to use the following link to create their teams. https://github.com/orgs/Azure/new-team. That might avoid some of the confusion where module owners have actually prefaced their team names with "@azure/".

**Comment by matebarabas** [comment]
@arnoldna, thanks for clarifying! Yes, the process has evolved over time; now module owners are expected to initiate the addition of the GH teams to their respective parent teams, whilst the core team still need to approve the paren-child relation on the other end. Adding the link to the documentation is a good idea, so I've submitted this PR with the suggested improvements: #486 

Please let me know if you'd suggest adding/changing anything else. 

Thanks!
