### ISSUE TITLE
[Orphaned Module]: `avm/res/compute/proximity-placement-group`

### ISSUE THREAD

**Issue by matebarabas** [Azure/Azure-Verified-Modules#492]
### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/compute/proximity-placement-group

### Module Details

This module was migrated from CARML by @krbar without an owner. 

**Note**: when someone volunteers to be the owner of this module, please reach out to @krbar to for changing the ownership of the existing GitHub teams as well.

- Module proposal: https://github.com/Azure/Azure-Verified-Modules/issues/452
- PR: https://github.com/Azure/bicep-registry-modules/pull/762

### Do you want to be the new owner of this module?

No

**Comment by jeetgarg** [comment]
Hey @matebarabas 
As suggested, i would like to be the owner of this module.

**Comment by matebarabas** [comment]
Hi @jeetgarg,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by jeetgarg** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by matebarabas** [comment]
Hi @jeetgarg,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

We just want to ask you to double check a few important things.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- You must be the owner of the GitHub teams as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
- Please check that your name has been updated in the module index page (this should happen shortly after you confirmed ownership).

You can now take ownership of this module and start improving it as needed! ✅ Happy coding! 🎉

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by matebarabas** [comment]
Hi @krbar, 

@jeetgarg has kindly volunteered to own this module. Can you please help him to take ownership over the 2 GH teams you've provisioned for this module? 

Please let me know when it's done, so we can close this issue.

Thank you!

**Comment by krbar** [comment]
@matebarabas FYI: both related GitHub teams are now transferred to @jeetgarg

**Comment by matebarabas** [comment]
Thanks for confirming! Closing this issue now.
