### ISSUE TITLE
[Question/Feedback]: should non-enumerable object variables be nullable?

### ISSUE THREAD

**Issue by kewalaka** [Azure/Azure-Verified-Modules#493]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Ref: https://azure.github.io/Azure-Verified-Modules/specs/terraform/#id-tfnfr20---category-code-style---declare-nullable--false-when-its-possible

> Nullable SHOULD be set to false for collection values (e.g. sets, maps, lists) when using them in loops. However for scalar values like string and number, a null value MAY have a semantic meaning and as such these values are allowed.

Should ``nullable=false`` only apply for complex types that are enumerable?

What benefit does it confer for objects, for example, the customer managed key from the documentation has this:

```terraform
variable "customer_managed_key" {
  type = object({
    key_vault_resource_id              = string
    key_name                           = string
    key_version                        = optional(string, null)
    user_assigned_identity_resource_id = optional(string, null)
  })
  default = {}
}
```

This doesn't work.

The AVM template fixes this by making the first two optional, which works, but not valid (I understand why this has to be done when nullable=false & the default is 'empty'.

Instead, for non-enumerable objects, what if null was the default?  Then, this would work:

```terraform
variable "customer_managed_key" {
  type = object({
    key_vault_resource_id              = string
    key_name                           = string
    key_version                        = optional(string, null)
    user_assigned_identity_resource_id = optional(string, null)
  })
  default     = null
  description = <<DESCRIPTION
This variable allows you to specify the details of a customer-managed key to be used for encryption.

- `key_vault_resource_id` - (Required) The resource ID of the Azure Key Vault containing the customer-managed key.
- `key_name` - (Required) The name of the customer-managed key in the Azure Key Vault.
- `key_version` - (Optional) The version of the customer-managed key to be used.
- `user_assigned_identity_resource_id` - (Optional) The resource ID of the user-assigned managed identity that will be used to access the customer-managed key.
DESCRIPTION
}
```

This also applies to ``lock`` & ``managed_identities``.

**Comment by matt-FFFFFF** [comment]
I think it depends and there is nuance here.

However in general is a null value conveys intent - typically, "I don't want this", then yes using null is useful.

In this way a nested object is the same as a scalar value.

However there are times, such as the MI interface where allowing null seems to add complexity. Maybe we need to rethink that.

**Comment by matt-FFFFFF** [comment]
Adding in @MariusStorhaug as this is pertinent to another discussion.

For managed identity, the way this is constructed currently means allowing null for the variable makes things more complex.

However for locks there seems to be a case for allow null.

**Comment by matt-FFFFFF** [comment]
See suggestion here:

https://github.com/Azure/Azure-Verified-Modules/pull/489#issuecomment-1895228752

I agree that the CMK interface could do with updating as well

**Comment by matt-FFFFFF** [comment]
Agreed. See comments on PR
