### ISSUE TITLE
[Module Proposal]: `avm/res/dev-test-lab/lab`

### ISSUE THREAD

**Issue by ahmadabdalla** [Azure/Azure-Verified-Modules#508]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/dev-test-lab/lab

### Module Details

Migration from CARML
https://github.com/ahmadabdalla/bicep-registry-modules/tree/users/ahmad/4412_devTestLab

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

ahmadabdalla

**Comment by matebarabas** [comment]
Hi @ahmadabdalla,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by ahmadabdalla** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by ahmadabdalla** [comment]
I will be working on this issue in the next 10 days.

**Comment by matebarabas** [comment]
- [x] Module published. PR: https://github.com/Azure/bicep-registry-modules/pull/1035
- [x] GitHub teams are available and assigned to their parents.
- [x] `CODEOWNERS` file updated.
 
Thank you for your work @ahmadabdalla!
