### ISSUE TITLE
[Module Proposal]: avm/res/compute/proximity-placement-group

### ISSUE THREAD

**Issue by jeetgarg** [Azure/Azure-Verified-Modules#513]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/compute/proximity-placement-group

### Module Details

This module would be migrated from CARML.

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

jeetgarg

**Comment by matebarabas** [comment]
@jeetrag, thank you for submitting this module proposal. Please note this module has already been [migrated from CARML](https://github.com/Azure/Azure-Verified-Modules/issues/452) without an owner. 

If you'd like to **become its owner** - which would be much appreciated! - please indicate it in a comment on the related "orphaned module" issue: https://github.com/Azure/Azure-Verified-Modules/issues/492

Thank you!
