### ISSUE TITLE
[Module Proposal]: `avm-ptn-cicd-agents-and-runners`(tf)

### ISSUE THREAD

**Issue by jaredfholgate** [Azure/Azure-Verified-Modules#520]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [x] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Pattern Module

### Module Name

avm-ptn-cicd-agents-and-runners

### Module Details

This pattern module will deploy self-hosted Azure DevOps Agents and / or GitHub Runners allowing selection of one of the following compute options:

- Azure Container Instance
- Azure Container Apps
- Azure Kubernetes Service
- Azure Virtual Machine Scale Set

It will eventually include options for:

- Ephemeral instances
- Scaling
- Private networking

For iteration 1 it will support Azure Container Instance and others will be added later. 

>NOTE: It may make sense to split the 4 different compute options into 4 different modules, please let me know if you prefer that approach and I will add 3 more proposals.

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

jaredfholgate

### (Optional) Secondary Module Owner's GitHub Username (handle)

luke-taylor

**Comment by PmeshramPM** [comment]
Hi @jaredfholgate 

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by jaredfholgate** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by PmeshramPM** [comment]
Hi @jaredfholgate,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

Before starting development, please ensure ALL the following requirements are met.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - for naming your module
  - `TelemetryIdPrefix` - for your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repo name and folder path are defined in `RepoURL`
  - Create GitHub teams for module owners and contributors and grant them permissions as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
  - Grant permissions for the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

Check if this module exists in the other IaC language. If so, collaborate with the other owner for consistency. 👍

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published! Please include a link pointing to your PR, once available. 🙏**

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by luke-taylor** [comment]
@jaredfholgate how is the module negotiated with `avm-ptn-cicd-bootstrap` ?

**Comment by mbilalamjad** [comment]
Hey @luke-taylor, @jaredfholgate do we need to consolidate/reconcile this module proposal with https://github.com/Azure/Azure-Verified-Modules/issues/416, thoughts ?

**Comment by jaredfholgate** [comment]
> Hey @luke-taylor Luke Taylor FTE, @jaredfholgate Jared Holgate FTE do we need to consolidate/reconcile this module proposal with #416, thoughts ?

Hi. Luke and I have discussed. #416 just requires some updates. It will leverage this module. This module is designed to serve a wider purpose outside of just IaC bootstrapping. But, the driver to get it done is the Accelerator and the module Luke proposed, so hope to get working on it ASAP.

**Comment by kewalaka** [comment]
there's some interesting pre-work in this space, I'll call out a few initiatives that might be worth looking at:

https://github.com/microsoft/symphony

& John Folberth's ones, which is what I used as the basis for the commercial ones I'm unable to share: 

https://github.com/JFolberth/TheYAMLPipelineOne

**Comment by mbilalamjad** [comment]
Requested @jaredfholgate to share an update here.

**Comment by jaredfholgate** [comment]
This is waiting on my time to free up. I really want to do this soon as it is needed for improvements to Accelerators. I have a meeting about Accelerator re-factoring to de-couple the bootstrap this week. If that gets a nod, then I'll be able to merge it and move onto this soon after.

**Comment by BlakeWills** [comment]
Hey @jaredfholgate - I've started working on a module for ADO Agents using Azure Container Apps here: https://github.com/BlakeWills/terraform-azurerm-avm-ptn-cicd-agents-and-runners-ca

It still needs some work, is there a repo for this module where I can create a PR to start the ball rolling, and get some initial feedback?

**Comment by jaredfholgate** [comment]
> Hey @jaredfholgate - I've started working on a module for ADO Agents using Azure Container Apps here: https://github.com/BlakeWills/terraform-azurerm-avm-ptn-cicd-agents-and-runners-ca
> 
> It still needs some work, is there a repo for this module where I can create a PR to start the ball rolling, and get some initial feedback?

Hi @BlakeWills. As mentioned on email. The repo is here and you should have access to create a branch: https://github.com/Azure/terraform-azurerm-avm-ptn-cicd-agents-and-runners

**Comment by jaredfholgate** [comment]
@mbilalamjad and @PmeshramPM This module has now been released if you'd like to close this issue and update the index. Thanks
