### ISSUE TITLE
[Module Proposal]: `avm-res-servicebus-namespace(tf)`

### ISSUE THREAD

**Issue by PmeshramPM** [Azure/Azure-Verified-Modules#528]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-servicebus-namespace

### Module Details

AVM Resource module for Service Bus Namespace

### Do you want to be the owner of this module?

No

**Comment by bryansan-msft** [comment]
Hello @mbilalamjad and @matebarabas, I would like to be the owner of this module and help with its development.

**Comment by ShivaniThadiyan** [comment]
Hello - I'm interested in the development of this module via Terraform as an Contributor. Thanks!

**Comment by mbilalamjad** [comment]
Hi @bryansan-msft,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by mbilalamjad** [comment]
> Hello - I'm interested in the development of this module via Terraform as an Contributor. Thanks!

@ShivaniThadiyan since @bryansan-msft requested first to own the module, we'll proceed with him, you could be a co-owner and collaborate with him to contribute to this one or look for a new one in the "Looking for Owners" section [here](https://github.com/orgs/Azure/projects/529).

**Comment by bryansan-msft** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by mbilalamjad** [comment]
Hi @bryansan-msft ,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

Before starting development, please ensure ALL the following requirements are met.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - for naming your module
  - `TelemetryIdPrefix` - for your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repo name and folder path are defined in `RepoURL`
  - Create GitHub teams for module owners and contributors and grant them permissions as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
  - Grant permissions for the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

Check if this module exists in the other IaC language. If so, collaborate with the other owner for consistency. 👍

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published! Please include a link pointing to your PR, once available. 🙏**

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by bryansan-msft** [comment]
I have had problems getting started contributing. I have a meeting on Thursday with our assigned mentor where I will address these issues.

**Comment by bryansan-msft** [comment]
@mbilalamjad I have opened a PR (Azure/terraform-azurerm-avm-res-servicebus-namespace#1) as the code is ready to be reviewed. 

I'm currently facing issues with the runners of the organization as they are missing. Could you help me with that? It's the only thing that is missing to have everything ready to be deployed

**Comment by bryansan-msft** [comment]
> @mbilalamjad I have opened a PR ([Azure/terraform-azurerm-avm-res-servicebus-namespace#1](https://github.com/Azure/terraform-azurerm-avm-res-servicebus-namespace/pull/1)) as the code is ready to be reviewed.
> 
> I'm currently facing issues with the runners of the organization as they are missing. Could you help me with that? It's the only thing that is missing to have everything ready to be deployed

Any help regarding to this? @Azure/avm-core-team-technical-terraform

**Comment by mbilalamjad** [comment]
@bryansan-msft checking with the team on this, will update as I hear any update

**Comment by bryansan-msft** [comment]
> @bryansan-msft checking with the team on this, will update as I hear any update

@mbilalamjad any news? I'm still blocked without being able to publish the module. @matebarabas could you lend me a little help here?

**Comment by matebarabas** [comment]
@bryansan-msft, I'll reach out to you internally.

**Comment by bryansan-msft** [comment]
Hello all, the module is published and ready to be used by everyone. We can proceed to close this ticket
https://registry.terraform.io/modules/Azure/avm-res-servicebus-namespace/azurerm/latest
