### ISSUE TITLE
[Module Proposal]: `avm-res-logic-workflow(tf)`

### ISSUE THREAD

**Issue by PmeshramPM** [Azure/Azure-Verified-Modules#530]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-logic-workflow

### Module Details

AVM Resource module for Logic workflow

### Do you want to be the owner of this module?

No

**Comment by bakrish** [comment]
Hi @mbilalamjad @PmeshramPM  , I'd like to volunteer for this module ownership/development. Thanks!

**Comment by mbilalamjad** [comment]
Hi @bakrish ,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by bakrish** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by mbilalamjad** [comment]
Reached out to @bakrish, he or I will update here accordingly

**Comment by bakrish** [comment]
I'm working on this - hoping to complete ASAP

**Comment by bakrish** [comment]
Still working on this,  hoping to complete soon

**Comment by bakrish** [comment]
The initial review of this module is complete and the module has been published to the registry. Requesting AVM team to close this module proposal and mark the module available in the module index.
