### ISSUE TITLE
[Module Proposal]: `avm-res-compute-diskencryptionset`(tf)

### ISSUE THREAD

**Issue by davidkarlsen** [Azure/Azure-Verified-Modules#534]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-compute-diskencryptionset

### Module Details

* take in param for keyvault resource-id
* take in param for optional key-id, if not present, create an auto-rotating key
* do the required role-assignments
* create the DES

### Do you want to be the owner of this module?

No

**Comment by mbilalamjad** [comment]
Reached out internally to Akash Choudhary who is interested in this module, will proceed to assign ownership of this module to him once he responds here.

**Comment by Akashc0807** [comment]
Hello I Will be taking the ownership of this module.

**Comment by mbilalamjad** [comment]
Hi @Akashc0807,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by Akashc0807** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by mbilalamjad** [comment]
Hi @Akashc0807,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

Before starting development, please ensure ALL the following requirements are met.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - for naming your module
  - `TelemetryIdPrefix` - for your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repo name and folder path are defined in `RepoURL`
  - Create GitHub teams for module owners and contributors and grant them permissions as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
  - Grant permissions for the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

Check if this module exists in the other IaC language. If so, collaborate with the other owner for consistency. 👍

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published! Please include a link pointing to your PR, once available. 🙏**

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by ShivaniThadiyan** [comment]
Team I want to contribute in this module as a contributor. Please let me know if you need any help.

**Comment by mbilalamjad** [comment]
Reached out to @Akashc0807 and @ShivaniThadiyan to share an update here

**Comment by Akashc0807** [comment]
Work is in progress, Will update by starting of the next week that is 11th march.

**Comment by Akashc0807** [comment]
Work is in progress, Delivery of this module is expected by 29th

**Comment by Akashc0807** [comment]
Work is in progress, Delivery of this module is expected by 7th April

**Comment by Akashc0807** [comment]
Work in progress.

**Comment by Akashc0807** [comment]
It will be closed within the week.

**Comment by PmeshramPM** [comment]
removing the needs attention on this one, @Akashc0807 is planning to work on the hack week
