### ISSUE TITLE
[Orphaned Module]: `avm/res/databricks/access-connector`

### ISSUE THREAD

**Issue by matebarabas** [Azure/Azure-Verified-Modules#542]
### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/databricks/access-connector

### Module Details

This module was migrated from CARML by @segraef without an owner. 

**Note**: when someone volunteers to be the owner of this module, please reach out to @segraef for changing the ownership of the existing GitHub teams as well.

- Module proposal: https://github.com/Azure/Azure-Verified-Modules/issues/462
- PR: https://github.com/Azure/bicep-registry-modules/pull/791

### Do you want to be the new owner of this module?

No

**Comment by matebarabas** [comment]
Hi @clintgrove,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by matebarabas** [comment]
@clintgrove, please respond by repeating the quoted text above to allow us to finish the transition of this module's ownership. Thanks!

**Comment by clintgrove** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by matebarabas** [comment]
Hi @clintgrove,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

We just want to ask you to double check a few important things.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- You must be the owner of the GitHub teams as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
- Please check that your name has been updated in the module index page (this should happen shortly after you confirmed ownership).

You can now take ownership of this module and start improving it as needed! ✅ Happy coding! 🎉

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by matebarabas** [comment]
@arnoldna, can you please work with @clintgrove to hand over the GH teams as well as to make sure the `ORPHANED.MD` file is deleted from the module, [here](https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/databricks/access-connector), as described in step 5 [here](https://azure.github.io/Azure-Verified-Modules/help-support/issue-triage/avm-issue-triage/#when-a-new-owner-is-identified). **Please let me know in a comment here when this step is done, so that we can close this issue.** Thank you!

**Comment by segraef** [comment]
Handed over
@Azure/avm-res-databricks-accessconnector-module-contributors-bicep
@Azure/avm-res-databricks-accessconnector-module-owners-bicep

Don't forget to remove `ORPHANED.MD` from the respective module directory, thanks!

**Comment by matebarabas** [comment]
> @segraef Sebastian Gräf FTE, can you please work with @clintgrove Clint Grove FTE to hand over the GH teams as well as to make sure the `ORPHANED.MD` file is deleted from the module, [here](https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/databricks/access-connector), as described in step 5 [here](https://azure.github.io/Azure-Verified-Modules/help-support/issue-triage/avm-issue-triage/#when-a-new-owner-is-identified). **Please let me know in a comment here when this step is done, so that we can close this issue.** Thank you!

@clintgrove, there seems to be a related PR already: https://github.com/Azure/bicep-registry-modules/pull/1003

Please let me know once this is merged, so we can close this issue. Thanks!

**Comment by krbar** [comment]
The PR https://github.com/Azure/bicep-registry-modules/pull/1003 is merged

**Comment by matebarabas** [comment]
@krbar, @clintgrove, thanks for confirming. Closing this issue now.
