### ISSUE TITLE
[Module Proposal]: `avm-res-security-pricing`(tf)

### ISSUE THREAD

**Issue by cshea-msft** [Azure/Azure-Verified-Modules#551]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-security-pricing

### Module Details

Looking to create a module that turns on features in Defender for Cloud Service Plans and features

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

cshea-msft

**Comment by cshea-msft** [comment]
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/security_center_subscription_pricing

**Comment by PmeshramPM** [comment]
Hi @cshea-msft ,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by cshea-msft** [comment]
"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

**Comment by cshea-msft** [comment]
After playing around with it and looking into the APIs Im not sure if this would be a good terraform module. It basically deploys Defender for CLoud features but some of the features like Defender for Cloud is missing some the of api extentions so would need Policies and then a way to remeditate the policy to deploy. 
 
So I was thinking should we remove this one for now until the apis are able to deploy all the extensions. 

cc @mbilalamjad

**Comment by mbilalamjad** [comment]
Thanks @cshea-msft for the comments, makes sense and closing this proposal for now, we can revisit in the future.
