### ISSUE TITLE
[Orphaned Module]: `avm/res/databricks/workspace`

### ISSUE THREAD

**Issue by matebarabas** [Azure/Azure-Verified-Modules#552]
### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/databricks/workspace

### Module Details

This module was migrated from CARML by @segraef without an owner. 

**Note**: when someone volunteers to be the owner of this module, please reach out to @segraef to for changing the ownership of the existing GitHub teams as well.

- Module proposal: https://github.com/Azure/Azure-Verified-Modules/issues/463
- PR: https://github.com/Azure/bicep-registry-modules/pull/792

### Do you want to be the new owner of this module?

No

### Module Owner's GitHub Username (handle)

clintgrove

**Comment by clintgrove** [comment]
@matebarabas . You mentioned that I should leave a comment here. "[@clintgrove](https://github.com/clintgrove), thank you for volunteering to help with this module! This is a duplicate of [#552](https://github.com/Azure/Azure-Verified-Modules/issues/552) - can you please leave a comment on this one @mentioning me? Thank you!" 

Put me down as owner on this module. Let me know if there is anything else you need from me

**Comment by matebarabas** [comment]
Hi @clintgrove,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by clintgrove** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by segraef** [comment]
> I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

Thanks @clintgrove, I'm starting the handover.

**Comment by segraef** [comment]
Handed over
@Azure/avm-res-databricks-workspace-module-contributors-bicep
@Azure/avm-res-databricks-workspace-module-owners-bicep

**Comment by matebarabas** [comment]
> I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

Hi @clintgrove,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

We just want to ask you to double check a few important things.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- You must be the owner of the GitHub teams as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
- Please check that your name has been updated in the module index page (this should happen shortly after you confirmed ownership).

You can now take ownership of this module and start improving it as needed! ✅ Happy coding! 🎉

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by matebarabas** [comment]
As @segraef confirmed handing over the related GitHub teams, I'm closing this issue now. @clintgrove, please reach out to the AVM core team internally if you need any additional help. Thank you again for volunteering to own this module! 👍
