### ISSUE TITLE
[Orphaned Module]: `avm/res/net-app/net-app-account`

### ISSUE THREAD

**Issue by matebarabas** [Azure/Azure-Verified-Modules#553]
### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/net-app/net-app-account

### Module Details

This module was migrated from CARML by @segraef without an owner. 

**Note**: when someone volunteers to be the owner of this module, please reach out to @segraef to for changing the ownership of the existing GitHub teams as well.

- Module proposal: https://github.com/Azure/Azure-Verified-Modules/issues/466
- PR: https://github.com/Azure/bicep-registry-modules/pull/800

### Do you want to be the new owner of this module?

No

### Module Owner's GitHub Username (handle)

fbinotto

**Comment by fbinotto** [comment]
Hi @matebarabas I would like to be owner of this module. Thanks

**Comment by matebarabas** [comment]
Hi @fbinotto,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by matebarabas** [comment]
@fbinotto, please don't forget to respond to this issue by repeating the text quoted above. Thank you!

**Comment by fbinotto** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by matebarabas** [comment]
Hi @fbinotto,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

We just want to ask you to double check a few important things.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- You must be the owner of the GitHub teams as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
- Please check that your name has been updated in the module index page (this should happen shortly after you confirmed ownership).

You can now take ownership of this module and start improving it as needed! ✅ Happy coding! 🎉

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by matebarabas** [comment]
@segraef, can you please work with @fbinotto on handing over the GitHub teams that were created for this module? Thank you!

**Comment by segraef** [comment]
Handed teams over to @fbinotto:

- @Azure/avm-res-netapp-netappaccount-module-owners-bicep 
- @Azure/avm-res-netapp-netappaccount-module-contributors-bicep

Don't forget to remove `ORPHANED.MD` from the root directory of the module.

**Comment by matebarabas** [comment]
Thanks @segraef! Yes, that would've been my next point. :)

@fbinotto, **please let me know when you're done with the deletion of the `ORPHANED.md` file** in the [module's folder](https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/compute/image), as described in step 5 [here](https://azure.github.io/Azure-Verified-Modules/help-support/issue-triage/avm-issue-triage/#when-a-new-owner-is-identified). [There's a PR for this already](https://github.com/Azure/bicep-registry-modules/pull/977). Thanks!

**Comment by matebarabas** [comment]
`ORPHANED.md` deleted: https://github.com/Azure/bicep-registry-modules/pull/1237
