### ISSUE TITLE
[Module Proposal]: `avm-res-cognitiveservices-account`

### ISSUE THREAD

**Issue by kewalaka** [Azure/Azure-Verified-Modules#555]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-cognitiveservices-account

### Module Details

I have a sample starter implementation in the style of AVM here;

https://github.com/kewalaka/terraform-azurerm-avm-res-cognitiveservices-account/

### Do you want to be the owner of this module?

No

**Comment by lonegunmanb** [comment]
Hi @kewalaka thanks for opening this pr, our team intends to promote OpenAI TF module and we'd like to use an AVM module, so I'd like to create a cognitive account module, and migrate code in [`terraform-azurerm-openai`](https://github.com/Azure/terraform-azurerm-openai) into this new module. Would you mind let me create this new module, so we can avoid duplicated work? Thanks a lot!

And I believe the module's name should be `terraform-azurerm-avm-res-cognitive-account`, right?

**Comment by mbilalamjad** [comment]
@lonegunmanb appreciate your response to @kewalaka comment above

**Comment by lonegunmanb** [comment]
@kewalaka I've composed one and I think it's ready for a review: https://github.com/lonegunmanb/terraform-azurerm-avm-res-cognitiveservices-cognitive-account

>Would we keep the yor tags? I like them, be a good addition to the spec.

Yor tags will be the foundation of AVM, yes we will support them very soon.

**Comment by mbilalamjad** [comment]
Closing this module proposal as duplicate and in favor of [this one](https://github.com/Azure/Azure-Verified-Modules/issues/571) raised by @lonegunmanb
