### ISSUE TITLE
[Module Proposal]: `avm/res/relay/namespace`

### ISSUE THREAD

**Issue by segraef** [Azure/Azure-Verified-Modules#561]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/relay/namespace

### Module Details

CARML to AVM

### Do you want to be the owner of this module?

No

**Comment by matebarabas** [comment]
@segraef will migrate this module from CARML, without becoming its owner. The module will be marked as orphaned once the migration is complete, unless someone volunteers to own it.

**If someone wishes to become the owner of this module, please indicate your intent in a comment on this issue.**

**Comment by segraef** [comment]
In development.

**Comment by krbar** [comment]
@matebarabas Please assign this issue to me. It's agreed with @segraef.
