### ISSUE TITLE
[Question/Feedback]: Needs a supporting documentation for creating synapse  link for cosmos db using terraform 

### ISSUE THREAD

**Issue by vamsee33** [Azure/Azure-Verified-Modules#574]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

 Is there any Microsoft supported document to create azure synapse link for cosmos DB account using terraform/az api? I could see enabling analytical store in account level and container level and linked service  externally gives capability to make analytical activities but need a Microsoft document to use terraform/az api to create synapse linked service for cosmos db.
```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by mbilalamjad** [comment]
Hi @vamsee33 this isn't strictly an AVM issue therefore we'll proceed with closing this but would recommend you look at the [this](https://github.com/hashicorp/terraform-provider-azurerm/issues/10419)
