### ISSUE TITLE
[Module Proposal]: `avm-res-compute-hostgroup`

### ISSUE THREAD

**Issue by chianw** [Azure/Azure-Verified-Modules#577]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-compute-hostgroup

### Module Details

Module to create a dedicated host group and also dedicated hosts within the host group.

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

chianw

**Comment by mbilalamjad** [comment]
Hi @chianw,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by chianw** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by mbilalamjad** [comment]
Hi @chianw,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

We just want to ask you to double check a few important things.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- You must be the owner of the GitHub teams as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
- Please check that your name has been updated in the module index page (this should happen shortly after you confirmed ownership).

You can now take ownership of this module and start improving it as needed! ✅ Happy coding! 🎉

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by chianw** [comment]
Hi I've not started development on this module as I'm still working on the other terraform-azurerm-avm-res-network-privatednszone module

**Comment by mbilalamjad** [comment]
Thanks for the update @chianw appreciate it

**Comment by chianw** [comment]
Hi I've started some work on this module but still testing it

**Comment by prjelesi** [comment]
@sharmilamusunuru

**Comment by prjelesi** [comment]
@SkouRene

**Comment by mbilalamjad** [comment]
The initial review of this module is complete, and the module has been published to the registry. Requesting AVM team to close this module proposal and mark the module available in the module index.
Terraform Registry Link: https://registry.terraform.io/modules/Azure/avm-res-compute-hostgroup/azurerm/latest
GitHub Repo Link: https://github.com/Azure/terraform-azurerm-avm-res-compute-hostgroup

**Comment by jeanchg** [comment]
this module ownership is being transitioned to @WenAI2020
