### ISSUE TITLE
[Module Proposal]: `avm-res-network-expressroutecircuit`

### ISSUE THREAD

**Issue by khushal08** [Azure/Azure-Verified-Modules#589]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-network-expressroutecircuit

### Module Details

Terraform AVM module for expressroute circuit. 

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

khushal08

**Comment by mbilalamjad** [comment]
Hi @khushal08,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by khushal08** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by mbilalamjad** [comment]
Hi @khushal08,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

Before starting development, please ensure ALL the following requirements are met.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - for naming your module
  - `TelemetryIdPrefix` - for your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repo name and folder path are defined in `RepoURL`
  - Create GitHub teams for module owners and contributors and grant them permissions as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
  - Grant permissions for the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

Check if this module exists in the other IaC language. If so, collaborate with the other owner for consistency. 👍

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published! Please include a link pointing to your PR, once available. 🙏**

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by adammontlake** [comment]
@khushal08 - if you need assistance, happy to collaborate

**Comment by mbilalamjad** [comment]
Reached out to @khushal08, he or I will come back with an update

**Comment by khushal08** [comment]
In development.

**Comment by mbilalamjad** [comment]
@khushal08 just a FYI, Express route circuits seemed to be covered by the below pattern module, would recommend re-evaluating if this resource module is needed or does the below pattern module suffice
https://registry.terraform.io/modules/Azure/avm-ptn-vnetgateway/azurerm/latest

**Comment by prjelesi** [comment]
Hi @khushal08 please continue to work on this as resource module.

**Comment by adammontlake** [comment]
The resource is in active development, will be ready for review very soon.

**Comment by adammontlake** [comment]
@prjelesi - PR ready for review: https://github.com/Azure/terraform-azurerm-avm-res-network-routetable/pull/7

**Comment by adammontlake** [comment]
@prjelesi / @khushal08 - sorry I commented on this thread by accident, when I clearly meant to comment on the Route Table task :O 
However, verry happy to help with this module development if required!

**Comment by khushal08** [comment]
ExpressRoute Circuit module is ready to be published to terraform registry. We have tested it on our internal subscription with ER access. 
Here is PR link - https://github.com/Azure/terraform-azurerm-avm-res-network-expressroutecircuit/pull/24

@Azure/avm-core-team @mbilalamjad @prjelesi @matt-FFFFFF @jaredfholgate Can you please help review?

CC: @adammontlake

**Comment by jchancellor-ms** [comment]
I have completed my initial development of the module and I would like to request a review of my module before publishing it to the terraform registry. The latest code is in a PR titled [AVM-Review-PR](https://github.com/Azure/terraform-azurerm-avm-res-network-expressroutecircuit/pull/29) on the module repo and all checks on that PR are passing.

**Comment by mbilalamjad** [comment]
Since this module is already published and available in [Terraform registry](https://registry.terraform.io/modules/Azure/avm-res-network-expressroutecircuit/azurerm/latest) so closing the module proposal, further discussion should continue on the module repo
