### ISSUE TITLE
[Feedback]: Broken link for Azure Firewall

### ISSUE THREAD

**Issue by vjmanda** [Azure/Azure-Verified-Modules#591]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Broken link for Terraform Registry - Azure Firewall in [Terraform Resource Modules](https://azure.github.io/Azure-Verified-Modules/indexes/terraform/tf-resource-modules/) page.

**Comment by mbilalamjad** [comment]
@vjmanda thank you for raising the issue, this is fixed now
