### ISSUE TITLE
[Module Proposal]: `avm-ptn-hpc-slurm-ai`

### ISSUE THREAD

**Issue by jchancellor-ms** [Azure/Azure-Verified-Modules#593]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Pattern Module

### Module Name

terraform-azurerm-avm-ptn-hpc-slurm-ai

### Module Details

Pattern module adapting code found in Jesse's blog entry - https://techcommunity.microsoft.com/t5/azure-high-performance-computing/training-large-ai-models-on-azure-using-cyclecloud-slurm/ba-p/3775454.

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

jchancellor-ms

### (Optional) Secondary Module Owner's GitHub Username (handle)

hannah-leland

**Comment by mbilalamjad** [comment]
@jchancellor-ms, thank you for proposing this module! As this is categorized as a pattern module, its approval will require a more thorough assessment. The AVM core team will get back to you soon.

**Comment by mbilalamjad** [comment]
Hi @jchancellor-ms,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by jchancellor-ms** [comment]
@mbilalamjad - I'm working with the HPC workloads team to see if they still want this module as they determine some functionality is already covered by AzHop project.

**Comment by mbilalamjad** [comment]
As per offline discussion, closing as @jchancellor-ms won't be proceeding forward on this for now and will re-open later as and when he is ready to proceed.
