### ISSUE TITLE
[Orphaned Module]: ADF is orphaned

### ISSUE THREAD

**Issue by clintgrove** [Azure/Azure-Verified-Modules#597]
### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/databricks/workspace

### Module Details

I can take ownership of this. I have experience doing bicep ADF deployment

### Do you want to be the new owner of this module?

Yes

### Module Owner's GitHub Username (handle)

clintgrove

**Comment by matebarabas** [comment]
@clintgrove, thank you for volunteering to help with this module! This is a duplicate of https://github.com/Azure/Azure-Verified-Modules/issues/431 - can you please leave a comment on this one @mentioning me? Thank you!

I'm going to close this one now. #wontfix
