### ISSUE TITLE
[Question/Feedback]: Bicep - better document what a Waf-aligned test should include

### ISSUE THREAD

**Issue by eriqua** [Azure/Azure-Verified-Modules#599]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

We should better document what a WAF aligned test case should include, although it may be a gray zone for some properties.
As a rule of thumb, it should include the minimum set of properties making the resource compliant to Waf. In Bicep, this in general means to comply with PSRule.
Also, in general, waf aligned test should not cover locks or rbac shared interfaces.
This issue is about elaborating more on the documentation for waf aligned test spec

**Comment by mbilalamjad** [comment]
@eriqua just double checking, has this been discussed and addressed already?

**Comment by eriqua** [comment]
Hey @mbilalamjad. Yes, I recently updated the test description as part of another issue in AVM specs, but forgot to close this one. Ref https://github.com/Azure/Azure-Verified-Modules/pull/852

Although it can be additionally improved, for me this issue can be closed
