### ISSUE TITLE
[Module Proposal]: avm-res-hpc-azure-batch

### ISSUE THREAD

**Issue by bsantacruzms** [Azure/Azure-Verified-Modules#602]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

terraform-azurerm-avm-res-hpc-azure-batch

### Module Details

The module will allow users to deploy Azure Batch utilizing an Azure Storage Account and Log Analytics. 

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

bsantacruzms

**Comment by mbilalamjad** [comment]
@bsantacruzms thank you for the module proposal, could I please ask you to review the [resource](https://azure.github.io/Azure-Verified-Modules/specs/shared/#terraform-resource-module-naming) and [pattern ](https://azure.github.io/Azure-Verified-Modules/specs/shared/#terraform-pattern-module-naming) naming convention and confirm the naming of the module and whether it would be a [resource or pattern module](https://azure.github.io/Azure-Verified-Modules/specs/shared/module-classifications/)

**Comment by bsantacruzms** [comment]
Thank you @mbilalamjad for checking on that. I will ping you offline for clarification.

**Comment by mbilalamjad** [comment]
Closing this module proposal in favor of the [previous ](https://github.com/Azure/Azure-Verified-Modules/issues/523)one created which will be assigned to @bsantacruzms
