### ISSUE TITLE
[Module Proposal]: `avm-res-devcenter-devcenter`

### ISSUE THREAD

**Issue by kewalaka** [Azure/Azure-Verified-Modules#606]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-devcenter-devcenter

### Module Details

This is a module proposal for the Azure Dev Center.  I've got a start on the parent resource and intend to continue on with child resources

https://github.com/kewalaka/terraform-azurerm-avm-res-devcenter-devcenter

I'm not sure if it should be 'devcenter' or 'dev-center'.

### Do you want to be the owner of this module?

No

**Comment by mbilalamjad** [comment]
Thank you @kewalaka for the proposal, we will locate an owner for the module and update accordingly.

**Comment by mbilalamjad** [comment]
@kewalaka this is a duplicate of a previous [module proposal](https://github.com/Azure/Azure-Verified-Modules/issues/335), will close this one in favor of the previous one, lets continue the conversation over there

**Comment by kewalaka** [comment]
Oops missed that, no probs👍
