### ISSUE TITLE
[Module Proposal]: `avm-res-network-virtualnetwork` (tf)

### ISSUE THREAD

**Issue by herms14** [Azure/Azure-Verified-Modules#62]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals

### Check this module doesn't already exist in another project that is being evolved into AVM

- [X] I have checked for that this module doesn't already exist in CARML or TFVM

### Terraform or Bicep?

Terraform

### Module Classification?

Resource Module

### Module Name

Module name - avm-res-network-virtualnetwork
GH repo name - terraform-azurerm-avm-res-network-virtualnetwork

### Module Details

creation of terraform module for virtual networks aligning to AVM standards

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username

herms14

**Comment by PankajMeshramCSA** [comment]
Hi @herms14 -

Thanks for requesting/proposing to be an AVM module owner.

We just want to confirm you agree to the below pages that define what module ownership means:

- https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions
- https://azure.github.io/Azure-Verified-Modules/specs/shared
- https://azure.github.io/Azure-Verified-Modules/help-support/module-support

Any questions or clarifications needed let us know.

If you agree please just reply to this issue with the exact sentence below (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Two more points 
1. I have changed the naming to align with the naming convention for Terraform. 
2. The module does exists currently in Terraform verified module and can be migrated to AVM specifications. Please see this ->  
  https://github.com/Azure/terraform-azurerm-network

Thanks

The AVM Core Team

**Comment by herms14** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by PankajMeshramCSA** [comment]
@herms14 - I will sort this out today.

**Comment by PankajMeshramCSA** [comment]
@herms14  - Assigned to you. To re-confirm this is Resource Module for Vnet

**Comment by herms14** [comment]
This has been completed. However repo is still in Private and is pending business review - https://ossmsft.visualstudio.com/Reviews/_workitems/edit/48113

**Comment by PmeshramPM** [comment]
@herms14 - FYI - Please pay attention to the module name and GH repo name. I have updated based on the specs

**Comment by herms14** [comment]
@PmeshramPM module is now public and available on TF registry

**Comment by mbilalamjad** [comment]
@PmeshramPM @jtracey93 given that the module has been moved to "Done", does this need to remain open or could be closed?

**Comment by PmeshramPM** [comment]
@mbilalamjad - This is documented here - https://azure.github.io/Azure-Verified-Modules/help-support/issue-triage/avm-issue-triage/  - Please see the Post-Development issue management

**Comment by mbilalamjad** [comment]
Thanks @PmeshramPM for the response, I'm aware of that part of the documentation and had reviewed it before hand, was wondering if there was a specific reason, like any pending work that needs to be done on this module, since this is still open and the documented post-development steps hadn't been followed. In case no, then I'll go ahead and take care of those steps and close this issue.

CC: @matt-FFFFFF, @jtracey93, @herms14

**Comment by PmeshramPM** [comment]
@mbilalamjad - Although this module is published, I see Hermes was requesting a follow up review from @matt-FFFFFF on 14th Nov after solving the issue on the Subnet level. 
@herms14 - could you please confirm if everything is finished on this one and we can close this one.

**Comment by herms14** [comment]
@PMEds28  Im wating for Matt to approve the PR

**Comment by mbilalamjad** [comment]
Thank you so much @herms14 for your contribution

Closing as module has been published to terraform registry below
https://registry.terraform.io/modules/Azure/avm-res-network-virtualnetwork/azurerm/latest

Further discussion on this module including issues & PRs to take please on its repo below
https://github.com/Azure/terraform-azurerm-avm-res-network-virtualnetwork
