### ISSUE TITLE
[Module Proposal]: `avm/res/network/azure-firewall`

### ISSUE THREAD

**Issue by hundredacres** [Azure/Azure-Verified-Modules#626]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/network/azure-firewall

### Module Details

Migrating from CARML: https://github.com/Azure/ResourceModules/tree/main/modules/network/azure-firewall

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

hundredacres

**Comment by matebarabas** [comment]
@hundredacres, thanks for volunteering to own this module! Before we continue, there are two important things to note:
- I corrected the name according to the naming convention (there was a missing '-' in 'azure-firewall'
- As per the current [migration plans](https://azure.github.io/Azure-Verified-Modules/indexes/bicep/bicep-resource-modules/#planned-modules) captured in the module indexes, this module is set to be owned and migrated by @rahalan (Rainer Halanek). The [Module Proposal] issue, however, hasn't been created for this module yet. That said, I'd imagine you could either agree with Rainer that you'll become the owner, or you could settle on a co-ownership model. **Could you please discuss this internally and leave a comment with what you concluded on?** Thank you!

**Comment by rahalan** [comment]
@hundredacres , thank you for your support. For sure you can be module owner. Please ping me on Teams, so I can help you with the migration of the CARML module.

**Comment by matebarabas** [comment]
Thank you @rahalan for confirming. @hundredacres, let's do the "handshake process"! 😉

**Comment by matebarabas** [comment]
Hi @hundredacres,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by matebarabas** [comment]
@hundredacres, if you agree, please respond by repeating the quoted text above. Thank you!

**Comment by hundredacres** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by hundredacres** [comment]
@matebarabas Rainer and I met and came up with an action plan. He's going to finish the migration and submit the PR and I'll own the module afterwards. I've started completing some of the other admin tasks, such as creating the Github teams for both Owner and Contributor. Rainer hopes to have an initial PR next week.

**Comment by matebarabas** [comment]
PR: https://github.com/Azure/bicep-registry-modules/pull/1079

**Comment by matebarabas** [comment]
- [x] Module published.
- [x] GitHub teams are available and assigned to their parents.
- [x] `CODEOWNERS` file updated.
 
Thank you for your work @rahalan! I'm closing this issue now.
