### ISSUE TITLE
[Module Proposal]: `oracle_db_at_azure` (tf)

### ISSUE THREAD

**Issue by sihbher** [Azure/Azure-Verified-Modules#630]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-oracledb

### Module Details

Terraform module to deploy Oracle DB@Azure

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

sihbher

**Comment by mbilalamjad** [comment]
@sihbher thank you for the module proposal, could I please request you to update the name of the module per the AVM spec on naming convention here for [Resource](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-rmnfr1---category-naming---module-naming) and [Pattern](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-pmnfr1---category-naming---module-naming)

**Comment by sihbher** [comment]
Hi @mbilalamjad, sure.

According to naming convention it would be: avm-res-database-oracledb

is that correct?

**Comment by mbilalamjad** [comment]
Actually no, it needs to be based on the following format, can you please confirm the resource provider for Oracle DB from this [link ](https://learn.microsoft.com/en-us/azure/templates/)?
avm-res-<resource provider>-<ARM resource type>

**Comment by prjelesi** [comment]
HI @sihbher any update from you side?

**Comment by sihbher** [comment]
Hey sorry, I didn't see the response, I will contact the PM to ask the resource provider and resource type, I will let you know
