### ISSUE TITLE
[Module Proposal]: `avm-res-resources-resourcegroup`

### ISSUE THREAD

**Issue by kevball2** [Azure/Azure-Verified-Modules#633]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-resources-resourcegroup

### Module Details

base resource group module for terraform

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

jfolberth

### (Optional) Secondary Module Owner's GitHub Username (handle)

kevball2

**Comment by JFolberth** [comment]
I am a MS employee and willing to own this and partner with @kevball2 on submission

**Comment by mbilalamjad** [comment]
Hi @JFolberth,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by JFolberth** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by mbilalamjad** [comment]
Hi @JFolberth,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

Before starting development, please ensure ALL the following requirements are met.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - for naming your module
  - `TelemetryIdPrefix` - for your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repo name and folder path are defined in `RepoURL`
  - Create GitHub teams for module owners and contributors and grant them permissions as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
  - Grant permissions for the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

Check if this module exists in the other IaC language. If so, collaborate with the other owner for consistency. 👍

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published! Please include a link pointing to your PR, once available. 🙏**

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by mbilalamjad** [comment]
Hey @JFolberth appreciate if you could work with @kevball2 on this

**Comment by JFolberth** [comment]
@mbilalamjad We have touched based and are actively collaborating

**Comment by kevball2** [comment]
It appears the repository that was setup for the module has been removed? https://github.com/Azure/terraform-azurerm-avm-res-resources-resourcegroup

The project is no longer available to update.

**Comment by JFolberth** [comment]
@kevball2 try again ...I moved it to public which would be required for the grept job to pick it up and is a required step anyway.

**Comment by kevball2** [comment]
thanks @JFolberth, I can see the repo now, but have no rights to modify the contents. As an external contributor is the expectation that I submit a PR from my fork of the project to the Microsoft owned AVM module repo? I could not find any confirmation in the current AVM contributor documentation

**Comment by kevball2** [comment]
thanks @JFolberth, I can see the repo but have not rights to modify the contents. As an external contributor is the expetantion that I submit a PR from my fork of the project to the Microsoft owned AVM module repo? I could not find any confirmation in the current AVM contributor documentation

**Comment by JFolberth** [comment]
This is ready to be published. Requesting review
https://github.com/Azure/terraform-azurerm-avm-res-resources-resourcegroup/issues/23
https://github.com/Azure/terraform-azurerm-avm-res-resources-resourcegroup/pull/43

**Comment by kevball2** [comment]
@mbilalamjad  Is there an ETA when this can be reviewed?

**Comment by kevball2** [comment]
@Azure/avm-core-team-technical-terraform, @mbilalamjad .  Any ETA on a review for this module?

**Comment by JFolberth** [comment]
The initial review of this module is complete, and the module has been published to the registry. Requesting AVM team to close this module proposal and mark the module available in the module index.
Terraform Registry Link: https://registry.terraform.io/modules/Azure/avm-res-resources-resourcegroup/azurerm/latest
GitHub Repo Link: https://github.com/Azure/terraform-azurerm-avm-res-resources-resourcegroup
