### ISSUE TITLE
[Module Proposal]: `avm/ptn/chat-with-your-data-solution-accelerator`

### ISSUE THREAD

**Issue by segraef** [Azure/Azure-Verified-Modules#640]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Bicep

### Module Classification?

Pattern Module

### Module Name

avm/ptn/chat-with-your-data-solution-accelerator

### Module Details

https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator

### Do you want to be the owner of this module?

No

**Comment by segraef** [comment]
First draft is here: https://github.com/segraef/bicep-registry-modules/tree/feat/chat-with-your-data-solution-accelerator/avm/ptn/chat-with-your-data-solution-accelerator

**Comment by matebarabas** [comment]
@segraef, thank you for proposing this module! As this is categorized as a pattern module, its approval will require a more thorough assessment. The AVM core team will get back to you soon. Thank you for your patience!

**Comment by segraef** [comment]
Leaving this for a later point in time.
