### ISSUE TITLE
[Module Proposal]: `express-route-circuit`

### ISSUE THREAD

**Issue by adammontlake** [Azure/Azure-Verified-Modules#641]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

express-route-circuit

### Module Details

Terraform module for creating an ER circuit

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

adammontlake

**Comment by mbilalamjad** [comment]
Thanks @adammontlake for the proposal, we already have this module in development, please feel free to combine your powers with the module owner there and co-own and contribute to the development of this module.
https://github.com/Azure/Azure-Verified-Modules/issues/589
