### ISSUE TITLE
[Module Proposal]: `avm-res-insights-components`

### ISSUE THREAD

**Issue by JFolberth** [Azure/Azure-Verified-Modules#643]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-insights-components

### Module Details

Application Insights for Terraform. Imagine this would be used either as a standalone or more so when developing pattern modules.

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

JFolberth

**Comment by mbilalamjad** [comment]
@JFolberth thank you for the proposal, there was an existing proposal for the same on which we need an owner, I'll close this one in favor of the previous proposal and get the process of assigning the module to you there.
https://github.com/Azure/Azure-Verified-Modules/issues/337
