### ISSUE TITLE
[Module Proposal]: AVD Session Host Setup

### ISSUE THREAD

**Issue by moisesjgomez** [Azure/Azure-Verified-Modules#66]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals

### Check this module doesn't already exist in another project that is being evolved into AVM

- [X] I have checked for that this module doesn't already exist in CARML or TFVM

### Terraform or Bicep?

Bicep

### Module Classification?

Pattern Module

### Module Name

avm-ptn-desktopvirtualization-sessionhostsetup

### Module Details

Module would deploy VMs and consequently set them up with AVD host pool

For reference: 
https://github.com/Azure/avdaccelerator/blob/main/workload/bicep/modules/avdSessionHosts/deploy.bicep

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username

moisesjgomez

**Comment by jtracey93** [comment]
Hi @moisesjgomez,

Thanks for the proposal. 

I think this should actually be a pattern module instead of a resource module, as per the classification definitions here: https://azure.github.io/Azure-Verified-Modules/specs/shared/module-classifications/

Could you please amend the module proposal and module name if you agree and we will triage further 👍

**Comment by moisesjgomez** [comment]
@jtracey93 I agree with that. I've updated the PR. Let me know if anything else. Thank you.

**Comment by danycontre** [comment]
Agree on session hosts module being a pattern, the module will not call resource specific to session hosts but call other resource modules that make up a session host (VM, VM extension, AMA, NIC, Disk, etc.).

**Comment by danycontre** [comment]
@danycontre

**Comment by jtracey93** [comment]
Thanks @danycontre. 

@moisesjgomez Can you please edit the module proposal to align to the pattern module naming please?

**Comment by danycontre** [comment]
@moisesjgomez let's schedule some time to put together the list of resource modules and patterns that we will submit/contribute for AVD LZA.

**Comment by matebarabas** [comment]
@moisesjgomez , @danycontre , I'll ping you internally to help structuring and preparing this work.

**Comment by matebarabas** [comment]
Duplicate of #147

**Comment by danycontre** [comment]
@matebarabas agree, this item needed to be closed as new ones were submitted.
