### ISSUE TITLE
[Module Proposal]: `avm/ptn/network/virtual-network-peering`

### ISSUE THREAD

**Issue by mbilalamjad** [Azure/Azure-Verified-Modules#660]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Bicep

### Module Classification?

Pattern Module

### Module Name

avm/ptn/network/virtual-network-peering

### Module Details

Bicep equivalent of [Terraform Module](https://github.com/Azure/Azure-Verified-Modules/issues/163)

### Do you want to be the owner of this module?

No

**Comment by herms14** [comment]
@mbilalamjad this appears to be a duplicate. Im already working on a vnet peering module - https://github.com/Azure/Azure-Verified-Modules/issues/163

**Comment by kewalaka** [comment]
just looking at existing proposed network pattern modules as I have an idea for one - and the scope of this isn't clear to me?  is peering really deserving of a pattern module?

**Comment by matebarabas** [comment]
Closing this as not planned. This functionality is implemented in the [VNET module](https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/network/virtual-network).

Note: the TF equivalent of this module proposal was also just closed as not planned - https://github.com/Azure/Azure-Verified-Modules/issues/163
