### ISSUE TITLE
[Module Proposal]: `avm/ptn/aca-lza/hosting-environment`

### ISSUE THREAD

**Issue by kpantos** [Azure/Azure-Verified-Modules#669]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Bicep

### Module Classification?

Pattern Module

### Module Name

avm/ptn/aca-lza/hosting-environment

### Module Details

This Azure Container Apps pattern module represents an Azure Container Apps deployment aligned with the cloud adoption framework implementing industry proven practices, such as those presented in [Azure landing zones](https://learn.microsoft.com/azure/cloud-adoption-framework/ready/landing-zone/) guidance in the Cloud Adoption Framework, owned and operated by a workload team. This avm pattern module provides a production ready reference implementation of a containerized apps hosting environment with Azure Container Apps.

![aca-avm](https://github.com/Azure/Azure-Verified-Modules/assets/1714480/de7190c1-0260-45cf-8e2b-9e9d9641847c)

As part of this pattern module the following services will be deployed:

- A resource group (Spoke) to deploy all resources
- A VNet with 4 subnets hosting the services
- An internal Azure container apps environment
- An Azure key vault exposed through a private endpoint
- An Azure Container Registry reachable through a private endpoint
- Azure Application Gateway or Azure Front Door to expose applications hosted at Azure Container Apps
- A Virtual Machine serving as a jump box for the locked down environment

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

kpantos

**Comment by matebarabas** [comment]
This module will take a dependency on https://github.com/Azure/Azure-Verified-Modules/issues/604.

**Comment by matebarabas** [comment]
Hi @kpantos,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by kpantos** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by matebarabas** [comment]
Hi @kpantos,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

Before starting development, please ensure ALL the following requirements are met.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - for naming your module
  - `TelemetryIdPrefix` - for your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repo name and folder path are defined in `RepoURL`
  - Create GitHub teams for module owners and contributors and grant them permissions as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
  - Grant permissions for the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

Check if this module exists in the other IaC language. If so, collaborate with the other owner for consistency. 👍

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published! Please include a link pointing to your PR, once available. 🙏**

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by matebarabas** [comment]
@kpantos, thanks again for proposing this module! Please don't forget to add the discussed details to the description, including the architectural diagram, and bill of materials. Thanks!

**Comment by matebarabas** [comment]
- [x] Module published.
- [x] GitHub teams are available and assigned to their parents.
- [x] `CODEOWNERS` file updated.
 
Thank you for your work @kpantos! I'm closing this issue now.
