### ISSUE TITLE
[Module Proposal]: `avm/res/web/serverfarm`

### ISSUE THREAD

**Issue by tsc-buddy** [Azure/Azure-Verified-Modules#67]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals

### Check this module doesn't already exist in another project that is being evolved into AVM

- [X] I have checked for that this module doesn't already exist in CARML or TFVM

### Terraform or Bicep?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/web/serverfarm

### Module Details

A resource module for an ASP (Microsoft.web/serverfarm). Put name on original index spreadsheet of carml modules back in may, so happy to own and refactor to avm specs.

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username

tsc-buddy

**Comment by jtracey93** [comment]
Hi @tsc-buddy,

Thanks for the proposal. 

However, it seems these modules already exist in CARML and therefore are being migrated by the CARML team to AVM already in a bigger bang style approach. As we have documented here: https://azure.github.io/Azure-Verified-Modules/faq/#carmltfvm-to-avm-evolution-details

You can see this here in the indexes: https://azure.github.io/Azure-Verified-Modules/indexes/bicep/bicep-resource-modules/

Also an app service is made up of many different resources from an API perspective and there's not just a single "app service" module. As you can see in the above index for all the `avm-res-web-xxxxx` modules we will be migrating from CARML. 

Therefore could you let us know whether you'd like to be the owner of one or all of these `avm-res-web-xxxxx` modules or do you wish to actually create a pattern module that wraps all of these resources into one, optionally you can await us to migrate them from CARML to build the resource modules as per this shared pattern module requirement https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-pmnfr2---category-composition---use-resource-modules-to-build-a-pattern-module

Let us know

**Comment by tsc-buddy** [comment]
Hey @jtracey93 - Understood on the Bicep CARML side of things. Prior to the github issues being the place to pick up modules, I put my name down in the spreadsheet following some discussions in early august with Pankaj and Charlie for _Microsoft.Web/serverfarms_ & _Microsoft.Web/sites_ as there were no names against them. 

My thinking on App services resource module was as sites cannot be deployed without serverfarms (unless you ref an existing one) and serverfarms with no sites are kind of useless it would make sense to have a resource module deploys the site and its required resource.

A pattern module for app service environments may be appropriate though, given that would be three separate resource types under the web RP.

**Comment by tsc-buddy** [comment]
details of module updated based on discussions with @jtracey93 - hopefully that proposal aligns better.

**Comment by jtracey93** [comment]
@jeanchg or @matebarabas can we validate the module names and if we have a current owner of the CARML equivalent, if it exists?

If not lets send the confirmation to @tsc-buddy to confirm ownership statement 👍

**Comment by matebarabas** [comment]
@tsc-buddy, I'll reach out to you internally to discuss the right strategy for this work.

**Comment by matebarabas** [comment]
Hi @tsc-buddy 

Thanks for requesting/proposing to be an AVM module owner.

We just want to confirm you agree to the below pages that define what module ownership means:

- https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions
- https://azure.github.io/Azure-Verified-Modules/specs/shared
- https://azure.github.io/Azure-Verified-Modules/help-support/module-support

Any questions or clarifications needed let us know.

If you agree please just reply to this issue with the exact sentence below (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks

The AVM Core Team

**Comment by tsc-buddy** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by tsc-buddy** [comment]
@matebarabas - I also have a colleague who is happy to co-own these. So when we sync next, let me know the process to onboard them.

**Comment by prjelesi** [comment]
@matebarabas i will handle this together with other conversion request. @tsc-buddy i will share with you upgrade checklist that you can use to continuo your work.

**Comment by matebarabas** [comment]
@tsc-buddy, thanks for opening this request and volunteering! I'll shortly send you a final confirmation that you're good to go. 

Also, @prjelesi is going to reach out to you separately and help with the next steps, given this is a migrate from CARML scenario. 

> @matebarabas - I also have a colleague who is happy to co-own these. So, when we sync next, let me know the process to onboard them.

Please let me know who the other person would be; we can capture him/her as a secondary owner.

Thank you!

**Comment by matebarabas** [comment]
Hi @tsc-buddy ,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities.

We just want to ask you to double check a few important things before you start the development.

Please visit the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page of your module and use the following values explicitly as provided there:

- `ModuleName`
- `TelemetryIdPrefix`
- `ModuleOwnersGHTeam` and `ModuleContributorsGHTeam`
- Repository name and folder path defined in `RepoURL`

You can now start the development of this module! Happy coding! 🎉

Please respond to this comment, once your module is ready to be published!

Any further questions or clarifications needed, let us know.

Thanks,

The AVM Core Team

**Comment by matebarabas** [comment]
@tsc-buddy,

Due to a recent change in the naming convention for AVM Bicep modules, this module is getting an updated name.

The title and description of this GH issue has been updated to reflect the name change. **Please make sure you adhere to the new naming convention when publishing your module!** 

Please see the new naming convention in:
- [RMNFR1](https://azure.github.io/Azure-Verified-Modules/specs/shared/#bicep-resource-module-naming) for resource modules
- [PMNFR1](https://azure.github.io/Azure-Verified-Modules/specs/shared/#bicep-pattern-module-naming) for pattern modules

Please note that the Telemetry ID and name of GitHub Teams haven't changed.

If you feel uncertain about any details, please check the [Bicep modules indexes](https://azure.github.io/Azure-Verified-Modules/indexes/bicep/).

**Comment by matebarabas** [comment]
- To be migrated from CARML: https://github.com/Azure/ResourceModules/tree/main/modules/web/serverfarm
- Requested by the AZD team: #261 
CC: @jongio

**Comment by matebarabas** [comment]
- [x] Module published: [#700](https://github.com/Azure/bicep-registry-modules/pull/700/files)
- [x] GitHub teams are available and assigned to their parents.
- [x] `CODEOWNERS` file updated.
 
Thank you for your work @tsc-buddy! I'm closing this issue now.
