### ISSUE TITLE
[Module Proposal]: `avm/ptn/lza/hub`

### ISSUE THREAD

**Issue by kpantos** [Azure/Azure-Verified-Modules#670]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Bicep

### Module Classification?

Pattern Module

### Module Name

avm/ptn/lza/hub

### Module Details

This LZA hub pattern module represents a Hub deployment for a Hub and Spoke architecture aligned with the cloud adoption framework implementing industry proven practices, such as those presented in [Azure landing zones](https://learn.microsoft.com/azure/cloud-adoption-framework/ready/landing-zone/) guidance in the Cloud Adoption Framework, owned and operated by a workload team. This hub pattern module provides a common hub reference implementation for all the LZA pattern modules.

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

kpantos

**Comment by matebarabas** [comment]
@kpantos, thank you for proposing this module! As this is categorized as a pattern module, its approval will require a more thorough assessment. The AVM core team will get back to you soon. Thank you for your patience!

**Comment by matebarabas** [comment]
This module won't be implemented as there's another one covering for hub-networking already being implemented: https://github.com/Azure/Azure-Verified-Modules/issues/604.
#wontfix
