### ISSUE TITLE
[Module Proposal]: avm-res-network-rulecollectiongroup

### ISSUE THREAD

**Issue by cshea-msft** [Azure/Azure-Verified-Modules#672]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-network-firewall_policy_rule_collection_group

### Module Details

Want to create a Rule Collection Group module. This is how you create rules for Azure Firewall Policy

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall_policy_rule_collection_group

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

cshea-msft

**Comment by mbilalamjad** [comment]
@cshea-msft thanks for the module proposal, wondering if this could be covered with in the avm-res-network-firewallpolicy module or exist separately

**Comment by cshea-msft** [comment]
I think it could be, I saw it has a separate module but if you think it should be part of the firewall policy I'm happy to add it to that.  your call bilal.

**Comment by mbilalamjad** [comment]
Let me discuss with the team and also have a look across how they are doing it in Bicep and come back to you

**Comment by cshea-msft** [comment]
sounds good! thanks!

**Comment by mbilalamjad** [comment]
Hey @cshea-msft I had a look across the equivalent [bicep module ](https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/network/firewall-policy) for firewall policy and it seems to cover rule collection group with in it, I would suggest we do the same here for terraform and coincidently you own the module for firewall policy so let me know your thoughts.

**Comment by cshea-msft** [comment]
Yeah that is no problem. I think it would be a good way to approach it. I will update the firewall policy module. We can close this PR. Thanks!
