### ISSUE TITLE
[Orphaned Module]: `avm/res/purview/account`

### ISSUE THREAD

**Issue by matebarabas** [Azure/Azure-Verified-Modules#701]
### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/purview/account

### Module Details

This module was migrated from CARML by @krbar without an owner. 

**Note**: when someone volunteers to be the owner of this module, please reach out to @krbar to for changing the ownership of the existing GitHub teams as well.

- Module proposal: https://github.com/Azure/Azure-Verified-Modules/issues/546
- PR: https://github.com/Azure/bicep-registry-modules/pull/1053

### Do you want to be the new owner of this module?

No

### Module Owner's GitHub Username (handle)

hundredacres

**Comment by hundredacres** [comment]
@matebarabas I can take ownership of this and will work on it during Hackathon.

**Comment by matebarabas** [comment]
Hi @hundredacres,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by hundredacres** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by matebarabas** [comment]
Hi @hundredacres,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

We just want to ask you to double check a few important things.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- You must be the owner of the GitHub teams as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
- Please check that your name has been updated in the module index page (this should happen shortly after you confirmed ownership).

You can now take ownership of this module and start improving it as needed! ✅ Happy coding! 🎉

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by matebarabas** [comment]
@krbar, as @hundredacres has kindly taken ownership of this module, can you please hand over the related GH teams to him, as well as help with un-orphaning this module by removing the orphaned.md file and re-generating the readme? Thank you!

**Comment by krbar** [comment]
@matebarabas the teams are transferred to @hundredacres and the PR for removal of ORPHANED.md is prepared (as draft). Once you update the module index, we will be able to complete the PR, now it's still listed as orphaned and the validation fails:

https://github.com/Azure/bicep-registry-modules/pull/3213

**Comment by matebarabas** [comment]
Thank you, @krbar! The index has just been updated, so your tests should pass now. Please let me know when the PR is merged. Thanks!

**Comment by krbar** [comment]
@matebarabas  PR is merged

**Comment by matebarabas** [comment]
Thank you, @krbar,

- [x] Module published.
- [x] GitHub teams are available and assigned to their parents.
- [x] `CODEOWNERS` file updated.
 
I'm closing this issue now.
