### ISSUE TITLE
[Question/Feedback]: External resource associations on a resource module

### ISSUE THREAD

**Issue by jchancellor-ms** [Azure/Azure-Verified-Modules#729]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Generally, the guidance for resource modules is that they should only implement the resource type defined by the module definition or child resource types of the primary resource type. However, there are certain cases where it is preferable to associate external resources using their ID to provide additional functionality that is not directly defined by the primary resource type but exists in a 1:1 or many:1 relationship with the resource. In these cases the association resource is technically not a primary or child resource type so this potentially falls in a gray area.  

As an example, a virtual machine can exist in the backend pool of a load-balancer and depending on how an organization sets up their separation of duties, it may be preferable or necessary for the VM to own placing itself in a load-balancer back-end pool even when another team owns the Load Balancer creation.  

Opening this issue to clarify whether it is acceptable to create relationships with other resource types as part of a resource module in situations where two conditions are met.  The primary resource type has a 1:1 or 1:many relationship with the associated resource type, and there is a reasonable expectation that a separation of duties would occur.

It is expected that implementation in the resource module would be limited to the creation of associations or links to the associated resource.

**Comment by matebarabas** [comment]
@jchancellor-ms, I just want to replay for the record, that your question was coming from a Terraform angle, and that in the conversation @ChrisSidebotham explained that this issue doesn't apply / applies differently in case of Bicep modules. Could you gents please chime in and clarify if it's just for TF, or if it's not, then give an example for Bicep as well? Thanks!

**Comment by jchancellor-ms** [comment]
@matebarabas - I can confirm this is true for Terraform.  I would need to lean on Chris as to how Bicep handles relationships between two resources.

**Comment by ChrisSidebotham** [comment]
In general, for the bicep side the association is done on the primary resource e.g. NSG & Subnets, this is done on subnets due to how ARM actions this. 

In the example given, for virtual machines we have the module for the NIC which is a separate resource module. Functionally a NIC does nothing on its own without being attached to a resource. Therefore, We can add the NIC to the backend pool of a load balancer from **both the NIC and Load balancer Modules** as this then gives the NIC a function. Hope this is clear?

**Comment by mbilalamjad** [comment]
@jchancellor-ms the team had a discussion around this and also looked into how this is being handled in bicep and in particular the bicep VM module, the guidance would be to let the primary resource handle the associations e.g. back-end pool is configured as part of the load-balancer primarily so we let a VMs NIC be associated to that backend pool through the load balancer module, let us know if that makes sense

**Comment by jchancellor-ms** [comment]
Based on Chris's response above, I'm think we might be in agreement, but saying it differently.  In the Bicep case, it appears that associations can be handled on either end of the association (NIC or LoadBalancer).  In this case, since we don't have a NIC resource module, I'm effectively handling the NIC and VM resource modules. (as a BICEP comparable).  Because of this, to mirror functionality I should (I think) allow users of the Terraform VM module to configure NIC associations to the various linked resources. (ASG, NSG, App GW pool, LB pool, LB NAT Rules, etc.)  We can discuss in the office hours to see if we're in agreement.
________________________________

**Comment by matt-FFFFFF** [comment]
Think this can be closed now
