### ISSUE TITLE
[Feedback]: A repo linter and pull request generator tool

### ISSUE THREAD

**Issue by lonegunmanb** [Azure/Azure-Verified-Modules#74]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

We have a bunch of very detailed policies about what MUST be done and MUST NOT be done, but it'll be impossible for humans to follow them and check all policies manually.

I found a handy tool called [SecureRepo](https://app.stepsecurity.io/securerepo) which could scan our github repo and submit a corresponding pull request to harden the CI's security.

I also found [RepoLinter](https://github.com/todogroup/repolinter) which could let us define the linting rules that check a github repo, and give suggestions on how to fix the issues it finds.

We might have hundreds of repos in the future, and our policies might keep changing and involving, it'll be impossible for us to keep all repos update-to-date manually.

Maybe we should consider a tool that combines them two, we can lint whether a repo meets our requirements, and if it's not, this tool could open a remediation pull request.

**Comment by jtracey93** [comment]
Hey @lonegunmanb,

Completely agree, as we discussed earlier in the week and we will follow up in our syncs to get this resolved.

**Comment by mbilalamjad** [comment]
@jtracey93  just circling back on this one to check if there are any actions that could be taken at this point in time to address the feedback and close the issue ?

**Comment by jtracey93** [comment]
This is being worked on by @lonegunmanb in a tool called `grept`

**Comment by lonegunmanb** [comment]
I'm closing this issue since we have [`grept`](https://github.com/Azure/grept) now.
