### ISSUE TITLE
[Question]: Make child modules available for direct usage 

### ISSUE THREAD

**Issue by timdhaeyer** [Azure/Azure-Verified-Modules#747]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

I have a case where I conditionally need to create child items (like key-vault secrets) via my Bicep files. At this moment, the child modules are not open for direct usage. Since I'm transitioning from CARML to use AVM, this would make my transition easier. In CARML, the child modules are available for direct usage.

So my question is, will it soon be possible to use any (relevant) child module directly? Mainly thinking about secrets, sb topics, sb queues, ...

**Comment by matebarabas** [comment]
@AlexanderSehr, I do remember that there was another issue somewhere, where you addressed this topic in depth, but I couldn't find it. Can you please chime in / help out?

**Comment by matebarabas** [comment]
I just found it: https://github.com/Azure/Azure-Verified-Modules/issues/578

**Comment by matebarabas** [comment]
That'd be a correct short assessment of the situation. 😊 But as you saw on the related issue where @AlexanderSehr explained all things in details, there're reasons behind. I'm going to close this issue for now. Please let us know if you have any further questions/comments related to this topic. Thanks!

**Comment by AlexanderSehr** [comment]
> So in short. "Don't count on it soon" 😄

Sadly.
