### ISSUE TITLE
[Question/Feedback]: Set-AVMModule hangs

### ISSUE THREAD

**Issue by hundredacres** [Azure/Azure-Verified-Modules#751]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Recently, running Set-AVMModule on my local machine hangs when processing files. I don't see any recent commits that would have changed much about this function and I'm not sure how to troublshoot.

`PS /Users/matthewschmitt/GIT/bicep-registry-modules> Set-AVMModule -ModuleFolderPath avm/ptn/network/hub-networking -ThrottleLimit 10
Building [avm-network/hub-networking/main.bicep]
/Users/matthewschmitt/GIT/bicep-registry-modules/avm/ptn/network/hub-networking/main.bicep(6,7) : Warning no-unused-params: Parameter "name" is declared but never used. [https://aka.ms/bicep/linter/no-unused-params]
Generating readme for [avm-network/hub-networking/main.bicep]
WARNING: Resource type [hubnetworking] does not exist in the API / is custom. Falling back to it as default.
WARNING: No resource type like [Microsoft.Network/hubnetworking] found in template. Falling back to it as identifier.
Processed [0/1] files [0% complete                                                                              ]
`

and it'll just sit there.

**Comment by matebarabas** [comment]
@Azure/avm-core-team-technical-bicep, could one of you please help @hundredacres (Matt Schmitt) with this issue?

**Comment by AlexanderSehr** [comment]
Hey @hundredacres, this is a duplication of https://github.com/Azure/bicep-registry-modules/issues/1315.

In short, the formatter of the new Bicep version breaks the tool. I already worked on a fix - yet need to finish testing and then get the PR merged.

**Comment by eriqua** [comment]
Hello @hundredacres, just a heads-up for today we enabled legacy (v1) formatting with [this PR](https://github.com/Azure/bicep-registry-modules/pull/1331). 
That is a temporary workaround meanwhile a fix is implemented for the readme generator to support bicep v2 formatting.

**Comment by hundredacres** [comment]
I pulled the latest changes and now gettting a new error:

`PS /Users/matthewschmitt/GIT/bicep-registry-modules> Set-AVMModule -ModuleFolderPath avm/ptn/network/hub-networking
Building [avm-network/hub-networking/main.bicep]
/Users/matthewschmitt/GIT/bicep-registry-modules/avm/ptn/network/hub-networking/main.bicep(6,7) : Warning no-unused-params: Parameter "name" is declared but never used. [https://aka.ms/bicep/linter/no-unused-params]
Generating readme for [avm-network/hub-networking/main.bicep]
WARNING: Resource type [hubnetworking] does not exist in the API / is custom. Falling back to it as default.
WARNING: No resource type like [Microsoft.Network/hubnetworking] found in template. Falling back to it as identifier.
InvalidOperation: /Users/matthewschmitt/GIT/bicep-registry-modules/avm/utilities/pipelines/sharedScripts/Set-ModuleReadMe.ps1:1327
Line |
1327 |          $moduleDeploymentPropertyIndent = ([regex]::Match($rawBicepEx …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot index into a null array.
Processed [0/1] files [0% complete`

**Comment by AlexanderSehr** [comment]
> I pulled the latest changes and now gettting a new error:
> 
> `PS /Users/matthewschmitt/GIT/bicep-registry-modules> Set-AVMModule -ModuleFolderPath avm/ptn/network/hub-networking Building [avm-network/hub-networking/main.bicep] /Users/matthewschmitt/GIT/bicep-registry-modules/avm/ptn/network/hub-networking/main.bicep(6,7) : Warning no-unused-params: Parameter "name" is declared but never used. [https://aka.ms/bicep/linter/no-unused-params] Generating readme for [avm-network/hub-networking/main.bicep] WARNING: Resource type [hubnetworking] does not exist in the API / is custom. Falling back to it as default. WARNING: No resource type like [Microsoft.Network/hubnetworking] found in template. Falling back to it as identifier. InvalidOperation: /Users/matthewschmitt/GIT/bicep-registry-modules/avm/utilities/pipelines/sharedScripts/Set-ModuleReadMe.ps1:1327 Line | 1327 | $moduleDeploymentPropertyIndent = ([regex]::Match($rawBicepEx … | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ | Cannot index into a null array. Processed [0/1] files [0% complete`

Hey @hundredacres,  can you share a link to your pipeline run with me / the branch you're developing in? My running assumption is that the test files are already formatted in V2. Disabling the V2 formatter as per the merged PR does not format them back. So they may still be in a not perfectly compatible state. 
Note I spent my last couple nights to work on a fix for the readme script too, but until that is in, I think it would make sense that we sort this out for you first :)

**Comment by hundredacres** [comment]
@AlexanderSehr Here's my branch: https://github.com/hundredacres/bicep-registry-modules/tree/hubspoke

**Comment by eriqua** [comment]
This issue has been closed automatically by PR [#1321](https://github.com/Azure/bicep-registry-modules/pull/1321) 
If not intended please @hundredacres @AlexanderSehr feel free to reopen it
