### ISSUE TITLE
[Module Proposal]: `avm-res-network-expressroutecircuit (tf)`

### ISSUE THREAD

**Issue by PmeshramPM** [Azure/Azure-Verified-Modules#780]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-network-expressroutecircuit

### Module Details

Terraform module for ExpressRoute Circuit

### Do you want to be the owner of this module?

No

**Comment by mbilalamjad** [comment]
There is already a module proposal for this
https://github.com/Azure/Azure-Verified-Modules/issues/589

Also, it seems it is being covered by the following pattern module.
https://registry.terraform.io/modules/Azure/avm-ptn-vnetgateway/azurerm/latest

So, we might need to reconcile if separate resource modules are required for express route gateway and circuit or if the pattern module is sufficient to cater to all use cases.

**Comment by PmeshramPM** [comment]
Thanks @mbilalamjad - Based on our internal discussions, we all agree to go ahead with the resource module.

**Comment by mbilalamjad** [comment]
> Thanks @mbilalamjad - Based on our internal discussions, we have consensus to go ahead with the resource module.

Would recommend closing this proposal one in favor of the existing [module proposal](https://github.com/Azure/Azure-Verified-Modules/issues/589)

**Comment by prjelesi** [comment]
Closing as duplicated.
