### ISSUE TITLE
[Module Proposal]: `avm-res-network-expressroutegateway (tf)`

### ISSUE THREAD

**Issue by PmeshramPM** [Azure/Azure-Verified-Modules#781]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-network-expressroutegateway

### Module Details

Terraform module for Express Route Gateway

### Do you want to be the owner of this module?

No

**Comment by mbilalamjad** [comment]
I believe this is already covered by the following module.
https://registry.terraform.io/modules/Azure/avm-ptn-vnetgateway/azurerm/latest

**Comment by prjelesi** [comment]
@PmeshramPM are we closing this?

**Comment by PmeshramPM** [comment]
@prjelesi - yes please. Based on last discussion we are closing Express Route Gateway , VPN Gateway. They are part of VWan Module. Could you please raise issue for Vwan module for zone redundancy ?

**Comment by prjelesi** [comment]
Closing as we agree.
