### ISSUE TITLE
[Question/Feedback]: Where do I find the version information for a Module

### ISSUE THREAD

**Issue by johnwildes** [Azure/Azure-Verified-Modules#783]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

I apologize for the noob question here, but where do I find the version information for a module?  When I visit the Registry page for bicep resource modules, I see no version information and am taken to the GitHub repo for documentation.  

![image](https://github.com/Azure/Azure-Verified-Modules/assets/1375512/934e828e-d2ea-4692-8bf7-24e953936c7e)

**Comment by johnwildes** [comment]
Closing, found correct bicep registry index link. https://azure.github.io/bicep-registry-modules/

**Comment by johnwildes** [comment]
Apologies for re-opening...but issue still persists.  Link mentioned above has only a handful of modules listed.  They are not AVM modules, and the AVM module index doesn't list versions.  So the issue is that AVM index pages do not list versions, which is making it difficult for me to deploy these modules.  Please advise where versions are published at.

No Versions displayed below at this url https://azure.github.io/Azure-Verified-Modules/indexes/bicep/bicep-resource-modules/ this is where versions are supposed to be displayed.  Clicking on any of these modules takes you to the respective code repo where the module exists, where documentation of examples exists, but none of them report on versions available in the registry.

![image](https://github.com/Azure/Azure-Verified-Modules/assets/1375512/5346207c-c761-44e9-8127-88fb51d0c444)

**Comment by matebarabas** [comment]
Hi @johnwildes, thank you for opening this issue!

To use IntelliSense in VS Code to explore the published versions of a given module, you must park your cursor right after the semicolon that comes after the module's name, just like this: 
<img width="631" alt="image" src="https://github.com/Azure/Azure-Verified-Modules/assets/22733424/32f9a9ca-cb68-446c-8ac3-21a09f75ea11">

If you try to hit `CTRL+SPACE` without having that semicolon typed in first, IntelliSense may not work. In case you're still having challenges with making this work, I recommend checking that you have the latest version of all the things in use (Bicep, VS Code, and the Bicep extension for VS Code).

**The recommended way of exploring module versions is via IntelliSense.** This way, when you hover over the module's name (or the "module" word itself) in VS Code, you can click on "View Documentation" which will open the `README.md` of the very version of the module you selected, as shown on the below screenshot:
<img width="381" alt="image" src="https://github.com/Azure/Azure-Verified-Modules/assets/22733424/7381b26f-36ad-471b-a60d-c25b6b4de907">

The module index you first linked is pointing to the "old", non-AVM modules, that we're in the process of retiring. Your assessment is correct, we don't have the modules' available versions listed in our [module indexes](https://aka.ms/AVM/ModuleIndexes) today. This is a feature we're planning to implement in the near future, however. 

Until then, if you'd like to "geek out" and get this information for yourself without using VS Code IntelliSense, you can find all the published versions here: https://aka.ms/AVM/BRMModuleIndex 

<img width="874" alt="image" src="https://github.com/Azure/Azure-Verified-Modules/assets/22733424/5ff3bf60-f3c6-4352-b48d-802cea5a2395">

Please note however, that depending on the browser you use, you might need to quickly scroll through the whole JSON metadata file first to be able to use `CTRL+F` to find what you're looking for!

I hope this helps. Please let us know if you need further help with this issue!

**Comment by johnwildes** [comment]
@matebarabas thanks for this info.  I didn't wait for the intellisense to kick in.  I have GitHub Copilot enabled , sometimes there's conflicts.  It would be nice to see version history at some point, is this going to be available?

**Comment by matebarabas** [comment]
Yes, absolutely! Please see this part of my response: "_...we don't have the modules' available versions listed in our [module indexes](https://aka.ms/AVM/ModuleIndexes) today. This is a feature we're planning to implement in the near future, however._"

**Comment by johnwildes** [comment]
Thanks @matebarabas ...I see that portion...was reading through quickly.
