### ISSUE TITLE
[Module Proposal]: `avm-res-portal-dashboard`

### ISSUE THREAD

**Issue by azure-lm** [Azure/Azure-Verified-Modules#788]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-portal-dashboard

### Module Details

We would like to create an AVM resource module to deploy an Azure Portal Dashboard: https://learn.microsoft.com/en-us/azure/azure-portal/azure-portal-dashboards

We expect this will largely be a wrapper around the azure dashboard module: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/portal_dashboard

This resource module will take the dashboard JSON (as well as other values) as parameters and deploy the dashboard with this JSON. This resource module will not manage or influence the dashboard JSON generation.

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

azure-lm

**Comment by prjelesi** [comment]
HI @azure-lm , 

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by azure-lm** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by prjelesi** [comment]
@azure-lm i just need to align with team how we will continue with this. Please give me a day.

**Comment by prjelesi** [comment]
Hi @azure-lm , 

sorry for this take so long.


Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

Before starting development, please ensure ALL the following requirements are met.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - for naming your module
  - `TelemetryIdPrefix` - for your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repo name and folder path are defined in `RepoURL`
  - Create GitHub teams for module owners and contributors and grant them permissions as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
  - Grant permissions for the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

Check if this module exists in the other IaC language. If so, collaborate with the other owner for consistency. 👍

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published! Please include a link pointing to your PR, once available. 🙏**

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by Menghua1** [comment]
@jongio for notification.

**Comment by VeronicaSea** [comment]
Hi @prjelesi , we are working on it and follow the release process.

**Comment by VeronicaSea** [comment]
I have completed my initial development of the module and I would like to request a review of my module before publishing it to the terraform registry. The latest code is in a PR titled [AVM-Review-PR](REPLACE WITH URL TO YOUR PR) on the module repo and all checks on that PR are passing.

**Comment by v-xuto** [comment]
@VeronicaSea We tested this module `avm-res-portal-dashboard` and found one issue, please review.
- https://github.com/Azure/terraform-azurerm-avm-res-portal-dashboard/issues/7
