### ISSUE TITLE
[AVM Question/Feedback]: Output of `what-if` (if any) can't be trusted

### ISSUE THREAD

**Issue by o-l-a-v** [Azure/Azure-Verified-Modules#797]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

AVM suffers the same problem as CARML: Bicep / ARM `what-if` doesn't handle nested modules, and thus shows little to no output. Which means it's spray and pray for deploying stuff with AVM, as `what-if` can't be trusted.

Is anything being done about this from AVM point of view?

Related issues:

* https://github.com/Azure/arm-template-whatif/issues/157

**Comment by mbilalamjad** [comment]
@AlexanderSehr just double checking if you managed to add that disclaimer

**Comment by watfordsuzy** [comment]
Just ran into this disaster today, quite unexpected. Should be highlighted in red in big bold print.

Gone back to our flat files (ouch) in order to get visibility into what's going on with deployments.

**Comment by AlexanderSehr** [comment]
Hey folks, just a quick update. We just agreed on an approach for "Known Issues" in the docs and @jtracey93 will add the described issue there.

Also, we'll ping the PG to see how they're progressing on this issue.

**Comment by jtracey93** [comment]
As promised we have now put a "known issues" page in AVM and this topic is mentioned there: https://azure.github.io/Azure-Verified-Modules/help-support/known-issues/#bicep-what-if-compatibility-with-modules

cc: @AlexanderSehr

**Comment by o-l-a-v** [comment]
@jtracey93 and @AlexanderSehr: Thanks, I'm happy with the outcome. 🙂

Let's hope Bicep `what-if` is at a better place in three months:

* <https://github.com/Azure/arm-template-whatif/issues/157#issuecomment-2091086080>
