### ISSUE TITLE
[Module Proposal]: `avm-res-network-virtualrouter(tf)`

### ISSUE THREAD

**Issue by PmeshramPM** [Azure/Azure-Verified-Modules#814]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-network-virtualrouter

### Module Details

Resource module for Route Server -  Microsoft.Network/virtualRouters

### Do you want to be the owner of this module?

No

**Comment by prjelesi** [comment]
@PmeshramPM Thank you for proposing module. Will place this request in 'looking for owners' until we find owner.

**Comment by pagyP** [comment]
I'd be happy to own this

**Comment by SkouRene** [comment]
@pagyP If you want I would be happy to contribute to this

**Comment by prjelesi** [comment]
@PmeshramPM we will suspend this in favor virtualHubs one. 

@pagyP , @SkouRene will tag you there.

**Comment by prjelesi** [comment]
Closing as we agree that it is not needed.
