### ISSUE TITLE
[Question/Feedback]: Publish modules to OpenTofu module registry

### ISSUE THREAD

**Issue by sebastianstephan** [Azure/Azure-Verified-Modules#825]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Because of the license issues we and many other corporates are migrating from Terraform to OpenTofu. OpenTofu is implementing its own registry of modules though and simply using the Terraform AVM modules is not working.

There are already some AVM modules also published to openTofu module registry but not all and it seems to be a manual process. Just for pushing the JSON file.

Would it be feasible to enhance the module deployment pipelines to also publish to OpenTofu registry as well as to the official Terraform registry?

**Comment by matt-FFFFFF** [comment]
Hi @sebastianstephan 

We are monitoring the OpenTofu project and may in future support publishing to that registry. However we don't currently have a date for this feature. We will re-assess if/when priorities change.

Thanks!
