### ISSUE TITLE
[Module Proposal]: `avm-ptn-network-routeserver`

### ISSUE THREAD

**Issue by jchancellor-ms** [Azure/Azure-Verified-Modules#833]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Pattern Module

### Module Name

avm-ptn-network-routeserver

### Module Details

In virtual network implementations where it is required to share BGP routes between 3rd party NVA's and the Azure fabric Route Server is required.  This is functionality that mirrors capability in a VWAN hub in a virtual network.  This is a key component of AVS network design patterns.  https://learn.microsoft.com/en-us/azure/route-server/overview

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

jchancellor-ms

**Comment by pagyP** [comment]
Isn't this the same as #814 ?

**Comment by jchancellor-ms** [comment]
Based on what I understand, no - The virtual router resource is at ARM endpoint Microsoft.Network/VirtualRouters while the routeserver is just a BGP reflector that is a special implementation of VWAN virtual Hub functionality in a Vnet.  (Microsoft.Network/VirtualHubs).   They exist at two different resource endpoints.  It is possible that the intention was routeserver and the request was virtualrouter, so it may make sense for us to follow-up with the requestor to ensure we aren't duplicating effort and ensure accuracy.  @PmeshramPM - It looks like you were the original requestor of the virtualRouter resource.  Do you have additional details on what was intended there?
![image](https://github.com/Azure/Azure-Verified-Modules/assets/84210452/b7fa3f09-74c8-4aa7-8c9e-db50e47ee371)

**Comment by prjelesi** [comment]
@jchancellor-ms let me check this with @PmeshramPM offline and will get back to you.

**Comment by prjelesi** [comment]
@jchancellor-ms we will proceed with this and suspend other request. But i need quick sync with you. Will ping you on teams.

**Comment by prjelesi** [comment]
@jchancellor-ms ,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by jchancellor-ms** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by jchancellor-ms** [comment]
Initial development complete.  Still pending the following actions:
- legal review of the repo
- linking test environment to subscription
- publishing to tf registry

**Comment by prjelesi** [comment]
@jchancellor-ms we need to change module name. 

Since route server deployment is under Microsoft.Network/virtualHubs RP, we can do one of those:

- create avm-res-network-virtualhub resource module and provide examples how to deploy route server or virtual hub as part of vwan

or

- to proceed with pattern module that will be used just to deploy route server and with name avm-ptn-routeserver

@matebarabas FYI

**Comment by prjelesi** [comment]
@jchancellor-ms 

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

**Comment by prjelesi** [comment]
Hi @jchancellor-ms 

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

Before starting development, please ensure ALL the following requirements are met.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - for naming your module
  - `TelemetryIdPrefix` - for your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repo name and folder path are defined in `RepoURL`
  - Create GitHub teams for module owners and contributors and grant them permissions as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
  - Grant permissions for the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

Check if this module exists in the other IaC language. If so, collaborate with the other owner for consistency. 👍

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published! Please include a link pointing to your PR, once available. 🙏**

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by jchancellor-ms** [comment]
I would like to request a review of my module. The latest code is in a PR titled AVM-Review-PR on the module repo and all checks on that PR are passing.

**Comment by jchancellor-ms** [comment]
Thank you for requesting a review of your module. The AVM module review process has been initiated, please perform the **Requested Actions** on the AVM-Review issue on the module repo.

**Comment by jchancellor-ms** [comment]
The initial review of this module is complete and the module has been published to the registry. Requesting AVM team to close this module proposal and mark the module available in the module index.

**Comment by jchancellor-ms** [comment]
Module published
