### ISSUE TITLE
[Module Proposal]: `avm-res-network-subnet`

### ISSUE THREAD

**Issue by haflidif** [Azure/Azure-Verified-Modules#842]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-network-subnet

### Module Details

This module uses the `azapi` resource provider to deploy a subnet within an existing virtual network. It offers all the configurations that the native `azurerm_subnet` resource provides, along with the ability to associate an existing Network Security Group (NSG) and Route Table (RT) to the subnet in a single API call.

In this scenario the `azapi` resource provider serves as an alternative to the native `azurerm_subnet` resource to avoid conflicts with `deny` Azure Landing Zone policies. These policies include [Subnets should have a Network Security Group](https://www.azadvertizer.net/azpolicyadvertizer/Deny-Subnet-Without-Nsg.html) and [Subnets should have a User Defined Route](https://www.azadvertizer.net/azpolicyadvertizer/Deny-Subnet-Without-Udr.html), which are frequently implemented in large to medium-sized enterprises following the [Azure Landing Zone Reference Architecture](https://learn.microsoft.com/azure/architecture/landing-zones/terraform/landing-zone-terraform?wt.mc_id=SEC-MVP-5005265).

A version of a pattern module that I created which can be used to deploy a subnet, create new route table, and nsg in addition to other features already exists [haflidif/terraform-azurerm-alz-subnet](https://github.com/haflidif/terraform-azurerm-alz-subnet) , but here in this res module request I want to contribute to a resource module that is clean and creates the subnet and takes input for Route Table, NSG etc.

I've already talked to @jaredfholgate and he has agreed to be the Microsoft FTE Owner or Co-owner of this module and I would love to be either the owner or the secondary owner of this module in addition to @jaredfholgate.

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

haflidif

### (Optional) Secondary Module Owner's GitHub Username (handle)

jaredfholgate

**Comment by prjelesi** [comment]
@haflidif thanks for proposal, let me review and get back to you.

**Comment by haflidif** [comment]
> @haflidif thanks for proposal, let me review and get back to you.

Looking forward to it! - can't wait to start the development 💯

**Comment by matt-FFFFFF** [comment]
Hi @haflidif!

After some discussion we feel that this feature belongs in the existing virtual network module.

Our rationale is that this approach avoids confusion and retains the model that resource modules create all child resources as well.

The virtualnetwork module has the ability to create subnets on an existing vnet already.

I propose the azapi functionality for subnets is added via a PR, with a feature flag used to control the provider used.

What do you think?

**Comment by haflidif** [comment]
> Hi @haflidif!
> 
> After some discussion we feel that this feature belongs in the existing virtual network module.
> 
> Our rationale is that this approach avoids confusion and retains the model that resource modules create all child resources as well.
> 
> The virtualnetwork module has the ability to create subnets on an existing vnet already.
> 
> I propose the azapi functionality for subnets is added via a PR, with a feature flag used to control the provider used.
> 
> What do you think?

Yeah, that did cross my mind and would be a good addition to the virtual network module, so If I understand it correctly, what you are basically proposing is when using the virtual network module to create a subnet, then you would want a feature flag that would be either set to true or false that has the functionality to create a subnet using azapi_provider instead of using the azurerm_provider to create the subnet.

Although my approach here to have it as a seperate module was to be able to give Landing Zone owners in the scenario where a Landing Zone is often provided via the Azure Landing Zone Vending machine and virtual network is created without subnets.

Therefor giving Landing Zone Owners the possibility to calculate and decide their own subnet sizes, configurations etc, even though they have no control over the Virtual Network it self.

However that could as well be implemented within the virtual network module, to have a feature flag that has the possibility to create only subnet/s within a existing virtual network.

What do you think @matt-FFFFFF ?

**Comment by haflidif** [comment]
> > Hi @haflidif!
> > After some discussion we feel that this feature belongs in the existing virtual network module.
> > Our rationale is that this approach avoids confusion and retains the model that resource modules create all child resources as well.
> > The virtualnetwork module has the ability to create subnets on an existing vnet already.
> > I propose the azapi functionality for subnets is added via a PR, with a feature flag used to control the provider used.
> > What do you think?
> 
> Yeah, that did cross my mind and would be a good addition to the virtual network module, so If I understand it correctly, what you are basically proposing is when using the virtual network module to create a subnet, then you would want a feature flag that would be either set to true or false that has the functionality to create a subnet using azapi_provider instead of using the azurerm_provider to create the subnet.
> 
> Although my approach here to have it as a seperate module was to be able to give Landing Zone owners in the scenario where a Landing Zone is often provided via the Azure Landing Zone Vending machine and virtual network is created without subnets.
> 
> Therefor giving Landing Zone Owners the possibility to calculate and decide their own subnet sizes, configurations etc, even though they have no control over the Virtual Network it self.
> 
> However that could as well be implemented within the virtual network module, to have a feature flag that has the possibility to create only subnet/s within a existing virtual network.
> 
> What do you think @matt-FFFFFF ?

apologizes there @matt-FFFFFF didn't read your response quite well enough yesterday before commenting, but you already mentioned that.

> The virtualnetwork module has the ability to create subnets on an existing vnet already.

Therefor making my comment about the approach obsolete, however I like the idea of proposing a change to the virtual network module, I can contribute to that absolutely!

What is the best approach here @matt-FFFFFF, create an issue / improvement proposal on that particular module, or just start working on it and then just create a PR ?

**Comment by prjelesi** [comment]
@haflidif please create a issue, tag module owner and agree with him if you want to contribute. Also link this issue. 
If you need any help, let me know.

**Comment by prjelesi** [comment]
@haflidif i am closing this. If there is anything new that we can help, feel free to ping.
