### ISSUE TITLE
[Module Proposal]: `avm_res_api_management`

### ISSUE THREAD

**Issue by sharmilamusunuru** [Azure/Azure-Verified-Modules#847]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-apimanagement

### Module Details

Resource Module for API Management

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

sharmilamusunuru

**Comment by sharmilamusunuru** [comment]
Have noticed a open issue on the similar contribution

**Comment by lukemurraynz** [comment]
Hey, I've got draft Terraform module for API Management here: https://github.com/lukemurraynz/terraform-azurerm-avm-res-apimanagement-apimangement

Let me know if you have any thoughts, successfully deployed API Management with it, could be a good baseline to start.
