### ISSUE TITLE
[Module Proposal]: `terraform-azurerm-avm-res-compute-hostgroup

### ISSUE THREAD

**Issue by sharmilamusunuru** [Azure/Azure-Verified-Modules#848]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-compute-hostgroup

### Module Details

Resource Module for Dedicated hosts and hostgroup

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

sharmilamusunuru

**Comment by SkouRene** [comment]
I would like to contribue to this module.

**Comment by sharmilamusunuru** [comment]
@SkouRene Sure, I can add you as a secondary owner. However, I'm waiting for the team

**Comment by matt-FFFFFF** [comment]
@prjelesi can we move this on and can the author start work?

**Comment by matt-FFFFFF** [comment]
The module name will need correcting to be compliant

**Comment by prjelesi** [comment]
@sharmilamusunuru

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm you agree to the below pages that define what module ownership means:

[Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
[Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
[Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)
Any questions or clarifications needed, let us know!

If you agree, please just reply to this issue with the exact sentence below (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by sharmilamusunuru** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND
DEFINITION OF A MODULE OWNER

**Comment by SkouRene** [comment]
So what do we need to get the repo @sharmilamusunuru

**Comment by prjelesi** [comment]
@sharmilamusunuru i can see that this is already in dev. https://github.com/Azure/Azure-Verified-Modules/issues/577 let see what is status.

**Comment by SkouRene** [comment]
Why do two issues? @sharmilamusunuru

**Comment by prjelesi** [comment]
@SkouRene lets go to module proposal that is already in dev and see can we help to create module. I will tag you there.

**Comment by prjelesi** [comment]
Closing this as duplicated.

**Comment by chianw** [comment]
I would like to request a review of my module. The latest code is in a PR titled AVM-Review-PR on the module repo and all checks on that PR are passing.
