### ISSUE TITLE
[Module Proposal]: `avm-res-vwan`

### ISSUE THREAD

**Issue by sharmilamusunuru** [Azure/Azure-Verified-Modules#849]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-virtual-wan

### Module Details

Resource Module for Azure Virtual WAN and Hub

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

sharmilamusunuru

**Comment by prjelesi** [comment]
@sharmilamusunuru can you please check this https://registry.terraform.io/modules/Azure/avm-ptn-virtualwan/azurerm/latest

**Comment by prjelesi** [comment]
I am closing this request since there is pattern module that covers this.
