### ISSUE TITLE
[Feedback]: We have a new telemetry provider for TF module 

### ISSUE THREAD

**Issue by lonegunmanb** [Azure/Azure-Verified-Modules#85]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

We have a new [telemetry provider](https://github.com/Azure/terraform-provider-modtm) which could provide module usage telemetry data with more details.

To use this provider, all you need to do is adding such resource block in your module:

```hcl
resource "modtm_telemetry" "test" {
  tags = {
    avm_git_commit           = "2724cc167e90f94ce2511c3fb803400d0a486743"
    avm_git_file             = "main.tf"
    avm_git_last_modified_at = "2023-06-05 02:21:33"
    avm_git_org              = "Azure"
    avm_git_repo             = "terraform-provider-modtel"
  }
}
```

The `tags` would be sent to our telemetry collection service (an Azure Application Insight instance), every time our user execute `apply`/`refresh`/`plan`/`destroy` command with our module, an event with these tags and CRUD type would be sent to us along with an uuid represents resource instance id. We could learn how many module instances exist now, and the module names, versions.

Now this provider is blocked by some unknown issues so we cannot use it directly from the registry, once it has been unblocked maybe we should consider use it as verified module's telemetry solution.

**Comment by jtracey93** [comment]
Hey @lonegunmanb,

We cannot wait until this is available and will certainly migrate/update our specs and contribution guides here to use this instead of the current approach, when it is available under the `Azure` org banner as a provider 😍

**Comment by mbilalamjad** [comment]
@jtracey93 just circling back on this one to check if there are any actions that could be taken at this point in time to address the feedback ?

**Comment by jtracey93** [comment]
This is something that myself & @matt-FFFFFF will need to review to understand further.

We'll also then need to engage @matebarabas & Jordi so we can work out a migration path, if possible for our telemetry dashboards.

Key question from me is do we need to deploy our our telemetry collection service endpoint as described here: https://github.com/Azure/TerraformModuleTelemetryService - @lonegunmanb can you let us know?

**Comment by PmeshramPM** [comment]
@lonegunmanb - We are converting this conversation to an internal one and I will ping you the link to the ADO item. I will also setup a call to discuss the next steps.
