### ISSUE TITLE
[Feedback]: We don't need a seperated idempotency test

### ISSUE THREAD

**Issue by lonegunmanb** [Azure/Azure-Verified-Modules#86]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

[ID: SNFR7 - Category: Testing - Idempotency Tests](https://github.com/Azure/Azure-Verified-Modules/blob/060bab728a8b0f04666b66cd593051b2c691d811/docs/content/specs/shared/_index.md?plain=1#L309) described a testing that ensures deploying the module twice over the top of itself won't cause any config drift. We can add this idempotency as part of the e2e test, as we have done in [`terraform-module-test-helper`](https://github.com/Azure/terraform-module-test-helper/blob/v0.16.0/e2etest.go#L87-L89) library.

Idempotency should be part of our e2e testing acceptance criteria.

**Comment by jtracey93** [comment]
Hey @lonegunmanb,

Purely from a function/non-functional requirements perspective we believe that they are fine to leave as invidual items to call out. 

From an implementation perspective, following the contribution guides and template repos etc., they certainly can be combined into one set of tests/setps/jobs.

Closing as no action required
