### ISSUE TITLE
[Feedback]: Consider a github team for automation bot account

### ISSUE THREAD

**Issue by lonegunmanb** [Azure/Azure-Verified-Modules#87]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

[ID: SNFR9 - Category: Contribution/Support - AVM & PG Teams GitHub Repo Permissions](https://github.com/Azure/Azure-Verified-Modules/blob/060bab728a8b0f04666b66cd593051b2c691d811/docs/content/specs/shared/_index.md?plain=1#L379) described the teams that must be listed as repo's admin.

We should consider a special team which contains a bunch of bot accounts, those bots could serve automation service in our CI pipeline, such as auto-generate documents, sync module's owner list from Github teams, or something like that.

We should consider using these bots to do the daily chore maintenance jobs.

**Comment by jtracey93** [comment]
Hi @lonegunmanb,

Agreed we need to work together on making these "chores" more efficient. We can again pick this up in our syncs.

> As a side note, I don't thing bots can be members of GitHub Org Teams etc... - but we can work it out later

**Comment by mbilalamjad** [comment]
@jtracey93 was there any further updates on this or any actions determined to address the feedback, is this a long term thing ?

**Comment by jtracey93** [comment]
This is long term and no progress as of yet

**Comment by mbilalamjad** [comment]
Considering we're going to be using the Github app instead, closing this as no longer required, let us know offline if this needs to be re-opened and discussed further.
