### ISSUE TITLE
[Module Proposal]: `avm-ptn-networking-azurefirewall`

### ISSUE THREAD

**Issue by cshea-msft** [Azure/Azure-Verified-Modules#875]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Pattern Module

### Module Name

avm-ptn-networking-azurefirewall

### Module Details

Wanted to create a pattern module that deploys all of Azure Firewall WAF and APRL recommendations. It will include multiple modules for other services. 

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

cshea-msft

**Comment by prjelesi** [comment]
Hi @cshea-msft , we need more details why this should be pattern module. Can you provide some architecture diagram or anything else based on what this module will be developer?

**Comment by cshea-msft** [comment]
@prjelesi so there is an ask to have all modules follow up the APRL aka.ms/aprl recommendations. For Firewall some of the recommendations are easy to hard code like Zones but not setting monitoring or ddos on the vnet with the firewall. I can create examples but I thought maybe creating a Pattern that does all those things would work. 

Np if this doesn't fit but figured i would bring it up.

**Comment by prjelesi** [comment]
@cshea-msft let's take is offline and discuss. We will update issue based on agreement.

**Comment by prjelesi** [comment]
@cshea-msft we will pause this until we have clear picture what we will achieve with this pattern module.

**Comment by prjelesi** [comment]
I am closing this and we will reopen in case that we need to have pattern module to cover wider number of resources.
