### ISSUE TITLE
[Feedback]: Resource group variable type

### ISSUE THREAD

**Issue by lonegunmanb** [Azure/Azure-Verified-Modules#89]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

[ID: RMFR3 - Category: Composition - Resource Groups](https://github.com/Azure/Azure-Verified-Modules/blob/060bab728a8b0f04666b66cd593051b2c691d811/docs/content/specs/shared/_index.md?plain=1#L634) requires the variable name must be `resource_group`, which implies that the variable's type should be `object({ name = string})`. In most cases we will need resource group's name and the location that we want to provision module's resources in, and this location could be different than the resource group's location. So it's improper to use such type definition:

```hcl
variable "resource_group" {
  type = object({
    name     = string
    location = string
  })
} 
```

Using datasource to retrieve resource group's location might cause the resource location be `Known after apply` in the plan.

It's better to define `var.resource_group_name` and `var.location` instead.

**Comment by jtracey93** [comment]
Hi @lonegunmanb,

We will add clarity to RMFR3 as we do not intend to make the `resource_group` variable an object and indeed in our initial module development done by @matt-FFFFFF we are using `resource_group_name` and `location` as variables.

This is also covered by [SNFR14](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr14---category-inputs---data-types) to keep variable declarations simple where possible

**Comment by mbilalamjad** [comment]
@jtracey93 i see you made the update, is there any additional action required to address the feedback or this could be closed?
