### ISSUE TITLE
[Feedback]: Manage module indexes in GitOps way along with Terraform configuation files

### ISSUE THREAD

**Issue by lonegunmanb** [Azure/Azure-Verified-Modules#90]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

[ID: RMNFR1 - Category: Naming - Module Naming](https://github.com/Azure/Azure-Verified-Modules/blob/060bab728a8b0f04666b66cd593051b2c691d811/docs/content/specs/shared/_index.md?plain=1#L644) describes:

>We will maintain a set of CSV files in the [AVM Central Repo (`Azure/Azure-Verified-Modules`)](https://github.com/Azure/Azure-Verified-Modules/tree/main/docs/static/module-indexes) with the correct singular names for all resource types to enable checks to utilize this list to ensure repos are named correctly. To see the formatted content of these CSV files with additional information, please visit the [AVM Module Indexes](/Azure-Verified-Modules/indexes) page.

Static CSV files and markdown files only is not enough to manage these modules, we need a whole infrastructure to manage these repos along with corresponding testing infrastructure (testing pool, testing environment in verified module repos, etc..).

We have implemented such GitOps style infra in [terraform-azure-modules](https://github.com/Azure/terraform-azure-modules) repo, the document and list could be maintained along with the corresponding infrastructure.

**Comment by jtracey93** [comment]
Hi @lonegunmanb,

Happy to take this one into our internal syncs that we have already scheduled as we are not super clear on what is meant here.

For clarity the CSV is used mainly for the [module indexes](https://azure.github.io/Azure-Verified-Modules/indexes/) and tracking owners and the modules status, that are then the source of truth for our telemetry reporting and a few other pieces.

Thanks

**Comment by jtracey93** [comment]
Reopening due to OOF

**Comment by mbilalamjad** [comment]
> Hi @lonegunmanb,
> 
> Happy to take this one into our internal syncs that we have already scheduled as we are not super clear on what is meant here.
> 
> For clarity the CSV is used mainly for the [module indexes](https://azure.github.io/Azure-Verified-Modules/indexes/) and tracking owners and the modules status, that are then the source of truth for our telemetry reporting and a few other pieces.
> 
> Thanks

Echoing what @jtracey93 has mentioned, the CSVs are meant to be the source of truth for static data that requires the approval of an AVM core team member. We have also just recently implemented a new feature that shows the latest/all available versions of each module.

![image](https://github.com/Azure/Azure-Verified-Modules/assets/79409563/0fd1fd9c-32ab-4cd2-817a-beadf811938c)

As an example for resource modules, we are also planning to implement a feature that will show all [interfaces](https://azure.github.io/Azure-Verified-Modules/specs/shared/interfaces/) available in each module. Therefore, we will keep the modules indexes as is while continuously adding new dynamic features to the website representation.
