### ISSUE TITLE
[Module Proposal]: `avm-res-edge-site` [tf]

### ISSUE THREAD

**Issue by xwen11** [Azure/Azure-Verified-Modules#906]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-edge-site

### Module Details

Terraform module to provision Arc Site Manager

The module code is ready https://github.com/Azure/Edge-infrastructure-quickstart-template/tree/export-scale-doc/modules/site-manager

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

xwen11

### (Optional) Secondary Module Owner's GitHub Username (handle)

duzitong

**Comment by prjelesi** [comment]
@jeanchg let sync about this.

**Comment by xwen11** [comment]
Thanks! Do you want me to set up a meeting to discuss all of these three modules? 
@prjelesi  and @jeanchg

**Comment by prjelesi** [comment]
@xwen11 we change name based on naming convention 
![image](https://github.com/Azure/Azure-Verified-Modules/assets/5805065/eee2be97-b98a-4af1-ab66-e0a86b310a69)

https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-rmnfr1---category-naming---module-naming

i will process this.

**Comment by xwen11** [comment]
@prjelesi can we have an update here? What's the next step?

**Comment by prjelesi** [comment]
Hi @xwen11 ,


Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

Before starting development, please ensure ALL the following requirements are met.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - for naming your module
  - `TelemetryIdPrefix` - for your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repo name and folder path are defined in `RepoURL`
  - Create GitHub teams for module owners and contributors and grant them permissions as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
  - Grant permissions for the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

Check if this module exists in the other IaC language. If so, collaborate with the other owner for consistency. 👍

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published! Please include a link pointing to your PR, once available. 🙏**

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by xhy8759** [comment]
Hello, we splited site manager to a module.
Here is my PR: https://github.com/Azure/terraform-azapi-avm-res-site-manager/pull/5
I renamed it to `AVM-Review-PR` as your requirement and invited team `avm-core-team-technical-terraform` to review.
Could you help review it?

**Comment by xhy8759** [comment]
Refer: https://github.com/Azure/Azure-Verified-Modules/issues/1204

**Comment by xhy8759** [comment]
![image](https://github.com/user-attachments/assets/865d0a0a-6876-45c6-a683-ce7c7c233542)
We run e2e test locally and it passed.

**Comment by prjelesi** [comment]
@prjelesi explore possibilities to use azapi in repo

**Comment by prjelesi** [comment]
@xhy8759 as we agree we will proceed with azurerm in repo name

**Comment by prjelesi** [comment]
Index is updated

**Comment by mbilalamjad** [comment]
The initial review of this module is complete, and the module has been published to the registry. Requesting AVM team to close this module proposal and mark the module available in the module index.
Terraform Registry Link: https://registry.terraform.io/modules/Azure/avm-res-edge-site/azurerm/latest
GitHub Repo Link: https://github.com/Azure/terraform-azurerm-avm-res-edge-site
