### ISSUE TITLE
[Module Proposal]: `avm-res-azurestackhci-cluster` (tf)

### ISSUE THREAD

**Issue by xwen11** [Azure/Azure-Verified-Modules#907]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-azurestackhci-cluster

### Module Details

HCI cluster Terraform azapi module
https://github.com/Azure/Edge-infrastructure-quickstart-template/tree/export-scale-doc/modules/hci

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

xwen11

### (Optional) Secondary Module Owner's GitHub Username (handle)

duzitong

**Comment by prjelesi** [comment]
@jeanchg lets sync about this.

**Comment by PmeshramPM** [comment]
@prjelesi & @jeanchg - I had a sync with @xwen11 and continuing the process based on that. Lets connect if you have any questions.

**Comment by PmeshramPM** [comment]
Hi @xwen11,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm you agree to the below pages that define what module ownership means:

[Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
[Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
[Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)
Any questions or clarifications needed, let us know!

If you agree, please just reply to this issue with the exact sentence below (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by PmeshramPM** [comment]
@xwen11 - Please see that I have updated the module name based on our naming convention ( Terraform Resource Module Naming (https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-rmnfr1---category-naming---module-naming) 
Naming convention:
avm-res-<resource provider>-<ARM resource type> (module name for registry)
terraform-<provider>-avm-res-<resource provider>-<ARM resource type> (GitHub repository name to meet registry naming requirements))

**Comment by xwen11** [comment]
> "I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

**Comment by xwen11** [comment]
@prjelesi can we have an update here? What's the next step?

**Comment by prjelesi** [comment]
Hi @xwen11 

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

Before starting development, please ensure ALL the following requirements are met.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - for naming your module
  - `TelemetryIdPrefix` - for your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repo name and folder path are defined in `RepoURL`
  - Create GitHub teams for module owners and contributors and grant them permissions as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
  - Grant permissions for the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

Check if this module exists in the other IaC language. If so, collaborate with the other owner for consistency. 👍

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published! Please include a link pointing to your PR, once available. 🙏**

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by xwen11** [comment]
Hi @prjelesi , our code is ready and I would like to double check on the next steps.

Should we create a separate Github repo with the repo name matching module name?  Then copy all the code into the new repo?
Where should we put the test results? And what test cases should we include here?

**Comment by prjelesi** [comment]
HI @xwen11 lets schedule a call and cover all those things.

**Comment by xhy8759** [comment]
The module is renamed as terraform-azapi-avm-ptn-hci

**Comment by xhy8759** [comment]
I would like to request a review of my module. The latest code is in a PR titled AVM-Review-PR on the module repo and all checks on that PR are passing.
Here isour PR link:
https://github.com/Azure/terraform-azapi-avm-ptn-hci/pull/1

Test passes locally:
![hci](https://github.com/user-attachments/assets/bea2102d-27d8-4d3d-a0fb-046a570ccfe5)

**Comment by prjelesi** [comment]
@prjelesi  to check azapi

**Comment by prjelesi** [comment]
@xhy8759 azurerm as we agreed.

**Comment by xhy8759** [comment]
I would like to request a review of my module. The latest code is in a PR titled AVM-Review-PR on the module repo and all checks on that PR are passing.
Here isour PR link:
https://github.com/Azure/terraform-azurerm-avm-res-azurestackhci-cluster/pull/1

Test passes locally:
![hci](https://github.com/user-attachments/assets/362e0e2f-2661-4484-86e6-0460f5ed91e9)

**Comment by xhy8759** [comment]
The initial review of this module is complete, and the module has been published to the registry. Requesting AVM team to close this module proposal and mark the module available in the module index.
Terraform Registry Link: https://registry.terraform.io/modules/Azure/avm-res-azurestackhci-cluster/azurerm/latest
GitHub Repo Link: https://github.com/Azure/terraform-azurerm-avm-res-azurestackhci-cluster
