### ISSUE TITLE
[Module Proposal]: `avm-ptn-hci-server-provisioner` [tf]

### ISSUE THREAD

**Issue by xwen11** [Azure/Azure-Verified-Modules#908]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Pattern Module

### Module Name

avm-ptn-hci-server-provisioner

### Module Details

Terraform azapi module to execute Arc for Server registration

https://github.com/Azure/Edge-infrastructure-quickstart-template/tree/export-scale-doc/modules/hci-provisioners

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

xwen11

### (Optional) Secondary Module Owner's GitHub Username (handle)

duzitong

**Comment by PmeshramPM** [comment]
@prjelesi & @jeanchg  - I had a sync with @xwen11 and continuing the process based on that. Lets connect if you have any questions.

**Comment by PmeshramPM** [comment]
Hi @xwen11, 

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by PmeshramPM** [comment]
@prjelesi & @jeanchg - I had a sync with @xwen11 and continuing the process based on that. Lets connect if you have any questions.

**Comment by prjelesi** [comment]
@xwen11 we are changing this to pattern will process.

**Comment by xwen11** [comment]
Hi, @prjelesi What's the next step?

**Comment by prjelesi** [comment]
Hi @xwen11 

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

Before starting development, please ensure ALL the following requirements are met.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - for naming your module
  - `TelemetryIdPrefix` - for your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repo name and folder path are defined in `RepoURL`
  - Create GitHub teams for module owners and contributors and grant them permissions as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
  - Grant permissions for the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

Check if this module exists in the other IaC language. If so, collaborate with the other owner for consistency. 👍

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published! Please include a link pointing to your PR, once available. 🙏**

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by xhy8759** [comment]
We need to implement two modules: avm-ptn-hci-ad-provisioner and avm-ptn-hci-server-provisioner.

**Comment by xhy8759** [comment]
I would like to request a review of my module. The latest code is in a PR titled AVM-Review-PR on the module repo and all checks on that PR are passing.
Here are our PR links:
https://github.com/Azure/terraform-azapi-avm-ptn-hci-ad-provisioner/pull/2
https://github.com/Azure/terraform-azapi-avm-ptn-hci-server-provisioner/pull/2

Tests pass locally:
![server](https://github.com/user-attachments/assets/b4aa02bb-d0f9-4924-ba94-898418d8e25b)
![ad](https://github.com/user-attachments/assets/dcb500a5-10d1-46c7-82fc-9ccb8c98c27d)

**Comment by xhy8759** [comment]
As @mbilalamjad said, we cannot have two modules under one module proposal, they need to have individual module proposals approved.
We hope to rename this module as `avm-ptn-hci-server-provisioner`, and I will submit a new proposal for another module as `avm-ptn-hci-ad-provisioner`. @prjelesi 
These two modules are hci preparation steps, the one-time setup scripts for hci AD and servers. No ARM resources are created by providers.
Is thak OK?

**Comment by prjelesi** [comment]
@predrag to finish with this name

**Comment by prjelesi** [comment]
Index is updated

**Comment by xhy8759** [comment]
I would like to request a review of my module. The latest code is in a PR titled AVM-Review-PR on the module repo and all checks on that PR are passing.
Here are our PR links:
https://github.com/Azure/terraform-azurerm-avm-ptn-hci-server-provisioner/pull/2

Tests pass locally:
![server](https://github.com/user-attachments/assets/353274c7-0e76-49d3-9f18-ed6ef0c41a77)

**Comment by xhy8759** [comment]
The initial review of this module is complete, and the module has been published to the registry. Requesting AVM team to close this module proposal and mark the module available in the module index.
Terraform Registry Link: https://registry.terraform.io/modules/Azure/avm-ptn-hci-server-provisioner/azurerm/latest
GitHub Repo Link: https://github.com/Azure/terraform-azurerm-avm-ptn-hci-server-provisioner
