### ISSUE TITLE
[Feedback]: Consider modules that have no resource group

### ISSUE THREAD

**Issue by lonegunmanb** [Azure/Azure-Verified-Modules#93]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

[ID: RMNFR2 - Category: Inputs - Parameter/Variable Naming](https://github.com/Azure/Azure-Verified-Modules/blob/060bab728a8b0f04666b66cd593051b2c691d811/docs/content/specs/shared/_index.md?plain=1#L788) describes:

>- `location` (use Resource Group location, if resource supports Resource Groups, otherwise no default)

Some resources are global resource that do not belong to resource group (e.g.: [`azurerm_management_group_policy_assignment`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/management_group_policy_assignment).

**Comment by jtracey93** [comment]
Hey @lonegunmanb,

We have reviewed this and believe what we have documented handles your query already:
![image](https://github.com/Azure/Azure-Verified-Modules/assets/41163455/59448557-a70b-4c0d-b7b0-a98fcfbe79ec)

Could you advise if you think this is sufficient or is further clarity required, if so please suggest?

**Comment by jtracey93** [comment]
Reopening due to OOF
