### ISSUE TITLE
[Module Proposal]: `avm/res/azure-stack-hci/deployment-settings`

### ISSUE THREAD

**Issue by mbrat2005** [Azure/Azure-Verified-Modules#930]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes.

### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/azure-stack-hci/deployment-settings

### Module Details

Azure Stack HCI Cluster deployment settings resource

Deriving from https://github.com/Azure/azure-quickstart-templates/tree/master/quickstarts/microsoft.azurestackhci/create-cluster-with-prereqs

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

mbrat2005

### (Optional) Secondary Module Owner's GitHub Username (handle)

steveswalwell

**Comment by matebarabas** [comment]
Closing this, as this is a child of the "AzureStackHCI/clusters " resource, and will be implemented through that.
