### ISSUE TITLE
[Question/Feedback]: Is there a project-wide convention for the length of resource names?

### ISSUE THREAD

**Issue by sstjean** [Azure/Azure-Verified-Modules#938]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

I am looking at a number of AVM modules and noting that they all restrict the size of resource names to 24 characters.  The Bastion module, for instance, has a 24 char limit but the actual length of the resource is 80 characters.  Can you add a coding standard that the lengths specified in the article below are to be used for length verification?

https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules

Thank you.

**Comment by ChrisSidebotham** [comment]
@sstjean - Can you link to a module you are referring too? I have checked both Bicep and Terraform and cannot see any restrictions regarding name length on these modules. Typically, we wouldn't apply these restrictions in the module without good reason as they can change without us knowing.

**Comment by sstjean** [comment]
Please look at the Public IP name validation in Terraform 
https://github.com/Azure/terraform-azurerm-avm-res-network-publicipaddress/blob/80db65fb3a68e157dbcc3e6c6810e1170b832ebd/variables.tf#L22

There are additional repos that show the same, like the DDoS Pretection Plan.
https://github.com/Azure/terraform-azurerm-avm-res-network-ddosprotectionplan/blob/d82200a8d73dd8f967e1e46d830ee775d5618175/variables.tf#L21

**Comment by ChrisSidebotham** [comment]
@prjelesi & @sitarant - Are you able to take a look into this as these modules are owned by yourselves. Maybe something for Core Team dicsussion. Thanks @sstjean - leave this with us for a few days please, conscious we have public holidays coming up also

**Comment by sitarant** [comment]
@ChrisSidebotham will take care of it next week

**Comment by prjelesi** [comment]
Hi, @sstjean, updated on ddos protection plan and public ip. Thanks for heads up. 
@ChrisSidebotham this check was originating from old TF template repo. We will maybe find it on more TF modules that are created in early phase of AVM.
