### ISSUE TITLE
[Module Proposal]: `avm/ptn/data/private-analytical-workspace`

### ISSUE THREAD

**Issue by jbinko** [Azure/Azure-Verified-Modules#949]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes.

### Bicep or Terraform?

Bicep

### Module Classification?

Pattern Module

### Module Name

avm/ptn/data/private-analytical-workspace

### Module Details

This pattern module aims to provide a set of Azure services that work Together often for data analytics workloads. It helps Azure customers in highly regulated industries deploy such a set faster with high security and privacy. Most services should not use public IP and should go through HUB, spoke, and firewall. This is common in healthcare and finance. I have used this pattern many times and want to make it part of the AVM + follow AVM specs + refresh to the latest features. I posted this pattern in in the past in the Azure repo for my customers to use. This is based on practical experience with customers and practical requirements in the industry.                                                                                                https://github.com/Azure/ADAW

![Alt text](https://github.com/Azure/ADAW/raw/main/DocImages/Overview.png "Architecture Diagram")

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

jbinko

**Comment by matebarabas** [comment]
Hi @jbinko, thanks for proposing and volunteering to own this module! I've pinged you internally to clarify a few questions before proceeding with the triage of this module.

**Comment by matebarabas** [comment]
Hi @jbinko,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by jbinko** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by matebarabas** [comment]
Hi @jbinko,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

Before starting development, please ensure ALL the following requirements are met.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - for naming your module
  - `TelemetryIdPrefix` - for your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repo name and folder path are defined in `RepoURL`
  - Create GitHub teams for module owners and contributors and grant them permissions as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
  - Grant permissions for the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

Check if this module exists in the other IaC language. If so, collaborate with the other owner for consistency. 👍

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published! Please include a link pointing to your PR, once available. 🙏**

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by jbinko** [comment]
Here is the fork and branch where the development is in the progress: https://github.com/jbinko/bicep-registry-modules/tree/private-analytical-workspace/avm/ptn/data/private-analytical-workspace

**Comment by jbinko** [comment]
Note for bot: Work in progress

**Comment by jbinko** [comment]
The initial version 0.1 implementation is complete, and a pull request has been submitted. This includes documentation, unit tests, and PowerShell post-unit tests.

https://github.com/Azure/bicep-registry-modules/pull/3307

**Comment by jbinko** [comment]
@matebarabas - The module has been successfully published.
Any next steps from my side? Can we close this issue?

module paw 'br/public:avm/ptn/data/private-analytical-workspace:0.1.0' = {
  name: name
  params: {
    name: name
  }
}

**Comment by matebarabas** [comment]
- [x] Module published.
- [x] GitHub teams are available and assigned to their parents.
- [x] `CODEOWNERS` file updated.
- [x] Issue template file updated.
 
Thank you for your work @jbinko! I'm closing this issue now.

**Comment by jbinko** [comment]
@matebarabas: Thank you.
I do not see the change about being published (it is still in Proposed state) here:
https://github.com/Azure/Azure-Verified-Modules/blob/main/docs/static/module-indexes/BicepPatternModules.csv
and here:
https://azure.github.io/Azure-Verified-Modules/indexes/bicep/bicep-pattern-modules/

Does the propagation require more time?
