### ISSUE TITLE
[Module Proposal]: `avm-res-elasticsan-elasticsans`

### ISSUE THREAD

**Issue by jchancellor-ms** [Azure/Azure-Verified-Modules#954]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-elasticsan-elasticsans

### Module Details

AVS and other baremetal services leverage the new ElasticSan service offering for additional high-performance IScsi block storage.  This proposal is for a resource module that enables that capability.

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

jchancellor-ms

**Comment by prjelesi** [comment]
Hi @jchancellor-ms 

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR
