### ISSUE TITLE
[Module Proposal]: `avm-res-network-networkwatcher-flowlog`

### ISSUE THREAD

**Issue by terrymandin** [Azure/Azure-Verified-Modules#963]
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-network-networkwatcher-flowlog

### Module Details

This module will allow customers to create flow logs and optionally enable traffic analytics.  Network Watcher has been identified as required for EPIC.  As part of the [Network Watcher AVM analysis](https://github.com/Azure/Azure-Verified-Modules/issues/236#issuecomment-2113033190), it was determined that a separate flow log AVM was required.

Please double check the module name as this is a sub resource of Network Watcher.  This is the way flow logs appear in the Azure.Network resource provider:

![image](https://github.com/Azure/Azure-Verified-Modules/assets/833055/71fbf23d-7e5f-42a5-b176-39072bac6577)

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

terrymandin

**Comment by prjelesi** [comment]
@PmeshramPM for visibility

**Comment by prjelesi** [comment]
@terrymandin we are closing this and will proceed with parent one as we agreed.
