### ISSUE TITLE
[Module Proposal]: `avm-res-network-networkwatcher-connectionmonitor`

### ISSUE THREAD

**Issue by terrymandin** [Azure/Azure-Verified-Modules#964]
### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-network-networkwatcher-connectionmonitor

### Module Details

This module will allow customers to enable connection monitoring.  Network Watcher has been identified as required for EPIC.  As part of the [Network Watcher AVM analysis](https://github.com/Azure/Azure-Verified-Modules/issues/236#issuecomment-2113033190), it was determined that a separate connection monitoring AVM was required.

Please double check the module name as this is a sub resource of Network Watcher.  This is the way flow logs appear in the Azure.Network resource provider:

![image](https://github.com/Azure/Azure-Verified-Modules/assets/833055/4820f6c3-3e34-4c2e-ac19-d64715cbc471)

### Do you want to be the new owner of this module?

Yes

### Module Owner's GitHub Username (handle)

terrymandin

**Comment by prjelesi** [comment]
@PmeshramPM for visibility

**Comment by prjelesi** [comment]
@terrymandin we are closing this and will proceed with parent one as we agreed.
