### ISSUE TITLE
[Orphaned Module]: `avm-res-network-virtualnetwork`

### ISSUE THREAD

**Issue by PmeshramPM** [Azure/Azure-Verified-Modules#968]
### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-network-virtualnetwork

### Module Details

This module was originally created by @herms14.
 
**Note**: when someone volunteers to be the owner of this module, please reach out to @herms14   for changing the ownership of the existing GitHub teams as well.
 
- Module proposal: https://github.com/Azure/Azure-Verified-Modules/issues/62 
- PR: https://github.com/Azure/terraform-azurerm-avm-res-network-virtualnetwork

### Do you want to be the new owner of this module?

No

### Module Owner's GitHub Username (handle)

jaredfholgate

**Comment by prjelesi** [comment]
Changed to @jaredfholgate

**Comment by jaredfholgate** [comment]
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by PmeshramPM** [comment]
closing this one now
