### ISSUE TITLE
[Question/Feedback]: How do we change the MI for the e2e testing workflow?

### ISSUE THREAD

**Issue by ibersanoMS** [Azure/Azure-Verified-Modules#997]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

I updated the client_id, subscription_id, and tenant_id in the test environment for [my module ](https://github.com/Azure/terraform-azurerm-avm-res-web-serverfarm), but it keeps failing because it's still using an old MI with the previous owner's subscription. I see there's an environment variable `MSI_ID` being used, but I don't see where it's initialized/set.

**Comment by matebarabas** [comment]
@Azure/avm-core-team-technical-terraform, please take a look. Thanks!

**Comment by mbilalamjad** [comment]
@matt-FFFFFF could you advise on this

**Comment by matt-FFFFFF** [comment]
Hi,

Why do you want to change the MSI? It is intrinsic to the Azure resource running the test.

The test environment is deliberately isolated as a security measure.

**Comment by jtracey93** [comment]
@ibersanoMS can you help answer @matt-FFFFFF's question here

#RR

**Comment by ibersanoMS** [comment]
The instructions in the template repo readme confused me as to whether the repo was using my subscription or a supplied test subscription which is why I was trying to change that. Now that I know it's using a supplied subscription, this question isn't relevant. Thanks!

**Comment by matt-FFFFFF** [comment]
Apologies. @mbilalamjad was going to fix this I think
